### ISSUE TITLE
EBADF error when parsing a large media collection

### ISSUE THREAD

**Issue by Draskas** [Borewit/music-metadata#1]
I'm running into a strange issue after porting some code from the original `musicmetadata` package. When the `console.log` is uncommented, the example below can parse 2000+ music files without ever having a single issue. 

However, the moment you comment out that line. calling `.close()` on the `fileStream` will occasionally throw a `EBADF: bad file descriptor, read` after parsing some of the files.

**MUSIC-METADATA:**

```typescript
import * as Chokidar from "chokidar"
import * as Path from "path"
import * as Fs from "fs"
import * as Metadata  from "music-metadata"

let tags = []
let watcher = Chokidar.watch(
  "/Music/**/*.mp3",
  {
    ignoreInitial: false,
    alwaysStat: false
  }
)

watcher.on("add", (file, fstat) =>
{
  let fileStream = Fs.createReadStream(file)
  Metadata.parseStream(fileStream, { native: true }, (error, metadata) =>
  {
    // console.log("no EBADF ever if this line uncommented")
    fileStream.close() // will occasionally throw `EBADF: bad file descriptor, read`
    tags.push(metadata)
  })
})

```

The same code using the original `musicmetadata` package will iterate over the same files without ever once throwing an `EBADF` error, and without the need of the `console.log`

**MUSICMETADATA:**

```typescript
import * as Chokidar from "chokidar"
import * as Path from "path"
import * as Fs from "fs"
import * as Metadata  from "musicmetadata"

let tags = []
let watcher = Chokidar.watch(
  "/Music/**/*.mp3",
  {
    ignoreInitial: false,
    alwaysStat: false
  }
)

watcher.on("add", (file, fstat) =>
{
  let fileStream = Fs.createReadStream(file)
  Metadata(fileStream, (error, metadata) =>
  {
    fileStream.close()
    tags.push(metadata)
  })
})
```

**Comment by Borewit** [comment]
@Draskas: Are you willing to give it another try with v0.7.0?
