### ISSUE TITLE
Be able to write tags

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#10]

**Comment by Yuudaari** [comment]
This would be so nice to have! I could implement details editing in my own music app...

I saw you comment on another issue that you've only seen this done in python, I found a [node module that it's implemented in](https://github.com/Zazama/node-id3). (Only works for MP3 tho)

**Comment by Borewit** [comment]
It would indeed be very nice @Yuudaari , but it will cost so much effort as well.

[node-id3](https://github.com/Zazama/node-id3) can set some tags on MP3 file, probably only one ID3 version, they did not bother to specify which one. 

What happens if there is already metadata present of another version?

Point is, it just a very limited scope. I don't think I'll get away with that. You guys will keep asking me for more until I covered the whole spectrum in writing functionality, based on expectations I set with reading capability ;-). 

And to meet does expectations, there are some serious challenges:
* Ability to write tags using the common interface
* Keep it lean, those module is primary written for Node, but I am now investigating if it can run [in the browser](https://music-metadata-webamp.netlify.com/) as well.
* Make sure it works, I don't want people around complaining that they destroyed 10.000 audio tracks thanks to a bug
* I want to avoid dependent application are going to suffer from changes
* Writing requires a different approach / architecture then reading, it not just making stuff work in the other direction.

**Comment by Borewit** [comment]
I am considering to implement it @FranzSkuffka, it will be a lot of work.

**Comment by FranzSkuffka** [comment]
That's great. Can you share some directions in this thread for the sake of accessibility?

**Comment by t-MURO** [comment]
> 
> 
> I am considering to implement it @FranzSkuffka, it will be a lot of work.
> Can you get in touch via chat: https://discord.gg/KyBr6sb

Have you started working on that module? I would be interessted in following it's development :)

I would even like to help out but I'm still a beginner developer...

May I also get an invite to your discrod?

Cheers!

**Comment by Borewit** [comment]
Working didn't start.
Sure you can join, the [invite is permanent](https://discord.gg/KyBr6sb).
