### ISSUE TITLE
Failed to parse source map from

### ISSUE THREAD

**Issue by Paul6552** [Borewit/music-metadata#1027]
**Bug description**
After updating my react-app from webpack 4 to webpack 5 I get error messages from music-metadata.

According to [this topic](https://github.com/facebook/create-react-app/discussions/11767) it seems that the library `music-metadata` is having a wrong source-map output?

**Expected behavior**
No error messages

<details>
<summary>Error message</summary>
WARNING in ./node_modules/@react-keycloak/core/lib/context.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/context.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/context.ts'
 @ ./node_modules/@react-keycloak/core/lib/index.js 2:0-26 2:0-26
 @ ./node_modules/@react-keycloak/web/lib/provider.js 1:0-58 3:35-53
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/core/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/index.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/index.ts'
 @ ./node_modules/@react-keycloak/web/lib/provider.js 1:0-58 3:35-53
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/core/lib/provider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/provider.tsx' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/provider.tsx'
 @ ./node_modules/@react-keycloak/core/lib/index.js 3:0-27 3:0-27
 @ ./node_modules/@react-keycloak/web/lib/provider.js 1:0-58 3:35-53
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/core/lib/types.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/types.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/core/lib/@react-keycloak/core/types.ts'
 @ ./node_modules/@react-keycloak/core/lib/index.js 4:0-24 4:0-24
 @ ./node_modules/@react-keycloak/web/lib/provider.js 1:0-58 3:35-53
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/web/lib/context.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/context.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/context.ts'
 @ ./node_modules/@react-keycloak/web/lib/provider.js 2:0-52 3:54-77
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/web/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/index.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/index.ts'
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/web/lib/provider.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/provider.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/provider.ts'
 @ ./node_modules/@react-keycloak/web/lib/index.js 1:0-27 1:0-27
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/web/lib/useKeycloak.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/useKeycloak.ts' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/useKeycloak.ts'
 @ ./node_modules/@react-keycloak/web/lib/index.js 2:0-30 2:0-30
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/@react-keycloak/web/lib/withKeycloak.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/withKeycloak.tsx' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/@react-keycloak/web/lib/@react-keycloak/web/withKeycloak.tsx'
 @ ./node_modules/@react-keycloak/web/lib/index.js 3:0-31 3:0-31
 @ ./src/index.tsx 9:0-60 27:38-59

WARNING in ./node_modules/music-metadata/lib/apev2/APEv2TagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/apev2/APEv2TagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/apev2/APEv2TagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 16:25-59
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/apev2/APEv2Token.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/apev2/APEv2Token.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/apev2/APEv2Token.js.map'
 @ ./node_modules/music-metadata/lib/apev2/APEv2Parser.js 18:21-44
 @ ./node_modules/music-metadata/lib/core.js 14:22-52
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/asf/AsfTagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/asf/AsfTagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/asf/AsfTagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 12:23-53
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/CaseInsensitiveTagMap.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/CaseInsensitiveTagMap.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/CaseInsensitiveTagMap.js.map'
 @ ./node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js 10:32-74
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 10:26-61
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/CombinedTagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/CombinedTagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/CombinedTagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/FourCC.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/FourCC.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/FourCC.js.map'
 @ ./node_modules/music-metadata/lib/aiff/AiffParser.js 16:17-44
 @ ./node_modules/music-metadata/lib/ParserFactory.js 18:21-49
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/GenericTagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/GenericTagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/GenericTagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 16:27-56
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/GenericTagTypes.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/GenericTagTypes.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/GenericTagTypes.js.map'
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 12:26-54
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/MetadataCollector.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/MetadataCollector.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/MetadataCollector.js.map'
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/common/Util.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/Util.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/common/Util.js.map'
 @ ./node_modules/music-metadata/lib/apev2/APEv2Parser.js 14:13-38
 @ ./node_modules/music-metadata/lib/core.js 14:22-52
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/id3v1/ID3v1TagMap.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v1/ID3v1TagMap.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v1/ID3v1TagMap.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 8:22-53
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/id3v2/ID3v22TagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v2/ID3v22TagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v2/ID3v22TagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 14:26-61
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 10:26-61
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/matroska/MatroskaTagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/matroska/MatroskaTagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/matroska/MatroskaTagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 24:28-68
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/matroska/types.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/matroska/types.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/matroska/types.js.map'
 @ ./node_modules/music-metadata/lib/matroska/MatroskaParser.js 14:16-34
 @ ./node_modules/music-metadata/lib/ParserFactory.js 42:25-61
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/mp4/MP4TagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/mp4/MP4TagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/mp4/MP4TagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 18:23-53
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/ogg/vorbis/VorbisTagMapper.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/ogg/vorbis/VorbisTagMapper.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/ogg/vorbis/VorbisTagMapper.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 20:26-66
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/riff/RiffInfoTagMap.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/riff/RiffInfoTagMap.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/riff/RiffInfoTagMap.js.map'
 @ ./node_modules/music-metadata/lib/common/CombinedTagMapper.js 22:25-58
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 14:28-58
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/music-metadata/lib/type.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/type.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/music-metadata/lib/type.js.map'
 @ ./node_modules/music-metadata/lib/common/MetadataCollector.js 8:15-33
 @ ./node_modules/music-metadata/lib/ParserFactory.js 16:28-65
 @ ./node_modules/music-metadata/lib/core.js 10:24-50
 @ ./node_modules/music-metadata-browser/lib/index.js 10:11-45 16:13-47
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

WARNING in ./node_modules/readable-web-to-node-stream/lib/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/readable-web-to-node-stream/lib/index.js.map' file: Error: ENOENT: no such file or directory, open '/home/paul/IdeaProjects/reactportal/portal-webapp/node_modules/readable-web-to-node-stream/lib/index.js.map'
 @ ./node_modules/music-metadata-browser/lib/index.js 12:38-76
 @ ./src/components/addDance.tsx 9:0-45 104:6-18
 @ ./src/components/router.tsx 13:0-34 304:72-80
 @ ./src/App.tsx 7:0-50 276:44-59
 @ ./src/index.tsx 7:0-24 32:33-36

</details>

**Comment by Borewit** [comment]
As far as I know music-metadata does not longer include source map files @Paul6552

**Comment by Paul6552** [comment]
ok. Thank you

**Comment by Konglomneshued** [comment]
Any way to surpress these warnings?  I have dozens of them in my console and it clutters them up.

**Comment by Borewit** [comment]
> Any way to surpress these warnings? I have dozens of them in my console and it clutters them up.

I think this problem is also reported here: #1509
