### ISSUE TITLE
Issue decoding UTF-16 strings in MP3's files in browser environments 

### ISSUE THREAD

**Issue by vneznaikin** [Borewit/music-metadata#1028]
Common metadata not support non latin languages! (Japanese for example)
For artist name ESPRIT 空想 retur asccii code "69,0,83,0,80,0,82,0,73,0,84,0,32,0,122,122,243,96,0,0"

And why it return data in ascii at all?

**Comment by Borewit** [comment]
Related to string encoding/decoding issues: #193, #614

Hello @vneznaikin, music-metadata should fully supports unicode, so also non latin languages like Japanese.

Can you please provide a sample?

**Comment by Borewit** [comment]
Is this the same issue https://github.com/Borewit/music-metadata-browser/issues/740?

**Comment by Fuchsoria** [comment]
> Is this the same issue [Borewit/music-metadata-browser#740](https://github.com/Borewit/music-metadata-browser/issues/740)?

In our case we are using standard english alphabet, and feature with metadata was implemented more than 6 months ago

**Comment by Borewit** [comment]
Understood, the issue has nothing to with Unicode. Can you help me to understand what could cause this? Do you get the same results using this web page: https://audio-tag-analyzer.netlify.app/?

Do you have code I can see?
What do you use to polyfill Node.js Buffer?

**Comment by Fuchsoria** [comment]
> 

Everything is fine through audio-tag-analyzer webpage. Here I created example and reproduced this issue with locked package versions: https://github.com/Fuchsoria/testmetadata/blob/master/src/App.js https://github.com/Fuchsoria/testmetadata/blob/master/package.json

**Comment by Fuchsoria** [comment]
But I think in my case I have issue because of react packages, so after update to latest version of react packages I just see "ReferenceError: Buffer is not defined"

**Comment by Borewit** [comment]
Same issue as https://github.com/Borewit/music-metadata-browser/issues/740, by using a [uint8array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) as a [Buffer](https://nodejs.org/api/buffer.html)

**Comment by Borewit** [comment]
Should be resolved in [music-metadata-browser v2.5.5](https://github.com/Borewit/music-metadata-browser/releases/tag/v2.5.5).
