### ISSUE TITLE
Wrong song duration

### ISSUE THREAD

**Issue by kmathmann** [Borewit/music-metadata#103]
I have issues with wrong song durations. The song from the example data has actually a length of 04:18 minutes. I saw that TagTypes contains `ID3v2.3` and that the tagType is not supported (#101).

Could the not supported tagType be the Problem for the wrong duration?

I'm using `parseStream`.

**data from example song**
```javascript
{ 
   format:   {
     lossless: false,
     dataformat: 'mp3',
     bitrate: 320000,
     sampleRate: 44100,
     numberOfChannels: 2,
     codecProfile: 'CBR',
     numberOfSamples: 3793536,
     duration: 86.02122448979591,
     encoder: 'LAME 3.99.5',
     tagTypes: [ 'ID3v2.3' ]
  },
  native: undefined,
  common:   {
     track: { no: 5, of: null },
     disk: { no: null, of: null },
     album: '10YEARS',
     artist: 'Jaxx & Vega vs. David Puentez vs. Mashup-Germany',
     bpm: '130',
     comment: [ 'Promotion only www.mashup-germany.com' ],
     encodedby: 'LAME in FL Studio 12',
     genre: [ 'Mashup' ],
     title: 'We found Arcando',
     year: 2018,
     picture: [ [Object] ],
     artists: [ 'Jaxx & Vega vs. David Puentez vs. Mashup-Germany' ] 
  } 
}

```

**Comment by Borewit** [comment]
#101 is not related to issue.

Can please drag and drop the mp3 file into this issue?

**Comment by kmathmann** [comment]
[05 - Jaxx & Vega vs. David Puentez vs. Mashup-Germany - We found Arcando.mp3](https://github.com/kmathmann/serve-files/raw/master/05%20-%20Jaxx%20%26%20Vega%20vs.%20David%20Puentez%20vs.%20Mashup-Germany%20-%20We%20found%20Arcando.mp3)

**Comment by Borewit** [comment]
I am not able to reproduce the issue Kevin. 

Unit test:
```TypeScript
describe("#103", () => {

    it("check duration / file", () => {

      const filePath = path.join(issue_path, "#103", "05 - Jaxx & Vega vs. David Puentez vs. Mashup-Germany - We found Arcando.mp3");

      return mm.parseFile(filePath, {duration: false, native: true}).then(metadata => {
        assert.approximately(metadata.format.duration, 4 * 60 + 18, 1.0 ); //258.01142857142855
      });
    });

    it("check duration / stream", () => {

      const filePath = path.join(issue_path, "#103", "05 - Jaxx & Vega vs. David Puentez vs. Mashup-Germany - We found Arcando.mp3");

      const stream = fs.createReadStream(filePath);

      return mm.parseStream(stream, 'audio/mpeg', {duration: false, native: true}).then(metadata => {
        assert.approximately(metadata.format.duration, 4 * 60 + 18, 1.0 ); //258.01142857142855
        printTags(metadata);
      });
    });

  });
```

``` 
------[format]------
{ lossless: false,
  dataformat: 'mp3',
  bitrate: 320000,
  sampleRate: 44100,
  numberOfChannels: 2,
  codecProfile: 'CBR',
  numberOfSamples: 11378304,
  duration: 258.01142857142855,
  encoder: 'LAME 3.99.5',
  tagTypes: [ 'ID3v2.3' ] }
------[common]------
{ track: { no: 5, of: null },
  disk: { no: null, of: null },
  album: '10YEARS',
  artist: 'Jaxx & Vega vs. David Puentez vs. Mashup-Germany',
  bpm: '130',
  comment: [ 'Promotion only www.mashup-germany.com' ],
  encodedby: 'LAME in FL Studio 12',
  genre: [ 'Mashup' ],
  title: 'We found Arcando',
  year: 2018,
  picture: 
   [ { format: 'image/jpeg',
       type: 'Cover (front)',
       description: '',
       data: <Buffer ff d8 ff db 00 84 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ... > } ],
  artists: [ 'Jaxx & Vega vs. David Puentez vs. Mashup-Germany' ] }
------[ID3v2.3]------
{ TALB: [ '10YEARS' ],
  TPE1: [ 'Jaxx & Vega vs. David Puentez vs. Mashup-Germany' ],
  TBPM: [ '130' ],
  COMM: 
   [ { language: 'eng',
       description: '',
       text: 'Promotion only www.mashup-germany.com' } ],
  TENC: [ 'LAME in FL Studio 12' ],
  TCON: [ 'Mashup' ],
  TIT2: [ 'We found Arcando' ],
  TRCK: [ '05' ],
  TYER: [ '2018' ],
  APIC: 
   [ { format: 'image/jpeg',
       type: 'Cover (front)',
       description: '',
       data: <Buffer ff d8 ff db 00 84 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 ... > } ] }
```

Are you sure you are using the latest version?

**Comment by kmathmann** [comment]
If i set duration to false it's working.

But why can i get the duration without duration to be true and why do i get a wrong duration if i set it to true?

> `duration`: default: `false`, if set to `true`, it will parse the whole media file if required to determine the duration.

**Comment by Borewit** [comment]
If the duration can be easily obtained (via the header or can be calculated based on the file size or number of frames) the duration flag has no impact.

But... if there is no easy way to calculate the duration, the parser will go through the whole file if and only if the duration flag is true and start to determine the duration based on the content.

Note the _if required_:
> `duration`: default: `false`, if set to `true`, it will parse the whole media file **if required** to determine the duration.

If I remember well this is only applicable for a VBR encoded MP3 lacking a LAME header which says what the duration is.

Reading a stream, without providing a file size (which is passed using fs.createReadStream as I used in my unit test) may impact how the duration of a CBR encoded file is calculated.

If you able to tell me how you managed to get the duration of ~86 sec, I am very much interested to look into that.

**Comment by Borewit** [comment]
I managed to reproduce your issue. The issue occurs only if the:

1. Read from a stream
2. The stream.fileSize is not set
3. option.duration=true (otherwise it would give up on the duration)

So the duration derived by by counting frames over the entire file is incorrect

**Comment by kmathmann** [comment]
Yes it's working now and the performance is gorgeous, 12 ms instead of up to 30 seconds.

Thank you 👍
