### ISSUE TITLE
Hope to support silk/slk format files

### ISSUE THREAD

**Issue by apprat** [Borewit/music-metadata#1050]
**Feature Request**
Hope to support silk/slk format audio files
[silk files.zip](https://github.com/Borewit/music-metadata/files/8190349/silk.files.zip)
silk format audio is very small and usually used in VoIP chat, I think it's widespread and should be supported

Ref:
- https://en.wikipedia.org/wiki/SILK
- https://github.com/ploverlake/silk
- https://www.vocal.com/speech-coders/silk/
- https://github.com/kn007/silk-v3-decoder
- https://datatracker.ietf.org/doc/html/rfc6716#section-4.2

**Comment by Borewit** [comment]
As SILK is more less only an audio codec, it there is no metadata. At most I can extract some very basic audio format information.

**Comment by apprat** [comment]
> As SILK is more less only an audio codec, it there is no metadata. At most I can extract some very basic audio format information.



I don't know much about the format structure of silk, I hope to get some basic information such as duration -.-

**Comment by Borewit** [comment]
This is not file a file oriented format. It's more like SILK stream dumped into a file and therefor probably not even a standardized file format. Therefor I don't expect any indicators telling what the duration is. The only way to find that out is decode the entire audio stream and measure the suration, and that is out of the scope of this module.

**Comment by Borewit** [comment]
To little added value, for to much complexity

**Comment by Borewit** [comment]
To little added value, for to much complexity

**Comment by Borewit** [comment]
To little added value, for to much complexity

**Comment by Borewit** [comment]
To little added value, for to much complexity
