### ISSUE TITLE
TypeError: buf.readUInt8 is not a function

### ISSUE THREAD

**Issue by dvantage** [Borewit/music-metadata#1066]
**Bug description**
For some tracks in mp3 format, the parseBlob() method may not work.
The problem manifests itself starting from version 7.12.1.

In commit 011cfb0a986db8266bc3e5545bcc885d61a200c3 Buffer has not been completely replaced by Uint8Array.

I'm afraid to break something, so I don't risk creating PR :slightly_smiling_face:

![image](https://user-images.githubusercontent.com/5517858/159884049-a27208de-6bea-48d2-a2d5-e85b7a90b9a3.png)

**Comment by Borewit** [comment]
> I'm afraid to break something, so I don't risk creating PR 🙂

Next time,. you should just try.
