### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by yultivert** [Borewit/music-metadata#109]
Hello.
I saw a similar issue to mine, but I can not really adapt my code for it to work.
I have a table containing all the paths of my music files (more than 5000):

`const files = ['music/track1.mp3', 'music/track2.flac', ...]`

How, from that, read the metadata of each music, by opening one at a time (or a better solution) ?

My current code is:

```
const parseMusic = f => new Promise((resolve, reject) => {
	mm.parseFile(f)
                .then(tags => resolve(tags))
                .catch(err => reject(err.message + ': ' + f))
})
const go = async () => {
	let requests = []
	for (let f of files) requests.push(parseMusic(f))
	try {
		let musics = await Promise.all(requests)
		// Do something with musics here
	} catch (err) {console.log(':`(', err)}
}
go()
```
Help me, please.
And thank you for this good parser.

**Comment by Borewit** [comment]
This is asynchronous programming. You tell music-metadata to parse, and you code continues. You don't want to parse all you files in parallel. Have a look to the [walk example](https://github.com/Borewit/music-metadata/blob/master/example/walk.js).

Another way of doing it is using a recursion. Create a list of file (kind of a ToDo list):

```JavaScript
function parseHugeFileList(files) {
  mm.parseFile(files.shift())
    .then(tags => {
      // do fantastic thing with the metadata
      parseHugeFileList(files) // process rest of the files AFTER we are finished
    });
}
```

The important part is that you iterate within the resolver routine (within the _then_).

Good luck yultivert!

**Comment by yultivert** [comment]
It's perfect with `parseHugeFileList(...)` !
Thank you Borewit ;)
