### ISSUE TITLE
Add an option to include/exclude embedded album art (images)

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#11]

**Comment by AoDev** [comment]
Thanks for moving the issue here. So, I don't have the knowledge required too know what can be done with audio file parsing. Does the request make sense to you? As far as memory / batch processing is concerned?

**Comment by Borewit** [comment]
@AoDev: It does make sense to me. 
I will be very busy the coming weeks, so it might has to wait a bit.

**Comment by Borewit** [comment]
Implemented; v0.7.1
