### ISSUE TITLE
Seemingly valid WAV file not being parsed for tags

### ISSUE THREAD

**Issue by ffxsam** [Borewit/music-metadata#1163]
**Bug description**
I've run across a WAV file that's completely valid (I can play it, edit it, etc), but its ID3 tags are not being read by music-metadata. I can even edit the tags in something like kid3 but music-metadata still won't see them.

The strange thing is, if I do this:
```bash
$ ffmpeg -y -i unreadable-tags.wav -c copy new.wav
```

Then I can edit the ID3 tags in kid3 and save it, and music-metadata will see those new tags.

**Expected behavior**
I would expect the ID3 tags to be read correctly.

**Audio file demonstrating the problem**
This is a customer's music track from an upcoming TV series so I can't share it here. Could you please provide me some secure way to send it to you?

**Comment by ffxsam** [comment]
BTW, we are now a sponsor. 🎉 music-metadata is a huge help to our service, so thank you!

<img width="663" alt="CleanShot 2022-06-29 at 12 51 39@2x" src="https://user-images.githubusercontent.com/12532733/176503290-47e75544-8233-435d-92e4-0a68a73c4754.png">

**Comment by Borewit** [comment]
Thank you so much for your sponsorship @ffxsam! I hope you received my e-mail, otherwise let me know.

**Comment by Borewit** [comment]
Solved in [v7.12.4](https://github.com/Borewit/music-metadata/releases/tag/v7.12.4)
