### ISSUE TITLE
Document the native option

### ISSUE THREAD

**Issue by bcomnes** [Borewit/music-metadata#12]
What does the native option do?

**Comment by depuits** [comment]
in the code I found this
```
/**
 * Parse audio stream
 * @param stream
 * @param opts
 *   .filesize=true  Return filesize
 *   .native=true    Will return original header in result
 * @param callback
 * @returns {*|EventEmitter}
 */
```

So when native is set to true it will return the original header in result. Not sure what that exactly means though.

**Comment by bcomnes** [comment]
Oh hrmmm... Sounds like I'll have to read the code to figure it out.  Feel free to close or keep open.

**Comment by Borewit** [comment]
Added a description to the README.

**Comment by bcomnes** [comment]
Sweet.  Digging the updates!

Any recommendations on metadata editing?

**Comment by Borewit** [comment]
Nice to get some response :smile:.

I use [MusicBrainz Picard](https://picard.musicbrainz.org/) to get and set meta-data. Make sure you selected picked the right release, before you let Picard update your audio files.

[MP3TAG](http://www.mp3tag.de/en/) is also pretty sophisticated.

For playing, converting and renaming files I use [foobar2000](http://www.foobar2000.org/).

**Comment by bcomnes** [comment]
I was looking more along the lines of node modules. But ty for the links!  Will check these out.

**Comment by Borewit** [comment]
In the future maybe this module #10....

I have no experience writing tags using NPM module yet.
