### ISSUE TITLE
Failing to read metadata from m4b, throwing "FourCC contains invalid characters"

### ISSUE THREAD

**Issue by teken** [Borewit/music-metadata#120]
**Bug description**
I try to read the audio file like any other but for this one and this one along it throws the error:
![error](https://user-images.githubusercontent.com/1248314/42890589-2289ab52-8aa5-11e8-8b20-8b2f56995629.png)

**Expected behaviour**
To read the metadata even if a field is bad, just without the bad field

**Audio file demonstrating the problem**
Unable to provide as its copyrighted material

**Comment by Borewit** [comment]
I tried to send you an e-mail...
If that fails, you can drop the file here, I will do my best to remove it as soon as I got it.

**Comment by teken** [comment]
Sorry but the file is an audiobook measuring at ~1.2GB, if you contact me privately I could see about some remote desktop control or something along that lines

**Comment by Borewit** [comment]
Can you contact me via: https://discord.gg/aWUUVQ?

**Comment by Borewit** [comment]
Issue is caused parsing a [mdhd Atom](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-SW34). Size was expected to be 32, which is the length of total number of fields.

Media Header Atom | Size [bytes] | Value
-- | -- | --
Atom Size | 4 | 44
Type = ‘mdhd’ | 4 |  
Version | 1 |  
Flags | 3 |  
Creation time | 4 |  
Modification time | 4 |  
Time scale | 4 |  
Duration | 4 |  
Language | 2 |  
Quality | 2 |  
**Sum:** | **32** |  

The actual atom size, was specified to be 44. This value was ignored causing the next value to read at the wrong offset, giving the invalid four-cc identifier.

Probably worth capturing it as a quality warning in the future #60.

**Comment by Borewit** [comment]
Fixed in version [v2.4.2](https://github.com/Borewit/music-metadata/releases/tag/v2.4.2)

**Comment by Borewit** [comment]
Another issue related to parsing MPEG-4 Audio-books: #127
