### ISSUE TITLE
AIFC files are always considered as compressed

### ISSUE THREAD

**Issue by johannesgiani** [Borewit/music-metadata#1211]
**Bug description**
Parsing some AIFC file with no compression throws: Illegal pstring length, likely because aifc files are always considered as compressed.

**Expected behavior**
Parsing uncompressed AIFC files should work.

**Audio file demonstrating the problem**
[loop-broken.aif.zip](https://github.com/Borewit/music-metadata/files/9249304/loop-broken.aif.zip)

soxi output:
```
Input File     : 'loop-broken.aif' (aifc)
Channels       : 2
Sample Rate    : 44100
Precision      : 25-bit
Duration       : 00:00:05.96 = 262904 samples = 447.116 CDDA sectors
File Size      : 2.10M
Bit Rate       : 2.82M
Sample Encoding: 32-bit Floating Point PCM
```

**Comment by Borewit** [comment]
Are you able to provide me a smaller audio sample?
That would help a lot to reduce the load / time of the continues integration tests.

**Comment by johannesgiani** [comment]
Sure, here you go:
[hit-broken.aif.zip](https://github.com/Borewit/music-metadata/files/9252423/hit-broken.aif.zip)

**Comment by johannesgiani** [comment]
❤️
