### ISSUE TITLE
(8.0.0) No .d.ts files from npm install

### ISSUE THREAD

**Issue by PapiOphidian** [Borewit/music-metadata#1216]
**Bug description**
An install of 8.0.0 does not include .d.ts files causing TypeScript builds to fail

**Expected behavior**
They should be included

**Audio file demonstrating the problem**
N.A.

**Comment by PapiOphidian** [comment]
I managed to fix this locally by adding `"declaration": true` in the compilerOptions of the tsconfig

**Comment by Borewit** [comment]
Thanks for making me aware @PapiOphidian!

**Comment by Borewit** [comment]
Fixed in [v8.0.1](https://github.com/Borewit/music-metadata/releases/tag/v8.0.1)
