### ISSUE TITLE
No `format.duration` for aac files

### ISSUE THREAD

**Issue by danieljamesross** [Borewit/music-metadata#1281]
No `format.duration` parameter is returned after passing `.aac` files. I have tried using [AudioTagAnalyzer](https://audio-tag-analyzer.netlify.app/) and get the same response (see image, below).

<img width="1203" alt="Screenshot 2022-09-08 at 14 18 53" src="https://user-images.githubusercontent.com/28922296/189132717-b7595f79-5c13-4db8-835b-aaaa52162497.png">

**Comment by Borewit** [comment]
Depending on the content of the AAC there may be no duration defined. [music-metadata](https://github.com/Borewit/music-metadata) has no audio decoders embedded. So if comes to that to be able to determine the duration, you won't get it.

If you have reason to believe the duration could be extract without decoding the full audio stream, please provide more details and a sample file.
