### ISSUE TITLE
Duration is different across platforms

### ISSUE THREAD

**Issue by hoangmf** [Borewit/music-metadata#1296]
Dear all, 

I have found duration in several platforms may have different estimates.

I know that estimating Duration is not easy. Can you help me answer this?

This is my mp3 file, When I use music-metadata it will have 372.19 seconds. And when I use FFMPEG it takes 371,87 seconds.

Do we have a way to sync or which one is correct?

My code example

`file.metadata = await mm.parseBlob(event.target.files[0]);`

<img width="555" alt="image" src="https://user-images.githubusercontent.com/66987100/191171541-59816013-ef8f-43c2-9c19-8a593fac4ef1.png">
![image](https://user-images.githubusercontent.com/66987100/191171583-ceeccb04-9b79-41fc-8a52-7ab293097a0b.png)

![image](https://user-images.githubusercontent.com/66987100/191171600-a944e460-f426-4cbf-b07c-f35029d8194f.png)

This file is an example 

https://wedding.microvn.net/assets/example.mp3

**Comment by Borewit** [comment]
There many different audio formats, and metadata tags, which also may have differences in utilizing different metadata and other header. MP3 specifically is a lot of variations and is no consistent way to set the duration.

In principal, music-metadata uses the easiest, fastest way to extract the duration. Not necessary the most accurate. Decoding the audio stream, and measuring that is probably the most accurate, which is outside the scope of this module. It's reading metadata, if the artist says Elvis, and song is in reality from Madonna, there is nothing I can do. Same with the duration.

However, in some cases, like CBR (constant-bit-rate), and if there no duration in header data available, a simple calculation over the content is done. Is this calculation correct. I may be off a bit, to be honest I am not entirely sure.

But it is open source code, feel free to suggest code which demonstrates better values.
Plenty of test cases which you could fine tune, or add if you think that is required.

**Comment by hoangmf** [comment]
Thanks for your information
