### ISSUE TITLE
Picture Format

### ISSUE THREAD

**Issue by IrosTheBeggar** [Borewit/music-metadata#132]
**Bug description**
I updated mStream to use the latest version of this library, and the picture object has changed causing some problems.  The format value is now returning 'image/jpeg' instead of just 'jpg'.  Is it possible to add the file extension to the object as well?

**Comment by Borewit** [comment]
Hey Paul. 

Good to hear your are updating, correct I changed the API (#96). 
I thought the MIME-types was a better way to express the content type.

What about using the [mime-types](https://www.npmjs.com/package/mime-types)?

```
mime.extension('image/jpeg') // 'jpg'
```

Or [media-typer](https://www.npmjs.com/package/media-typer) to extract the type part ('jpeg') from the MIME type, but which is not the same as the extensions.

**Comment by IrosTheBeggar** [comment]
I got it working with mime-types.  I was just wanted to avoid adding more dependencies if possible.

**Comment by Borewit** [comment]
I will think about adding the extension as well.
