### ISSUE TITLE
nodeError The value "-7" is invalid for option "size"

### ISSUE THREAD

**Issue by MostafaIOS** [Borewit/music-metadata#133]
**Bug description**
hi
I'm using this library for export music metadata that uploaded from iOS application.music format is m4a and when i upload music file I received this error and it can't export music metadata.

please help me to solve this issue

** Error **
nodeError The value "-7" is invalid for option "size"

**Comment by Borewit** [comment]
I will try to help, but I need the file causing trouble Mostafa.

**Comment by MostafaIOS** [comment]
this is m4a file :
[1534662183711.m4a.zip](https://github.com/Borewit/music-metadata/files/2301024/1534662183711.m4a.zip)

**Comment by Borewit** [comment]
Your file contains an 'mdat' [atom using the extended size field](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap1/qtff1.html#//apple_ref/doc/uid/TP40000939-CH203-38190).

Although it should not use the extended size field (should only be used if the size does not fit in a 32-bit unsigned integer), it should be parsable.

The extended size field is currently not supported in music-metadata, which I consider to be a bug.

**Comment by Borewit** [comment]
Fixed in [v2.6.1](https://github.com/Borewit/music-metadata/releases/tag/v2.6.1).
