### ISSUE TITLE
Synchronous metadata return

### ISSUE THREAD

**Issue by teken** [Borewit/music-metadata#134]
Same functionality but a synchronous method. would make scanning batches of files much easier

**Comment by Borewit** [comment]
Makes sense Duncan.

Note that a library like [walk](https://www.npmjs.com/package/walk) also helps with synchronous file traversal.

Related: #109, #26

**Comment by Borewit** [comment]
I don't see an easy way to add that.
I think [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) makes dealing with promises a lot easier.
