### ISSUE TITLE
How to add lyrics?

### ISSUE THREAD

**Issue by kyawswarthwin** [Borewit/music-metadata#138]
I found lyrics in id3v2-lyrics.mp3. I wan't to know how to add? Which software support?
MusicBrainz Picard lyrics not work and TagScanner lyrics not work too.

**Comment by kyawswarthwin** [comment]
MusicBee lyrics work.

**Comment by kyawswarthwin** [comment]
synchronized lyrics missing time

**Comment by Borewit** [comment]
No response from user.
