### ISSUE TITLE
mpeg parsing fails for irrelevant attributes

### ISSUE THREAD

**Issue by depuits** [Borewit/music-metadata#14]
I have some files in which the parsing fails on:

> Invalid MPEG Audio version

or

>expected frame header but was not found

I've "fixed" both errors by disabling them in the code (file: mpeg.js):
```
if (this.version === null) {
    this.version = 1;
    //throw new Error('Invalid MPEG Audio version');
}
```
```
if (this.frameCount > 0) {
    //return this.done(new Error('expected frame header but was not found'));
}
```
While this is definitely not a real fix, I am now able to read the song title and artist successfully which is all I currently need.

**Comment by Borewit** [comment]
Can you provide me with a sample of such a failing MP3 file?

**Comment by depuits** [comment]
'04 - You Don't Know.mp3' is one with the 'expected frame header but was not found' error and '07 - I'm Cool.mp3' is one with 'Invalid MPEG Audio version'

[songs.zip](https://github.com/Borewit/music-metadata/files/1088895/songs.zip)

**Comment by Borewit** [comment]
Thanks providing this test data. It looks like both of these files contain some odd content (corrupt data). Nevertheless, they are passing as unit tests now.
