### ISSUE TITLE
Expose the "lib" folder to consumers

### ISSUE THREAD

**Issue by binyamin** [Borewit/music-metadata#1424]
### Scenario
The current `package.json` limits access to a single file, via a conditional export. This entry-point is the only file that consumers may import.
https://github.com/Borewit/music-metadata/blob/72a40061a1ba2d85336cbd8d756fec25b9a23e72/package.json#L14-L19

Personally, I was trying to import `./lib/ParserFactory.js`, so I could check whether a given format is supported.

### Solutions
1. Use [subpath patterns](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#subpath-patterns) to export the entire lib folder. Compatible with Node.js v14.13.0 & v12.20.0, and greater. I think that with v16.x you can specify extensions. I testing this method locally with v14.20.0
```jsonc
{
  "exports": {
    ".": { 
      "node": "./lib/index.js", 
      "default": "./lib/core.js" 
    },
    "./lib/*": "./lib/*",
    // you can restrict access to subfolders
    "./lib/internal/*": null
  }
}
```
2. Keep using a single entry-point, and expose various functions, classes, etc., via that file
3. Add an "exports" field for specific files, instead of exposing the entire folder.

**Comment by binyamin** [comment]
@Borewit The "exports" field appears to be a Node.js thing, not an "ESM" thing. I'm using Deno, which _only_ uses ESM, and that's not required at all.

**Comment by binyamin** [comment]
But that's a good idea. I can work on a PR.

**Comment by binyamin** [comment]
@Borewit I'm a bit conflicted on this. It may be smarter for users to catch the error when a file cannot be parsed. This would require a custom error class for the parser, which would be useful to have in general.

Otherwise, here's the basic code I would add. I assume it would go in `lib/core.ts`, and `lib/index.ts` would re-export it.
```ts
/**
 * Determines whether the {@link filepath} is supported for parsing.
 * @param filepath Path, filename or extension of a file.
 */
export function isFileSupported(filepath: string) {
    return Boolean(ParserFactory.getParserIdForExtension(filepath));
}
```

**Comment by Borewit** [comment]
It is already close to do something like that:

https://github.com/Borewit/music-metadata/blob/7cdebd1ca61411f3bb8bf7ae1d69a916ff317222/lib/ParserFactory.ts#L100

&

https://github.com/Borewit/music-metadata/blob/7cdebd1ca61411f3bb8bf7ae1d69a916ff317222/lib/ParserFactory.ts#L105

If we would throw an error with a good described error code, would that provide you the feedback you are looking for?

What is the objective?

**Comment by binyamin** [comment]
the object is to throw a subclass of `Error`, instead of a generic `Error` class, so I can use `instanceof` to identify the code that threw the error.

```ts
class ParserError extends Error { /* ... */ }

async function parse() {
    throw new ParserError("...");
}

try {
    await parse();
} catch (error) {
    if (error instanceof ParserError) {
        // This must be from music-metadata
    } else {
        throw error;
    }
}

**Comment by binyamin** [comment]
@Borewit What do you think about using a custom error class?

**Comment by Borewit** [comment]
Sorry for this very late reply, custom error class sounds good to me.
