### ISSUE TITLE
'/node_modules/.vite/deps/music-metadata.js?v=1aab4cae' does not provide an export named 'parseFile'

### ISSUE THREAD

**Issue by LeviticusMaximus** [Borewit/music-metadata#1425]
I'm trying to use this to parse my audio file uploads in Vue3/Vite

and I'm banging my head against a wall with this error: 

> '/node_modules/.vite/deps/music-metadata.js?v=1aab4cae' does not provide an export named 'parseFile'

my setup is as specified:
`import { parseFile } from "music-metadata";`

although I can see in the index.js that there's an export:

`export async function parseFile(filePath, options = {}) { ... }`

So I'm kinda stuck, any ideas?

Thanks

**Comment by Borewit** [comment]
I am not familiar with Vue3/Vite, but `parseFile` should not be available on the browser side, only on the server / Node.js side. If you are looking for a method to parse a [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) you should check [music-metadata-browser `parseBlob` function](https://github.com/Borewit/music-metadata-browser#parseblob-function).

I have not migrated this function to this ESM module yet.

**Comment by staniel359** [comment]
@Borewit Somehow `parseFile` function is not exported after Vite optimization.
Other functions seem to be imported.
Same with `music-metadata-browser` package.

But when I install `music-metadata-browser` and do:

`
import { parseFile } from  'music-metadata'
`

then `parseFile` is imported.

Do you know why it can happen?

**Comment by Borewit** [comment]
> But when I install `music-metadata-browser` and do:
> 
> `import { parseFile } from 'music-metadata'`
> 
> then `parseFile` is imported.
> 
> Do you know why it can happen?

My best guess is that the Vite optimization is using an aggressive form of [tree shaking](https://webpack.js.org/guides/tree-shaking/). 

For that reason:

```js
// Now the optimizer understand we only need `parseFile`, the rest will eliminated
import { parseFile } from 'music-metadata'; out

parseFile();
```

is better then:

```js
import * as mm from 'music-metadata`; 

mm.parseFile();
```
despite my code example.

**Comment by staniel359** [comment]
@Borewit What I meant was:
```
yarn add music-metadata
import { parseFile } from 'music-metadata'
[fails]

yarn add music-metadata-browser
import { parseFile } from 'music-metadata-browser'
[fails]

yarn add music-metadata-browser
import { parseFile } from 'music-metadata'
[imported]
```

**Comment by Borewit** [comment]
That's very weird.
I have no idea, maybe some dependency.

Is Vue3/Vite not client (browser) side framework?

**Comment by staniel359** [comment]
@Borewit Both are client-side tools.
Vue is framework and Vite is bundler, running on Rollup.

Right now I'm using vue-cli (Vue 3 + Webpack) and `import { parseFile } from 'music-metadata'` works fine.
But on Vite it's not working.

Is there any chance that `parseFile` could not be exported somehow?
Does it have special logic that Vite (Rollup) can't handle or ignores?

**Comment by Borewit** [comment]
What I don't understand is how `parseFile()` could possibly work on the client side, as you lack file system access.

`parseFile()` is designed in ESM to be only available in Node.js:

https://github.com/Borewit/music-metadata/blob/72a40061a1ba2d85336cbd8d756fec25b9a23e72/package.json#L16

where non node engines import:
https://github.com/Borewit/music-metadata/blob/72a40061a1ba2d85336cbd8d756fec25b9a23e72/package.json#L17

which does not have the `parseFile()`. 

I am not sure of this statement is correct, but also see also [binyamin's comment](https://github.com/Borewit/music-metadata/issues/1424#issuecomment-1336280440), who says that this export is a Node specific thing.

**Comment by staniel359** [comment]
@Borewit Now I see, thank you.

@LeviticusMaximus I'm using `music-metadata` with Electron, so I solved this one with [vite-plugin-electron-renderer](https://www.npmjs.com/package/vite-plugin-electron-renderer):
``` js
plugins:
  renderer({
    optimizeDeps: {
      include: [
        'music-metadata'
      ]
    }
  })
]
```
On vue-cli it was:
``` js
configureWebpack: {
  target: 'electron-renderer'
}
```
So I guess you need to set some config to tell your app to run Node packages on client side.

**Comment by Borewit** [comment]
I recommend in to use music-metadata in the main process, as it designed on Node.js.

There are many Electron application having succes with that, yet as far as I know only with the CJS version.

**Comment by staniel359** [comment]
@Borewit Okay, thank you.

**Comment by LeviticusMaximus** [comment]
thanks for the input guys, will check it out and get back if I'm still having issues.
