### ISSUE TITLE
Could not get duration from webm audio files

### ISSUE THREAD

**Issue by AlisonGou** [Borewit/music-metadata#1463]
**Bug description**
We are using music-metadata to get metadata(mainly for duration) from webm audio files using nodejs, but it does not work. This is reproducible very easily.

Tried to get metadata using the sample file from https://audio-tag-analyzer.netlify.app. Here is the result.
<img width="860" alt="Screen Shot 2022-12-30 at 11 36 15 AM" src="https://user-images.githubusercontent.com/18065870/210032002-1f0d5b1e-c469-43e6-8352-e352ad78a43b.png">

**Expected behavior**
Duration(metadata) can get from webm audio files

**Audio file demonstrating the problem**
If applicable, please drag and drop the __zipped__ audio file(s) which caused the problem into the bug report.
**Test audio files:** [RecordRTC-20221130-music.webm](https://user-images.githubusercontent.com/18065870/210030444-764fdc1c-bfb0-493d-bd09-8db294b52a9f.webm)

**Comment by Borewit** [comment]
In my  opinion the bug is that the duration returns `NaN`, but it should be `undefined`, as there is no duration set in the metadata. The audio may have a duration, yet decoding the audio in order to extract the duration is beyond the scope of this module.
