### ISSUE TITLE
no duration and bitrate in m4a file

### ISSUE THREAD

**Issue by subframe7536** [Borewit/music-metadata#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

7.13.1 & 8.1.1

### JavaScript module eco system

CommonJS modules (CJS), music-medata ≥ version 8

### Current Behavior

as titled, no duration and bitrate in the sample m4a file

```
parseFile('test.m4a').then(meta => {
  console.log(meta.format)
})

{
  tagTypes: [ 'iTunes' ],
  trackInfo: [ { codecName: 'MPEG-4/AAC', type: 2, audio: [Object] } ],
  container: 'iso5/avc1/dsms/msix/dash',
  creationTime: 1904-01-01T00:00:00.000Z,
  modificationTime: 1904-01-01T00:00:00.000Z,
  codec: 'MPEG-4/AAC',
  duration: 0,
  sampleRate: 44100,
  bitsPerSample: 16,
  numberOfChannels: 2,
  lossless: false
}
```
[issue file.zip](https://github.com/Borewit/music-metadata/files/10367959/issue.file.zip)

### Expected Behavior

bitrate: 403000
duration: 189.08

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Konglomneshued** [comment]
I have the same issue.  I think it's related to AAC files and not m4a, because it can grab metadata from my ALAC m4a files.  

I have a .aac file not contained in m4a and it fails to grab the duration and such.

**Comment by Borewit** [comment]
Sorry for the late reply.

music-metadata does return a duration of 0.
The duration of 0 is defined in the audio file, in the following atoms:
- movie header (mvhd) atom
- track header (tkhd) atom

music-metadata is not able to calculate the duration of actual the audio-stream.

MP4 / M4A is complex format, it can certainly be that I missed something. If you believe it can be derived from the metadata, please tell me which atom you believe the duration is stored. 

music-metadata cannot guarantee to be able to determine the duration. But in proper encoded audio files, with metadata defined as it should be, in my experience it always does.
