### ISSUE TITLE
Bit Rate for WAV files have me confused

### ISSUE THREAD

**Issue by avwie** [Borewit/music-metadata#1479]
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

I am checking a 2-channel, 16-bit, 44,1kHZ WAV file and get this as response:

```
{
  "tagTypes": [
    "exif",
    "ID3v2.3"
  ],
  "trackInfo": [],
  "container": "WAVE",
  "codec": "PCM",
  "bitsPerSample": 16,
  "sampleRate": 44100,
  "numberOfChannels": 2,
  "bitrate": 352800,
  "lossless": true,
  "numberOfSamples": 137095,
  "duration": 3.108730158730159
}
```

The bitrate has me confused. I was expecting 1411200.
This answer is consistent for multiple WAV files.

What am I missing here?

Looking at the source-code it seems to be calculated by `blockAlign * 8 * sampleRate`, which would imply a block-align or 1. However, for a stereo 16-bit file this block-align should be 4.

**Comment by Borewit** [comment]
Superseded by issue #1480
