### ISSUE TITLE
Bitrate calculation for WAV files is wrong

### ISSUE THREAD

**Issue by avwie** [Borewit/music-metadata#1480]
**Issue**

The `bitrate` for any 2 channel, 16-bit, wave file will result in a bitrate of 352600, which is wrong. It should be 44100 * 16 * 2 = 1411200.

Looking at there is an issue:
https://github.com/Borewit/music-metadata/blob/773b406b6398546a76d36ab3038b6526b2977ac8/lib/wav/WaveParser.ts#L122

The calculation is wrong and should be similar to:
https://github.com/Borewit/music-metadata/blob/773b406b6398546a76d36ab3038b6526b2977ac8/lib/wav/WaveParser.ts#L91

**Comment by Borewit** [comment]
Good catch @avwie !
