### ISSUE TITLE
NPM release：remove sourceMappingURL

### ISSUE THREAD

**Issue by juntaosun** [Borewit/music-metadata#1509]
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

Unable to read /node_modules/.store/music-metadata@8.1.3/node_modules/music-metadata/lib/matroska/types.js Source map: ENOENT: no such file or directory, open '\node_modules\.store\music-metadata@8.1.3\node_modules\music-metadata\lib\matroska \types.js.map'

//# sourceMappingURL=types.js.map

"npm  install music-metadata"
After installation, there is a description of sourceMappingURL at the end of the file in the lib directory. 
I hope to remove it when the version is released.
path:
. /node_modules/.store/music-metadata@8.1.3/node_modules/music-metadata/lib/**
remove all //# sourceMappingURL=**

NPM release （next time），
tsconfig.json add ：
`"sourceMap": false,`

thanks！

**Comment by Borewit** [comment]
Was resolved in b51a833c1f06f253eb0d39580098058e7361fc71, #729
