### ISSUE TITLE
Possible Copyright infringment

### ISSUE THREAD

**Issue by aadsm** [Borewit/music-metadata#153]
Hey,

I want to raise a concern about the copyright of this library since it’s a derivative work of aadsm/node-id3 through this fork link: `Borewit/music-metadata` -> `leetreveil/musicmetadata` -> `aadsm/node-id3`.
You probably haven’t realized this (because as far as I can see this was changed at leetreveil/musicmetadata) but the original work is under a [BSD licence](https://github.com/aadsm/node-id3/blob/master/LICENSE.md) and copyrighted by me and Opera Software ASA (https://opera.com). 

As it is now, this software is presented with a different license and is missing the BSD once which is required for derivative works (it’s also missing the original copyrighters which this work is a derivative of).

**Comment by Borewit** [comment]
Hi António,

I have not tempered your license António, so I don't think you should address me.

As far as I can see neither BSD, neither Opera Software, neither you have any copyright on music-metadata.

Neither I see your name in the list of [contributors](https://github.com/Borewit/music-metadata/graphs/contributors).

I noticed that on the original project you are referring to, [you only added some licensing and credits](https://github.com/aadsm/node-id3/graphs/contributors). I am a bit confused, what is your mission here? It doesn't feel like _promote and protect open source software, projects and communities_ to me.

**Comment by aadsm** [comment]
Yeah, those are good questions, let me provide more context around `aadsm/node-id3`.

In 2010 Tim Smart downloaded my `JavaScript-ID3-Reader` project, renamed some variables in it and re-upload it to github under the `node-id3` name. I pointed this out to him and he eventually deleted his project (only my fork of his project remains, the one this is based on). I kept a [copy of the issue](https://github.com/aadsm/node-id3/issues/3) I filed at the time for historical purposes.

This is the reason why you don’t see my name in the list of contributors, you see Tim’s name because he uploaded all my code to github. The [commits he made](https://github.com/Borewit/music-metadata/commits?author=tim-smart) are the code I wrote. I added the licensing and credits to the project to provide the legal information that was missing.

The reason I created this issue in this project is because I noticed you’ve put a lot of work into it and are still activly maintaining it. You’ve addressed and closed all the >100 issues that have been opened and that’s quite impressive. For me, this means you care a lot about this project.

I know that you have not tempered with the license and my guess was that you had no idea about the copyright implications of this derived work until now. Since you seem to care a lot about this project I thought it would be the right thing to do to raise this concern so you could be aware (sooner than later) and address it. (If I had a similar issue I’d hope someone would point it out to me as well).

**Comment by Borewit** [comment]
I don't want to impose any restrictions on those who are using and continue my work. I hope credits are maintained, but I am not planning to enforce that with legal means at the cost flexibiliy.

I don't see any issue António:
1. I have not derived work with the copyright holders you are refering to
2. The repositiory I cloned from (@leetreveil) neither, you have [added the license](https://github.com/aadsm/node-id3/commit/59cc6fe72b28d31d2aae1be50da03b533cb33ff0) after @leetreveil & contributors worked for 3 years on that repo ([initial commit](https://github.com/leetreveil/musicmetadata/commit/fa20251fce1ef27fb80319125d011b3529482bf8)).
3. [Original code](https://github.com/aadsm/node-id3/commit/d4b3d341146b5b5a8023da2ea4bb3951571eedfe) you are refering to is no longer present is music-metadata.

If there is something I can do for you, please let me know.

**Comment by aadsm** [comment]
I also have no desire to impose any restrictions on the people using your project (I think you did an amazing job here). I just wanted to let you know about this possible issue.

I’d like to clarify your second point though, regarding the time the license file was added to the project. Under copyright law it doesn’t matter if or when a copyright notice is added to a piece of work. Your work is copyright protected as soon as you create it and can prove it is yours. The license (or notice) is just there for information purposes only, it is not the thing that grants copyright protection.

**Comment by Borewit** [comment]
Thanks António, and as I said before, I don't seen an issue.
But if you are worried, maybe you can declare that [musicmetadata](https://github.com/leetreveil/musicmetadata) should not be considered to be a copy of your work, and if one does for whatever reason, that you fully accept the copyright license Lee Treveil assigned to it including the freedom to copy it as described in that license.

**Comment by Borewit** [comment]
I am closing this issue António, if you want to have a chat one-on-one just let me know.
If you want to team up as an independent developer you are more then welcome.
