### ISSUE TITLE
The requested module does not provide an export named 'parseFile'

### ISSUE THREAD

**Issue by Konglomneshued** [Borewit/music-metadata#1551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

^8.1.3

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

Only thing I did was install and try to use it.

Using in my code
```
import { parseFile } from 'music-metadata';
import { v4 as newUUID } from 'uuid';

import type { File } from 'types/fileTypes';
import type { Song } from '../types';

export const readSongs = (files: File[], extractSong: (song: Song) => void) => {
   files.map(async ({ path, name }) => {
      parseFile(path)
         .then(metadata => {
            console.log(metadata);
         })
         .catch(error => console.error(error.message));
   });
};
```

![image](https://user-images.githubusercontent.com/94726665/221443737-045fa73d-6481-47a3-a2e9-639cdefcdef3.png)
![image](https://user-images.githubusercontent.com/94726665/221444006-c2cfee25-304f-478b-bcba-b90268c560b9.png)

My IDE not showing any errors
![image](https://user-images.githubusercontent.com/94726665/221444034-98654d12-dce4-4ac6-b89f-1e6430054ae1.png)

### Expected Behavior

Import parseFile as shown in the usage section.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Similar to issue #1357, #1259.

Using Electron, try to use parseFile() from the _main process_, and not the _renderer process_.
Maybe Electron does not support ESM modules yet, therefor switch back to music-metadata version 7.
