### ISSUE TITLE
Can not parse m4a on server

### ISSUE THREAD

**Issue by FranzSkuffka** [Borewit/music-metadata#156]
Follow up on #78 

Not working
https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a

working
https://tunalib.s3.eu-central-1.amazonaws.com/cool.mp3 works.

**Bug description**
Can not parse m4a on server

**Expected behavior**
Metadata is extracted as by the audio-tag-analyzer.

**Code samples demonstrating the problem**

Code samples demonstrating the problem
```
❯ node --version
v8.12.0
```
using `isomorphic-fetch`

`parseStream` example
```js
  fetch(loc)
    .then(res => mm.parseStream(res.body))
    .then(tags => {
        console.log(tags)
        respond(JSON.stringify(tags || 'tagged'))
    })
```

`parseFile` example
```js
  fetch(loc)
    .then(res => {
        fs.writeFileSync(TEMP, res.body)
        mm.parseFile(TEMP).then( tags=> {
          console.log(tags)
          respond(JSON.stringify(tags || 'tagged'))
        })
    })
```
output for both samples
```
[1] https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a
[1] { format: { tagTypes: [], dataformat: 'MPEG-4' },
[1]   native: undefined,
[1]   common: { track: { no: null, of: null }, disk: { no: null, of: null } } }


[1] https://tunalib.s3.eu-central-1.amazonaws.com/cool.mp3
[1] { format: 
[1]    { tagTypes: [ 'ID3v2.2' ],
[1]      lossless: false,
[1]      dataformat: 'mp3',
[1]      bitrate: 320000,
[1]      sampleRate: 48000,
[1]      numberOfChannels: 2,
[1]      codecProfile: 'CBR',
[1]      encoder: 'Lavc58.18',
[1]      duration: 175.536 },
[1]   native: undefined,
[1]   common: 
[1]    { track: { no: null, of: null },
[1]      disk: { no: null, of: null },
[1]      encodersettings: 'Lavf58.12.100',
[1]      title: 'Ok Cool (prod. Stickle)',
[1]      artists: [ 'Yung Hurn' ],
[1]      artist: 'Yung Hurn' } }

```

**Comment by Borewit** [comment]
I did not have the time to really look into it, but I think you need to use [parseReadableStream, part of module music-metadata-browser](https://github.com/Borewit/music-metadata-browser#parsereadablestream-function), instead.

[Response.body](https://developer.mozilla.org/en-US/docs/Web/API/Response) is a [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) which is not the same as a Node [stream.Readable](
https://nodejs.org/api/stream.html).

**Comment by Borewit** [comment]
I was to quick with my conclusion, I have been able to to reproduce your issue. The m4a resolves with no metadata in a streaming context. I have used [needle](https://www.npmjs.com/package/needle) instead stream the audio track from the URL.

```JavaScript
import * as mm from 'music-metadata';
import * as needle from 'needle';

describe('Issue #156', () => {

  describe('Fetch URL using needle', () => {


    it('Parse: cool.mp3', () => {

      const url = 'https://tunalib.s3.eu-central-1.amazonaws.com/cool.mp3';

      const stream = needle.get(url);
      return mm.parseStream(stream, stream.type, {duration: true}).then(metadata => {
        assert.strictEqual(metadata.common.title, 'Ok Cool (prod. Stickle)');
        assert.strictEqual(metadata.common.artist, 'Yung Hurn');
      });
    });

    it('Parse:  plan.m4a', () => {

      const filePath = path.join(issue_path, '#156', 'plan.m4a');

      return mm.parseFile(filePath, {duration: true}).then(metadata => {
        assert.strictEqual(metadata.common.title, 'We Made a Plan');
        assert.strictEqual(metadata.common.artist, 'Adan Cruz');
        assert.strictEqual(metadata.common.album, 'Quiérelo');
      });
    });

    it('Parse:  plan.m4a', () => {

      const url = 'https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a';

      const stream = needle.get(url);
      return mm.parseStream(stream, stream.type, {duration: true}).then(metadata => {
        assert.strictEqual(metadata.common.title, 'We Made a Plan'); // <= Fails here
        assert.strictEqual(metadata.common.artist, 'Adan Cruz');
        assert.strictEqual(metadata.common.album, 'Quiérelo');
      });
    });
  });
});

```

**Comment by Borewit** [comment]
Okay, I found the cause. The reason the MPEG-4 (.m4a) fails is due to the fact the file-size is unknown to the parser. MPEG-4 is build from atoms. If you pass the content-size to the parser it will work just fine:

```JavaScript
import * as mm from 'music-metadata';
import * as fetch from 'isomorphic-fetch';

 it('Parse: plan.m4a using fetch', () => {

      const url = 'https://tunalib.s3.eu-central-1.amazonaws.com/plan.m4a';

      return fetch(url)
        .then(res => mm.parseStream(res.body, res.headers.get('Content-Type'), {
          fileSize: res.headers.get('Content-Length') // This one makes the difference
        }))
        .then(tags => {
          assert.strictEqual(tags.common.title, 'We Made a Plan');
          assert.strictEqual(tags.common.artist, 'Adan Cruz');
          assert.strictEqual(tags.common.album, 'Quiérelo');
        });
    });
```

I did not succeed to get it to work with needle, because I only succeed to get access to the headers after the point I had to start reading from the stream. (Question asked: tomas/needle#265).

I will create a fix so it will work as well without the fileSize. This will however register a warning in the future (#60).

Note that `'Content-Type` absolutely wrong, however music-metadata has a fallback for unknown content-types to auto detect the audio type based on the content.

**Comment by Borewit** [comment]
I had to switch to [axios](https://github.com/axios/axios), because isomorphic-fetch was hanging in integration test on Travis-CI using Node v10.

**Comment by FranzSkuffka** [comment]
Man you are doing a great job!

**Comment by Borewit** [comment]
I have been struggling a lot to nail the issue with http getting suck, did not get it to work with any http client, moved that part to #160.
