### ISSUE TITLE
ALAC support?

### ISSUE THREAD

**Issue by Konglomneshued** [Borewit/music-metadata#1563]
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

Basically I am using this package to read audio metadata in an app I am making and I noticed my .m4a (ALAC) files wouldn't play.  I wonder if it's not supported.

I think FLAC is supported, but I use ALAC as I have an iPhone and need to sync my songs with it.

**Comment by Borewit** [comment]
Hi @Konglomneshued `.m4a` are supported. Also ifthe audio stream is encoded with the ALAC codec.

Playing or syncing audio tracks with your iPhone is out of the scope of this module.

**Comment by Konglomneshued** [comment]
> Hi @Konglomneshued `.m4a` are supported. Also ifthe audio stream is encoded with the ALAC codec.
> 
> Playing or syncing audio tracks with your iPhone is out of the scope of this module.

I guess you misunderstood.  I sync my music with iTunes.  But I am making an app which reads metadata and it isn't playing audio when I load an ALAC file.

**Comment by Konglomneshued** [comment]
I think my issue is related to the framework I am using to make my app.  Since it's based on Chrome, which doesn't support ALAC decoding.  Only Safari does.
