### ISSUE TITLE
TypeError: this.buffer.copy is not a function

### ISSUE THREAD

**Issue by FranzSkuffka** [Borewit/music-metadata#157]
Related to #156 
**Bug description**
Using `mm.parseBuffer` results ins `TypeError: this.buffer.copy is not a function`

**Expected behavior**
No error thrown, correct metadata returned

**Code samples demonstrating the problem**
Reprocible on node 8.12 using 

```
  fetch(loc)
    .then(res => mm.parseBuffer(res.body))
    .then(tags => {
        console.log(tags)
        respond(JSON.stringify(tags || 'tagged'))
    })
```

```
  fetch(loc)
    .then(res => res.body)
    .then(blob => mm.parseBuffer(blob))
    .then(tags => {
        console.log(tags)
        respond(JSON.stringify(tags || 'tagged'))
    })
```

**Comment by Borewit** [comment]
That looks like a type mismatch to me, res.body is a [stream.Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable) using it server side, not a Node [Buffer](https://nodejs.org/api/buffer.html).
