### ISSUE TITLE
Error in parse empty tag in mp3 file?

### ISSUE THREAD

**Issue by AlgeriaSoft** [Borewit/music-metadata#16]
this data show when parse mp3 file when this not have any tag
![capture](https://user-images.githubusercontent.com/29903690/27984610-8473d4f2-63da-11e7-924f-0618a349a878.PNG)

when add tag to this file 

![capture](https://user-images.githubusercontent.com/29903690/27984622-edcaa44e-63da-11e7-8b88-b914c6f03faa.PNG)

**Comment by Borewit** [comment]
In case  no ID3v2 tags are found, the parser tries to read ID3v1.1 tags.
It looks like it is not checking if the ID3v1.1 tags are set..
I will fix it, thanks for reporting this.

**Comment by Borewit** [comment]
Fixed in [v0.7.4](https://github.com/Borewit/music-metadata/releases/tag/v0.7.4)
