### ISSUE TITLE
Error when reading valid WAV file: FourCC contains invalid characters: 00 5f 50 4d

### ISSUE THREAD

**Issue by ffxsam** [Borewit/music-metadata#161]
**Bug description**
I'm getting the error "FourCC contains invalid characters: 00 5f 50 4d" when parsing a valid WAV file

**Expected behavior**
It should work properly. This file is saved from Adobe Audition CC, with ID3 metadata.

Let's get in touch if possible. I really need this for a commercial project and can pay you for a bugfix!

[test.zip](https://github.com/Borewit/music-metadata/files/2530083/test.zip)

**Comment by ffxsam** [comment]
Now I can't replicate this, no matter what I do. It's possible I did something wrong with the metadata on that file.

**Comment by Borewit** [comment]
That would be the very the first donation I receive @ffxsam!

I'll check the file.

**Comment by Borewit** [comment]
Fixed in [v3.1.6](https://github.com/Borewit/music-metadata/releases/tag/v3.1.6).

**Comment by ffxsam** [comment]
Awesome, thanks!

**Comment by ffxsam** [comment]
@Borewit I also sent you something. 🍺

**Comment by Borewit** [comment]
Thanks you very much @ffxsam ! Cheers!
