### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by bfromager** [Borewit/music-metadata#163]
V3.1.6
Trying to use music-metadata.parseFile() under Ionic 4/Angular 6

Got the following errors:
ERROR in ./node_modules/strtok3/lib/FsPromise.js
Module not found: Error: Can't resolve 'fs' in '...\node_modules\strtok3\lib'
ERROR in ./node_modules/music-metadata/lib/index.js
Module not found: Error: Can't resolve 'path' in '...\node_modules\music-metadata\lib'
ERROR in ./node_modules/music-metadata/lib/aiff/AiffParser.js
Module not found: Error: Can't resolve 'stream' in '...\node_modules\music-metadata\lib\aiff'
ERROR in ./node_modules/music-metadata/lib/riff/RiffParser.js
Module not found: Error: Can't resolve 'stream' in '...\node_modules\music-metadata\lib\riff'

Not sure if i'm doing something wrong

**Comment by Borewit** [comment]
Client side you you better use [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) which is designed to address the issues you experience now.

Therefor I will continue my answer there: Borewit/music-metadata-browser#13
