### ISSUE TITLE
Parsing the code

### ISSUE THREAD

**Issue by Shmaur** [Borewit/music-metadata#164]
Mp3 parses Chinese character messy code。

**Comment by Borewit** [comment]
@Shmaur:
Can you please provide me a zipped sample of the MP3 track you demonstrating you issue?
Can you describe which fields is wrong?
What value do you get?
What should the value be?

**Comment by Shmaur** [comment]
Thank you for your answer.

Chinese characters messy code error

[你的承诺.zip](https://github.com/Borewit/music-metadata/files/2558579/default.zip)

Uploaded attachments

**Comment by Borewit** [comment]
I can see the following metadata is set:
```JavaScript
{
  "track": {
    "no": 8,
    "of": null
  },
  "disk": {
    "no": null,
    "of": null
  },
  "album": "Dance Dance Dance",
  "artists": [
    "º£ÃùÍþ"
  ],
  "artist": "º£ÃùÍþ",
  "year": 2007,
  "genre": [
    "Pop/Pop"
  ],
  "title": "ÄãµÄ³ÐÅµ"
}
```
I checked the results with [Foobar2000](https://www.foobar2000.org/) & [Mp3tag](https://www.mp3tag.de/en/), and they give the same output.

I think way the headers are encoded are wrong.

I tried to fix the tags to demonstrate it could work just fine.
[你的承诺 fixed.zip](https://github.com/Borewit/music-metadata/files/2558752/fixed.zip)

**Comment by Shmaur** [comment]
yes, Like me

Is the way the file title is encoded itself wrong

Is the audio track damaged

I'll try the other files first

**Comment by Shmaur** [comment]
Thank you very much for your answer

How to repair damaged sound tracks
Because some of the files are the same

**Comment by Borewit** [comment]
I don't think it easy to correct the tag headers. 
You probably need a tag editor, you could use [Picard](https://picard.musicbrainz.org/) which is able to automatically identify which track it is.
