### ISSUE TITLE
MPC support (APE tag)

### ISSUE THREAD

**Issue by LudekStoklasa** [Borewit/music-metadata#165]
Hi, any plan to support MPC (Musepack) ? 
AFAIK it uses APE tags (that you already support), so it could be easy to add?

Currently it reports:
_Music metadata parsing error: Error: No parser found for extension: .mpc (C:/MP3/Faze Action/Broad Souls/Faze Action - 09 - God Inside.mpc)_

Sample file [here](https://www.dropbox.com/s/8c4pqg7b2ypio4x/Faze%20Action%20-%2009%20-%20God%20Inside.mpc?dl=0)

**Comment by Borewit** [comment]
I will look into it.

**Comment by Borewit** [comment]
Initial SV7 & SV8 support can be found in [v3.2.0](https://github.com/Borewit/music-metadata/releases/tag/v3.2.0).

If you can let me know if it is working for you, that would be great.

**Comment by LudekStoklasa** [comment]
Hi, thanks for looking into this and the added support!

Unfortunately it still fails on most of the tracks from the album and took 417 second just for 10 files! 
I guess I should upload all the album, [here it is](https://www.dropbox.com/sh/1u8n0tljj204abf/AABiGvnMCPTKbqgujLAQeOUta?dl=0)

`
Music metadata parsing error: RangeError: Index out of range (C:/MP3/Faze Action/Broad Souls/Faze Action - 04 - Outside.mpc)
Music metadata parsing error: Error: Invalid Musepack signature prefix (C:/MP3/Faze Action/Broad Souls/Faze Action - 07 - Vigilante Song.mpc)
Music metadata parsing error: Error: Unexpected data-type: 3 (C:/MP3/Faze Action/Broad Souls/Faze Action - 02 - Broad Souls.mpc)
Music metadata parsing error: Error: Unexpected data-type: 3 (C:/MP3/Faze Action/Broad Souls/Faze Action - 01 - We Don't Know How.mpc)
Music metadata parsing error: RangeError: Index out of range (C:/MP3/Faze Action/Broad Souls/Faze Action - 08 - There's No Time.mpc)
Music metadata parsing error: Error: Unexpected data-type: 3 (C:/MP3/Faze Action/Broad Souls/Faze Action - 06 - Walking Time.mpc)
Music metadata parsing error: Error: Unexpected data-type: 3 (C:/MP3/Faze Action/Broad Souls/Faze Action - 03 - Three Foot High.mpc)
Scan of repository C:/MP3/Faze Action has been finished in 417 seconds
`

**Comment by Borewit** [comment]
In my machine in takes 19 seconds in full debug mode, but slow it.

The Musepack, stream-version 7 is indeed very inefficient to parse.
Because the tag header is at the end of the file, due to the stream nature of music-metadata (cannot read in reverse direction starting at the end), I have to parse basically the entire file, which is build of of very small bit-aligned frames.

Musepack, stream-version 8 is formatted way more efficient.

Regarding the error(s) I find 2 issues:

1. Error in APEv2 offset: issue #168
2. Support ID3v2 header #169 (track number 7 has ID3v2.4 header as well).

The way the APEv2 headers are written to these files looks a bit suspicious to me. The TAG footer is missing.

**Comment by Borewit** [comment]
I fixed and released the bugs.

I will think about some file specific optimization to improve speed.

**Comment by LudekStoklasa** [comment]
Hi, thanks for update and I must do apologize. I have just found that two files were actually corrupted (03, 06) having each 1.8 GB in size. I found them in my original backup and replaced them back , I have updated them also in the dropbox link to the album above.
I believe that it was the reason for the slowdowns.

**Comment by LudekStoklasa** [comment]
Nevertheless I have done tests with version 3.2.1 and it still takes 57 seconds to scan just [the 10 files](https://www.dropbox.com/sh/1u8n0tljj204abf/AABiGvnMCPTKbqgujLAQeOUta?dl=0) , so still quite slow

**Comment by LudekStoklasa** [comment]
Hi again,
user here https://www.mediamonkey.com/forum/viewtopic.php?p=495101#p495101 
has trouble scan/parse certain MPC files, sample files provided there.

Could you please have a look whether there is something bad with the files or the parser ?

Thanks in advance!
