### ISSUE TITLE
invalid argument, read

### ISSUE THREAD

**Issue by Shmaur** [Borewit/music-metadata#166]
An error can occur by dynamically transferring file parameters.However, music metadata can be obtained directly from the local file.
What's the problem, please
`
router.post('/audio', async (ctx, next) => {

    let upload = ctx.request.body
    let info = {
            music_path: "你的承诺.mp3",
            music_name: "你的承诺",
            music_chanteur: "海鸣威",
            music_albumStudio: "",
            music_artiste: "",
            music_genre: "",
            music_title: "",
            music_year: "",
            music_size: "123",
            music_user: "1",
            music_lossless: '',
            music_subtitle: '',
            music_accompaniment: '',
            music_duration: '',
            music_Img: '',
            music_picture: '',
            music_bitrate: ''
        }
        console.log(upload) 
    for (let i = 0; i < upload.fields.fileName.length; i++) {
        let name = JSON.parse(upload.fields.fileName[i])
        console.log(name) 
        let file_path = path.join(__dirname, `../public/music/${upload.files.file[0].name}`);
        console.log(file_path) //e:\vue\musicServer\public\music\你的时间流逝.mp3
        await mm.parseFile(file_path, {
            native: true
        }).then(metadata => {
            console.log(succeed)
        }).catch((err) => {
            console.error(err.message);  // EINVAL: invalid argument, read
        })
    }
    return ctx.body = {
        info: info
    }
})
`

`
console.log(upload) 
{
fields:{
fields:[
0:"{"music_name":"你的时间流逝","music_chanteur":" 的风格","name":"你的时间流逝.mp3"}"
1:"{"music_name":"生巅峰","music_chanteur":" 地方给","name":"偶尔.mp3"}"
2:"{"music_name":"认为","music_chanteur":"为 ","name":"让我心动.mp3"}"
]
}
}
`

`
error: EINVAL: invalid argument, read
`

**Comment by Borewit** [comment]
Is this supposed to run server side or client side?

Do you have a link to the repo?

**Comment by AN602** [comment]
If anyone arrived at this issue in search for answers like I did, the problem originates from the filePath param. In my case I passed a folder path and not a file path to the parseFile function.
Hope this helps somebody in the future.
