### ISSUE TITLE
Some metadata strings are decoded incorrectly for Bulgarian strings

### ISSUE THREAD

**Issue by strawhatduckk** [Borewit/music-metadata#1689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

7.13.4

### JavaScript module eco system

None

### Current Behavior

I am attempting to get metadata from this mp3 file:
https://drive.google.com/file/d/1q430DvOcEuZu6MQVO37CLjw_69pcBtgh/view?usp=sharing

This is the output. Note the warning as well as the values of `artist(s)` and `title`.
```
{
  format: {
    tagTypes: [ 'ID3v2.3', 'ID3v1' ],
    trackInfo: [],
    lossless: false,
    container: 'MPEG',
    codec: 'MPEG 1 Layer 3',
    sampleRate: 48000,
    numberOfChannels: 2,
    bitrate: 192000,
    codecProfile: 'CBR',
    duration: 117.72
  },
  native: {
    'ID3v2.3': [ { id: 'TIT2', value: '\x00䨀攀渀攀爀椁ἀ' } ],
    ID3v1: [
      { id: 'title', value: 'Jeneri?i' },
      { id: 'artist', value: 'Âåëè÷íå ñòîë³òòÿ. Ðîêñîëàíà' }
    ]
  },
  quality: {
    warnings: [
      { message: 'Invalid ID3v2.3 frame-header-ID: iTPE' },
      { message: 'Illegal ID3v2 tag length' }
    ]
  },
  common: {
    track: { no: null, of: null },
    disk: { no: null, of: null },
    movementIndex: {},
    title: '\x00䨀攀渀攀爀椁ἀ',
    artists: [ 'Âåëè÷íå ñòîë³òòÿ. Ðîêñîëàíà' ],
    artist: 'Âåëè÷íå ñòîë³òòÿ. Ðîêñîëàíà'
  }
}
```

AudioTagAnalyzer returns more or less the same thing:
![CleanShot 2023-05-10 at 19 10 41](https://github.com/Borewit/music-metadata/assets/114894332/ebf48252-9bfa-465d-87a1-d82bbd1ebca3)

However apps like VLC and QuickTime are able to decode the title and description correctly:
![CleanShot 2023-05-10 at 19 11 29](https://github.com/Borewit/music-metadata/assets/114894332/8837389d-15fa-41bd-82a6-fe275273eeea)

### Expected Behavior

I would think the correct expected behaviour would be what is reflected by VLC.

![CleanShot 2023-05-10 at 19 11 29](https://github.com/Borewit/music-metadata/assets/114894332/e943f89f-0b5b-4c65-8648-6f9f8fd3782b)

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
1. The tag ID3v2.3.TIT2 which has the title is specified as UTF16-LE. This does not match the UTF16-BE content
2. The tag value the string is stand [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), this is non-standard. Also the BOM specifies the wring byte order
3. After the BOM field the string value is prefixed with 0x00, 0x00.
4. In addition to the ID3v2.3 tag header a ID3v1 header is present, which does not support Unicode (does not support Bulgerian)

Fixed tag with MusicBrainz Picard:
[testmusic - fixed.zip](https://github.com/Borewit/music-metadata/files/11540491/testmusic.-.fixed.zip)
