### ISSUE TITLE
Expose TS types from the main export

### ISSUE THREAD

**Issue by martpie** [Borewit/music-metadata#172]
**Feature Request**

Hello 👋,

Since an update from v2 to v3, the type, the following does not work anymore:

``` ts
import * as mmd from 'music-metadata';

const test: mmd.IAudioMetadata = { ... }; // IAudioMetadata is not defined...
```

I managed to fix it by importing it with `import { IAudioMetadata } from 'music-metadata/lib/type';
`, but it kind of triggers my OCD 😄 

Could we imagine putting the types back (or at least exporting them) to `index.d.ts`?

**Comment by Borewit** [comment]
Definitions restored in [v3.2.2](https://github.com/Borewit/music-metadata/releases/tag/v3.2.2).

Can you please confirm the warm fuzzy experience having stuff the locations you would expect them to be?

**Comment by martpie** [comment]
🎉 

![screen shot 2018-11-22 at 10 43 56](https://user-images.githubusercontent.com/1311607/48894647-89633580-ee43-11e8-8b7e-89b70ee8217e.png)

**Comment by thoni56** [comment]
I think that IPicture is also missing here.

**Comment by Borewit** [comment]
I will look into it, please create an new issue @thoni56 .

**Comment by Borewit** [comment]
IPicture added in [v3.5.3](https://github.com/Borewit/music-metadata/releases/tag/v3.5.3)
