### ISSUE TITLE
Crash when reading Windows sample file

### ISSUE THREAD

**Issue by LudekStoklasa** [Borewit/music-metadata#174]
Windows there is default sample file in
C:\Users\Music\Public\Sample Music\Sleep away.mp3
and the music-metadata crashes completely (silently) + fails to read its artwork.

The file can be found also [here](https://www.dropbox.com/sh/yskbggww74rpc8t/AAD3sii0VgElqGST46-lPkMWa?dl=0)

**Comment by LudekStoklasa** [comment]
Actually this might be a regression -- as I found more files in my library on which it crashes (hard crash - without an exception that could be caught in JS)

**Comment by Borewit** [comment]
This one is embarrassing. Thanks for reporting it @LudekStoklasa.

This is where it breaks: [FileTokenizer.ts#L59](https://github.com/Borewit/strtok3/blob/bf639880d9f9e0faa1c1e4230b4d8f14211e436e/src/FileTokenizer.ts#L59), reading ahead which results in a read which exceeds the end-of-file boundary.

**Comment by Borewit** [comment]
Workaround released in [v3.2.3](https://github.com/Borewit/music-metadata/releases/tag/v3.2.3)

**Comment by LudekStoklasa** [comment]
Thanks. I can confirm that it no longer crashes in 3.2.4, but the embedded artwork isn't shown.

**Comment by Borewit** [comment]
Ah okay, that's what I thought as well: #176 

Note that this MP3 is not nicely encoded as one may expect from an official Windows sample file.
It contains binary noise with false sync signatures after the ID3 header, causing the entire file to be parsed.

**Comment by Borewit** [comment]
Addressed in [v3.3.0](https://github.com/Borewit/music-metadata/releases/tag/v3.3.0)
