### ISSUE TITLE
Module not found: Can't resolve './id3v1/id3v1'

### ISSUE THREAD

**Issue by C-Higgins** [Borewit/music-metadata#18]
I'm getting 
`Module not found: Can't resolve './id3v1/id3v1' in '......\node_modules\music-metadata\lib'`

Any ideas here? id3v1/id3v1 is indeed not a file that exists.

**Comment by Borewit** [comment]
Appreciate your feedback.
Please try with [version 0.7.6](https://github.com/Borewit/music-metadata/releases/tag/v0.7.6).

**Comment by Borewit** [comment]
Can you let me know if your issue is solved?
