### ISSUE TITLE
ambiguous indirect export: parseFile

### ISSUE THREAD

**Issue by thejacer87** [Borewit/music-metadata#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

^8.1.4

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

in nuxt 3

i import the module:

```
import { parseFile } from "music-metadata";

...

const metadata = await parseFile(props.src);
```

strangely `parseStream` is imported just fine, even though they are both exported in the same manner:

```
export declare function parseStream(stream: Stream.Readable, fileInfo?: strtok3.IFileInfo | string, options?: IOptions): Promise<IAudioMetadata>;
export declare function parseFile(filePath: string, options?: IOptions): Promise<IAudioMetadata>;
```

### Expected Behavior

for it to parseFile

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by JannieT** [comment]
@thejacer87 you say that the expected behaviour is "for it to parseFile". How do you know it does not parseFile?
