### ISSUE TITLE
After importing the music-metadata, the terminal prompted two errors. I am a novice and I am currently confused.

### ISSUE THREAD

**Issue by Violexjj** [Borewit/music-metadata#1827]
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

ERROR in node:buffer                                                                                               
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

ERROR in node:stream
Module build failed: UnhandledSchemeError: Reading from "node:stream" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

**Comment by Borewit** [comment]
This module is primary written for Node.js. I cannot help every user mocking the module for client side use.
