### ISSUE TITLE
React Native Compatability

### ISSUE THREAD

**Issue by markmccoid** [Borewit/music-metadata#1849]
### Has the question been asked before?

- [X] I have searched the existing issues

### Question

I'm using React Native and Expo v49 and was wondering if there was any way to get this package to work in React Native.

I have played a bit with it, but I'm wondering if the package's dependency on Node will be an issue.

Thanks!

**Comment by Borewit** [comment]
Probably this is possible. But I cannot give guidance on each different framework. In principle this module is wirtten for Node.js.

**Comment by Borewit** [comment]
Browser support has been improved in [v9.0.0](https://github.com/Borewit/music-metadata/releases/tag/v9.0.0)

**Comment by andy380743909** [comment]
Hi @Borewit ,
Thank you for developing the nice project.

I'm using the library in a ReactNative music player project. When I use `parseBuffer` function, it throws an error:
```
[RangeError: Unknown encoding: latin1 (normalized: latin1)]
```

here is my code:
```
const buffer = await RNFS.readFile(decodedPath, 'base64')
            const uint8Array = base64ToUint8Array(buffer)

            const metadata = await parseBuffer(uint8Array, { mimeType: 'audio/mpeg' })

            console.log('Title:', metadata.common.title)
            console.log('Artist:', metadata.common.artist)
            console.log('Album:', metadata.common.album)
            console.log('Picture:', metadata.common.picture?.[0])
            console.log('Lyrics:', metadata.common.lyrics)
            const metadataJson = JSON.stringify(metadata)
```

Does this mean this library not support React Native?

**Comment by Borewit** [comment]
I just noticed you already opened #2474, and pinpointing where the issue occurs. 👍🏻
