### ISSUE TITLE
Duration: +Infinity when parsing m4a file

### ISSUE THREAD

**Issue by arnaudmartin99** [Borewit/music-metadata#1860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

7.12.6

### JavaScript module eco system

CommonJS modules (CJS), music-medata ≤ version 7

### Current Behavior

A m4a file parsed with parseBuffer returns a duration of +Infinity

### Expected Behavior

The m4a file parsed with parseBuffer returns a duration of around 1683 seconds

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by arnaudmartin99** [comment]
Hello Borewit,

Thank you for maintaining this library, it is useful and works very well !

I have a m4a audio file parsed with a duration of +Infinity. I investigated a bit and it seems that the duration is correctly parsed but the timeScale is 0, causing the division to return +Infinity.

I have seen that https://github.com/Borewit/music-metadata/issues/797 is a similar issue but couldn't provide the audio file to reproduce it because of copyrights. As you seem to be working on the subject ([#801](https://github.com/Borewit/music-metadata/pull/801)), I thought I could help by providing you with an audio file that is readable but parsed incorrectly. I will send it to you by email.

Feel free to ask me if you need additional information

**Comment by Borewit** [comment]
Are you able to test this PR: #1861 @arnaudmartin99 ?

**Comment by arnaudmartin99** [comment]
> Are you able to test this PR: #1861 @arnaudmartin99 ?

Yes: the duration returned is not Infinity anymore but 1683.6053333333334, as expected.

Thank you !
