### ISSUE TITLE
(node:46542) UnhandledPromiseRejectionWarning: Error: gg audio-codec not recognized (id=theora)

### ISSUE THREAD

**Issue by ithustle** [Borewit/music-metadata#187]
**Bug description**
`(node:46542) UnhandledPromiseRejectionWarning: Error: gg audio-codec not recognized (id=theora)
    at OggParser.<anonymous> (/Users/celiogarcia/dev/server/vienna-server/node_modules/music-metadata/lib/ogg/OggParser.js:82:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/celiogarcia/dev/server/vienna-server/node_modules/music-metadata/lib/ogg/OggParser.js:4:58)`

**Expected behavior**
Show the metadata. bitrate, duration, samplerate... 

**Audio file demonstrating the problem**
[Uploading Fruto-Proibido.ogg.zip…](audio .ogg)

**Comment by Borewit** [comment]
Looks like you file didn't make it into the issue...

Hi @ithustle, [Theora](https://en.wikipedia.org/wiki/Theora) is video stream.
music-metadata is most on audio formats, although it does support some MPEG video's as well.

Do you know it this Ogg/Theora really has metadata?

**Comment by ithustle** [comment]
@Borewit, hi.
Yep it has. I converted the mp3 file to ogg and this same mp3 file has metadata.
And yes, it is a audio file.

**Comment by ithustle** [comment]
Aditional info: I'm using `ffmpeg` to convert mp3 audio files to ogg.

**Comment by ithustle** [comment]
> Hi @ithustle, Theora is video stream.
This information that you gave to me, make me thing another things, now I converted with `sox`, metadata now is showing. 

@Borewit , thanks for support.

**Comment by ithustle** [comment]
FIA
[Uploading Fruto-Proibido.ogg.zip…](File)

**Comment by Borewit** [comment]
Unrelated to the issue, please be aware that converting from any lossy format to another will result in drastic quality loss.

**Comment by ithustle** [comment]
Got it. Thanks

**Comment by Borewit** [comment]
Sorry, your upload did't work again.

**Comment by Borewit** [comment]
Great, both them working now, thanks!

I will look into it tomorrow.

**Comment by Borewit** [comment]
Fixed in [v4.0.1](https://github.com/Borewit/music-metadata/releases/tag/v4.0.1)
