### ISSUE TITLE
run function after processing multiple tracks

### ISSUE THREAD

**Issue by vasyl-shumskyi** [Borewit/music-metadata#189]
Hello,

Thanks for the great module! 

I need to run a function or some code on collected metadata of multiple tracks. Tracks count is from 1000 to 10000

What is correct way to do so? Because of async nature of the module I can't accomplish this properly

My code is like: 

```javascript
const mm = require('music-metadata')

var tracks = [ 'track1.mp3' .... 'track1000.mp3' ]
var titles = []

for (track of tracks) {

    mm.parseFile(track)
      .then( metadata => {
          titles.push(metadata.common.title)
      })
     .catch( err => {
        console.error(err.message);
     })
}

if (track == tracks[tracks.length-1])
   console.log(titles)    // => expect array with titles, but receive empty array :(

```

Thanks!

**Comment by vasyl-shumskyi** [comment]
Following seems to be working. If there is better solution I will be very grateful. 

```javascript
const mm = require('music-metadata')

var tracks = [ 'track1.mp3' .... 'track1000.mp3' ]
let titles = []
let counter = 0

for (track of tracks) {

    mm.parseFile(track)
      .then( metadata => {
          counter++ 
          titles.push(metadata.common.title)
          if (counter == tracks.length)
               console.log(titles)   
      })
     .catch( err => {
        console.error(err.message);
     })
}
```

**Comment by Borewit** [comment]
I added secition to the README to give some advice on this, you are not the first one asking: https://github.com/Borewit/music-metadata#using-recursion.

Related: #134, #109, #26

Let me know if it worked out for you.

**Comment by vasyl-shumskyi** [comment]
Thanks for your kindness @Borewit I will give it a try!
