### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'codecName' of undefined

### ISSUE THREAD

**Issue by MaddyCrowle** [Borewit/music-metadata#194]
Hi! Here is my code:

```
var streamaddr = 'url_to_http_stream';

http.get(streamaddr, (resp) => {

    // A chunk of data has been recieved.
    resp.on('data', (chunk) => {

        try
        {
            mm.parseBuffer(chunk, 'audio/ogg', { fileSize: 26838 })
            .then( metadata => {
                console.log(util.inspect(metadata, { showHidden: false, depth: null }));
            });
        }
        catch (e)
        {

        }
        
    });
}).on("error", (err) => {
    //console.log("Error: " + err.message);
  });
```
Seems it works, first part of data received is correct (tags array), but after 1 second appears this:

(node:25944) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'codecName' of undefined
    at OggParser.<anonymous> (/path_to_project/node_modules/music-metadata/lib/ogg/OggParser.js:85:86)
    at Generator.next (<anonymous>)
    at fulfilled (/path_to_project/node_modules/music-metadata/lib/ogg/OggParser.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:25944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Am i wrong in my code or is it a bug?

**Comment by MaddyCrowle** [comment]
I'm trying to read audio stream via http, so no - chunk is not entire file, it's streaming/buffering data.
fileSize i left untouched from your example, could you tell me what size shall i pass in this^ case?
content-type: yes, it's ogg vorbis stream.

**Comment by Borewit** [comment]
That is not going to fly like that my friend.

You probably want to stream the data into music-metadata, there is an [examle (stream.js)](https://github.com/Borewit/music-metadata/blob/master/example/javascript/stream.js), not sure if it is up to date.

There is also a [unit test reading from http](https://github.com/Borewit/music-metadata/blob/master/test/test-http.ts), that one works for sure.

**Comment by MaddyCrowle** [comment]
Thanks a lot, it will help!

**Comment by Borewit** [comment]
No problem, let know if you managed get it working.

**Comment by MaddyCrowle** [comment]
Actualy, [this](https://github.com/Borewit/music-metadata/blob/master/example/javascript/stream.js) code works fine, but i managed to take results with mp3 stream only, when i tried to put there my ogg stream (IceCast2+IceS), it says: Parsing: application/ogg and that's all, no usefull data. Isn't it audio/ogg? What shall i do?

**Comment by MaddyCrowle** [comment]
Actualy, [this](https://github.com/Borewit/music-metadata/blob/master/example/javascript/stream.js) code works fine. Firstable i thought it doesn't work because no data was fired, but i waited for a while and it appeared. Is it normal to wait for a few seconds to get results?

**Comment by MaddyCrowle** [comment]
I investigated it and realized, that tag data comes after a song ends. It means i have tag data of previous song, not the currently playing. Is this expected behaviour of your module?

**Comment by Borewit** [comment]
> Actualy, [this](https://github.com/Borewit/music-metadata/blob/master/example/javascript/stream.js) code works fine. But it seems something is wrong still, because i waited for 2 or 3 minutes to get results. Is it normal? Tag data has pictures (few MB).

There are a lot of factors influencing the speed:
- Your network connection (HTTP connection to the source you are downloading from)
- Audio file type, with MP3 it depends strongly on the encoding type and the presence of some headers
- Some tweaks you can set in options
- CPU capacity

In general you can expect music-metadata to parse a file in ~1/10 of second (not based on strong evidence), maybe a few seconds over an HTTP connection sounds reasonable, 2 or 3 minutes is very slow .

> I investigated it and realized, that tag data comes after a song ends. It means i have tag data of previous song, not the currently playing. Is this expected behavior of your module?

Playing and parsing at the same time? That is tricky, maybe that is what slowing down the parsing. Most tag headers appear before the audio data, but some after. Music-metadata can read all of those, but you can set `options.skipPostHeaders = false`, to prevent it looking for "post headers". 

There is something else you can try, you can pass an oberver function to the options: `options.observer = metaEvent => { // will get metadata here in real-time (while parsing) }`. It will at least give you more understanding of the timing.

Another thing to better see what is going on. set environment variable DEBUG to *, that will give you detailed debug messages. You can do it also in code:
```
process.env.DEBUG = '*'; // Make sure you set this at the very beginning of you code, BEFORE your imports
```

Finally, if HTTP download is the bottle neck, I worked on a [HTTP-client which is using chunked reads](https://github.com/Borewit/streaming-http-token-reader). It is designed to work on client side, not sure if works on Node, or how hard it is. It requires your server to support checked transfer as well. Great stuff, but you have to be very aware are doing.

**Comment by MaddyCrowle** [comment]
> you can set options.skipPostHeaders = false, to prevent it looking for "post headers".
`false` or `true` exaclty to prevent?

I used `options.observer` and saw data streaming of currently playing song (check please [log](https://drive.google.com/file/d/1uhhsPi5oW_OUBdG87AVnsnMcBdi0woUF/view?usp=sharing) file) and it seems module awaits for end of this stream or of all headers.

Also check please this [debug log file](https://drive.google.com/file/d/1yIjUVxEIqSFk8MrZrHzv_n8_BkoUe9Lo/view?usp=sharing)

Shall (and can?) i grab data from observer?
Actualy i need just artist, title, year and picture tags.

**Comment by MaddyCrowle** [comment]
According log file you can see artist and title headers appears almost at very beginning, and then a lot of data awaits.

**Comment by Borewit** [comment]
You can use from the observer, no problem. You can filter on specific fields if you require. Note that some fields may be provided multiple time, best to update with the last value. It is there to lower bandwidth stream, to give metadata as soon as possible.

`options.skipPostHeaders = true`, to skip post header indeed.
But is has not or hardly any effect on Ogg parsing.

If the performance is important for you in combination with Ogg files, you can create an issue to stop reading from an Ogg file after reading the metadata header.

**Comment by MaddyCrowle** [comment]
Thanks for help! I managed to parse metadata in real-time and sending it to client part once per 3 secs. But i have 1 more question: there is picture tag, and it looks like this:
```
picture:
      [ { type: 'Cover (front)',
          format: 'image/jpeg',
          description: 'Front Cover',
          width: 0,
          height: 0,
          colour_depth: 0,
          indexed_color: 0,
          data:
           <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 02 01 01 02 01 01 02 02 02 02 02 02 02 02 03 05 03 03 03 03 03 06 04 04 03 ... > } ]
```

Why width and height are 0, and how to use 'data' in src attribute of img HTML tag? What is the <Buffer ... ?

**Comment by Borewit** [comment]
So regarding the conversion to HTML you can do something like this:
https://github.com/Borewit/audio-tag-analyzer/blob/9b2cb3d702b663e03a7995a72520c8da011514af/src/app/app.component.html#L71

But maybe you already figured it out yourself.

The width and height are part of the metadata. These are the picture dimension as litterly written in metadata tag. 0 is close to not specified ([ref](https://wiki.xiph.org/index.php?title=VorbisComment&mobileaction=toggle_view_desktop#Image_dimension_fields)), so yeah, you could say it may better to set not define the `picture.width` property in that case.

**Comment by MaddyCrowle** [comment]
Yea, i figured it out, but you gave me an idea to convert src blob data to base64 in addition. Now it seems everything is working now, thanks again!
