### ISSUE TITLE
Add  support for DSF (DSD Stream File) format

### ISSUE THREAD

**Issue by volumio** [Borewit/music-metadata#195]
**Feature Request**

The library does not support the quite popular DSD  format ([dff](https://github.com/Borewit/music-metadata/issues/196) and dsf). 
See here for specifications:
https://dsd-guide.com/sites/default/files/white-papers/DSFFileFormatSpec_E.pdf

I am willing to offer support to make it happen

PR: #197

**Comment by Borewit** [comment]
Definitely something music-metadata should support.
Sounds like a plan, let's do it @volumio.

**Comment by volumio** [comment]
@Borewit Great.

Tell me how can I support and I'll do it. If you want we can communicate directly via mail at info at volumio dot org

**Comment by Borewit** [comment]
I'll have a chat channel using Discord: https://discord.gg/KyBr6sb

If the implementation is doable, I assume you can test it.
I will assess to understand what else needs to be done.
Sample data for unit test is strongly desired, I'll like to keep the audio samples as small as possible.

**Comment by Borewit** [comment]
Beta version released with DSF parser: 3.6.0-beta.0

**Comment by Borewit** [comment]
Fixed bitrate for DSF format in: [3.6.0-beta.1](https://www.npmjs.com/package/music-metadata/v/3.6.0-beta.1)

**Comment by Borewit** [comment]
Implemented in [v3.6.0](https://github.com/Borewit/music-metadata/releases/tag/v3.6.0)
