### ISSUE TITLE
Add support for DSDIFF (Direct Stream Digital Interchange File Format)

### ISSUE THREAD

**Issue by volumio** [Borewit/music-metadata#196]
**Feature Request**

The library does not support the quite popular DSD format (dff and dsf).
See here for specifications:
http://www.sonicstudio.com/pdf/dsd/DSDIFF_1.5_Spec.pdf

PR: #198

**Comment by Borewit** [comment]
Beta version released with DSF parser: 3.6.0-beta.0

**Comment by Borewit** [comment]
Beta version released with DSDIFF parser: 3.6.0-beta.0

**Comment by Borewit** [comment]
Support for bitrate released in [3.6.0-beta.2](https://www.npmjs.com/package/music-metadata/v/3.6.0-beta.2)

**Comment by Borewit** [comment]
Implemented in [v3.6.0](https://github.com/Borewit/music-metadata/releases/tag/v3.6.0)
