### ISSUE TITLE
Parsing WebM consumes a lot of CPU and is slow

### ISSUE THREAD

**Issue by Android789515** [Borewit/music-metadata#1961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

8.2.0

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

When my program gets to reading a WebM file it slows down and starts consuming a lot of CPU.  It takes a while just to parse it.  17 seconds to start reading it and 17 seconds to finish.

When I remove the WebM file I have no lag when reading files.

### Expected Behavior

File is read fine and swiftly like the rest of my files.
[a-ha - Take On Me.webm.zip](https://github.com/Borewit/music-metadata/files/13799908/a-ha.-.Take.On.Me.webm.zip)

I provided a sample WebM file which still takes considerably more time to read than its equivalent MP3 counterpart.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
That can very well be. Not much I can do about that.

**Comment by Android789515** [comment]
Any chance there's something that can be done?  Parsing Webm files is slowing down my app.

**Comment by Borewit** [comment]
> Any chance there's something that can be done? Parsing Webm files is slowing down my app.

Did you try `mkvUseIndex` (implemented in #2219 ) as described [here](https://github.com/Borewit/music-metadata?tab=readme-ov-file#ioptions-interface)?

**Comment by Android789515** [comment]
> > Any chance there's something that can be done? Parsing Webm files is slowing down my app.
> 
> Did you try `mkvUseIndex` (implemented in #2219 ) as described [here](https://github.com/Borewit/music-metadata?tab=readme-ov-file#ioptions-interface)?
> 
> I am curious in results, can you provide some numbers?

Looks like the latest version of music-metadata has already fixed the issue.  I updated it to be able to use the mkvUseIndex and no longer experiencing any slowdown.
