### ISSUE TITLE
expose `core` as separate package export entry in version 8

### ISSUE THREAD

**Issue by minht11** [Borewit/music-metadata#1973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

expose `core` as separate package export here:
https://github.com/Borewit/music-metadata/blob/72a40061a1ba2d85336cbd8d756fec25b9a23e72/package.json#L14-L19
currently importing version 8 in the browsers with vite produces warning "buffer, fs packages must be externalized" and so on and generally doesn't work for me.

Previously with version 7 it was possible to import from `music-metadata/lib/core` which did not have any issues above.

**Comment by Borewit** [comment]
I am not what problem we fix if I add "core".

Version 7 is CommonJS module, since version 8 it is an ESM module.

Please have a look at #1259.

**Comment by minht11** [comment]
I did look into that. The issue being that because of how you wrote package.json exports, core.js and index.js are merged into same entry and even if you load only `import mm from 'music-metadata'` index.js also will be loaded. That is problematic because it does contain much more node specific things which break Vite in browser.

I am using version 7, load only core and things are great (besides minor need to pollyfill buffer), in version 8 that is not possible, because of issue above. Still my prefererance would to migrate CJS to ESM where possible.

**Comment by Borewit** [comment]
This problem is caused by this project.

**Comment by minht11** [comment]
I mean it is, being able to import only core was a feature which was available in version 7, but is not in 8.

But I understand if you do not wish to support that in newer version.
