### ISSUE TITLE
Sometimes observer doesn't want to exit

### ISSUE THREAD

**Issue by MaddyCrowle** [Borewit/music-metadata#199]
Hello. Sorry, it's me again. I have an issue, and I don't know if it is my fault or an feature/bug in your module. Could you help me to identify why it happens?

I need to start my script endless, as daemon, so i established forever and do this:

`forever start -c "node --expose-gc --max-old-space-size=512" live.js`

inside live.js i have code:

```
var http = require('http');
var winston = require('winston');
var io = require('socket.io').listen(2100);
const mm = require('music-metadata');

var metadata;
var mimeType;
var httpurl = 'http://some_http_address';

async function httpGet (url) {
  return new Promise(function (resolve, reject) {
    http.get(url, function (res) {
      switch (res.statusCode) {
        case 200:
          resolve(res);
          break;
        case 302: // redirect
          resolve(httpGet(res.headers.location));
          break;
        default:
          reject(new Error('Unexpected status-code:' + res.statusCode));
      }
    });
  });
}

async function GetData()
{
  // Get http content
  metadata = await httpGet(httpurl, {native: true});
  mimeType = metadata.headers['content-type'];

  await ParseTags();

  /* Garbage clean */
  metadata = null;
  mimeType = null;
}

async function ParseTags()
{
  return await new Promise((resolve, reject) => {
    if (metadata && mimeType)
    {
      mm.parseStream(metadata, mimeType, {native: false, skipPostHeaders: true, observer: metaEvent => { 

          logger.info('mm.Observer start.');
          
          if (metaEvent.metadata.common)
          { 
            Do some stuff...
          }

          logger.info('All done.');

        }}).then(() => {
          logger.info('Resolve.');
          resolve();
        });
    }
    else
      reject();
  });
}

async function Live()
{
  logger.info('Live started.');
  do {
    logger.info('Iteration started.');
    await GetData();
    logger.info('Iteration ended.');
  } while (1);
}

Live();
```

Everything goes fine until it stops to fire `resolve()` at all. It happens when script works about 8 hours. I tried to catch any errors, but no errors in logs, no rejects in logs. It stucks right after `logger.info('All done.');` (i mean 'All done' is the last entry in log, nothing after it, and can't exit from observer and function can't return neither resolve nor reject) and what is more interesting - script keeps alive.

What can it be?

P.S. httpurl - is live ogg stream.

**Comment by Borewit** [comment]
First some some async/await fundementals

- An async function will always return a promise, `return;` is the same as `promise.resolve();`, `throw new Error('damn');` is the same as `promise.reject('damn');` The promise declaration in `httpGet` is fine, because you need to convert an non promise based async function into a promise based function, you need explicitly wire the promise. 
- Try not to use .`then()`, use `await`, that is whole point of the async/await syntax, to simplify the promise handling

You get something like this:
```JavaScript
async function ParseTags() {
  if (metadata && mimeType) {
    await mm.parseStream(metadata, mimeType, {
      native: false, skipPostHeaders: true, observer: metaEvent => {

        logger.info('handle metadata event...');

        if (metaEvent.metadata.common) {
          // Do some stuff...
        }

        logger.info('handling metadata event done.');
      }
    });
    logger.info('End of never ending Ogg stream?');
  } else
    throw new Error('Missing metadata or mimeType'); // No need to return explicit promise in async function
}
```
music-metadata is not directly written for continues stream, or maybe I should say, never really tested in that kind of scenario by me. In principle I don't seen anything wrong with your code. I am a bit suspicious towards the loop, is that called frequently?

**Comment by Borewit** [comment]
I have created a small application based on your code: https://github.com/Borewit/ogg-radio-stream

I noticed a few things:
1. music-metadata repeats a lot of time the same event (issue on my end)
2. after an HTTP failure you immediately reconnect, slow that down a bit, no good for other end, no good for your app

**Comment by Borewit** [comment]
Repeating `format.dataformat` tag fixed in [v3.5.4](https://github.com/Borewit/music-metadata/releases/tag/v3.5.4)

**Comment by MaddyCrowle** [comment]
Thank you very much! I followed all tips you gave me here, and, you know, it works much better and polite now) In addition i managed to catch errors better. At least there is no more odd stuck in observer, though it still has an issue - every 6-8 hours it throws error 'expected ogg header but was not found' and repeats it for 10 minutes, then everything works fine again for next 6-8 hours. I was observing it for 4 days, and every day, each 6-8 hours of live stream and exactly for 10 minutes it throws this error. What can it be?)

P.S. Also many thanks for update, now there are no more thousands duplicate entries in logs with tags observing and +10Gb log files each day)

**Comment by Borewit** [comment]
Go to hear you are making progress.

> very 6-8 hours it throws error 'expected ogg header but was not found' and repeats it for 10 minutes, then everything works fine again for next 6-8 hours.

That sounds some currupted data reaches music-metadata, or maybe a synchronization problem. WIth a synchronization problem I mean, that music-metadata ends of reading the header from the wrong offset. Since the error doesn't occure ofton, it can be very hard to find it.

Although a bit of effort, it may be worth to start capturing the stream. If you keep the last succesfull Ogg file streamed, and the data received from the call until the error, we can use that for further analysis.
More specfic, we need to data from the last successfull synced Ogg header until the point it tries the read the next Ogg header, which for some reason is no longer an Ogg header.

If storage is not an issue, you may conider saving the entire stream as well. Point is, you need to  look into the magic 10 minutes ;-).

Can you share the URL of the radio station you are analyzing?

**Comment by MaddyCrowle** [comment]
Actually this is my own stream, i just established IceCast2 on my VPS and put there several songs for tests. The stream is http://air.muzkanal.ru:8182/one

What is more interesting - as i said, there are just several songs which just rotates from playlist's beginning to it's end and then repeats. It means that during the day playlist repeats several times, and the error occures at it's different parts.

Ok, firstable i made error reporting more detail, and the error says:

```
AssertionError [ERR_ASSERTION]: Ogg capture pattern
    at OggParser.<anonymous> (/home/dev/jsnode/airtime/node_modules/music-metadata/lib/ogg/OggParser.js:54:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/dev/jsnode/airtime/node_modules/music-metadata/lib/ogg/OggParser.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Then, i started to capture ogg stream in file. So when i got the error next time, i downloaded stream file to check what was the problem when error has occured. I identified, that error has occured just about 6 hours 47 minutes after stream started. But I have another problem - 2GB ogg stream file, i've tried to open it in different media players, and all of them failed to rewind forward/backward. Opening it via web browser doesn't allow to rewind at all. After i converted it to mp3, i was able to rewind without any problem, but stream became shorter by about 1 hour. How can i open ogg and quickly go to position i need?

Could you provide me any another ogg stream for tests?, maybe something wrong with my IceCast server.

[Captured ogg stream here](https://drive.google.com/open?id=1ro4vhmL68M_Hp_HK873Q4mQ58yum-YuR)
[Combined log file here](https://drive.google.com/open?id=1K17LAua15vY5UaiC3cnR8ImC9vVufCYP)

**Comment by Borewit** [comment]
>  How can i open ogg and quickly go to position i need?

With Windows running [foobar2000](https://www.foobar2000.org/), no problem.

**Comment by MaddyCrowle** [comment]
ok, i connected another online ogg stream (from your script), and there was no error. I admitted that something is wrong with my icecast streaming (what exactly - i couldn't identify). Sorry for disturbing.

**Comment by Borewit** [comment]
@MaddyCrowle, no problem.
When I have an opportunity (time-wise), I will analyze your captured stream, maybe I notice something strange. I already had quick look, I did not see anyhting strange so far.

**Comment by MaddyCrowle** [comment]
@Borewit I think everything is alright with captured stream, i even tried totally change whole playlist by replacing it with another songs, but error still appears, although, now is different:

```
2019-04-23T03:35:56.416Z [Unit test] error: AssertionError [ERR_ASSERTION]: Ogg capture pattern
    at OggParser.<anonymous> (/home/dev/jsnode/airtime/node_modules/music-metadata/lib/ogg/OggParser.js:54:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/dev/jsnode/airtime/node_modules/music-metadata/lib/ogg/OggParser.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I think something is wrong exactly in real time streaming, maybe icecast itself, i tried to compare time of this error with any errors in icecast error log, but didn't find anything useful. So i didn't manage to solve it, and almost gave up.

Anyway thank you for your assistance and answers!

**Comment by Borewit** [comment]
> @Borewit I think everything is alright with captured stream, i even tried totally change whole playlist by replacing it with another songs, but error still appears, although, now is different.

I went through the entire stream:
```JavaScript
const filePath = 'C:\\tmp\\dump-one.ogg';

const stream = fs.createReadStream(filePath);

let n = 1;

while (stream.readable) {
  console.log(`Reading from stream...`);
  const metadata = await mm.parseStream(stream, 'audio/ogg');
  assert.strictEqual(metadata.format.bitrate, 320000);
  assert.deepEqual(metadata.format.dataformat, 'Ogg/Vorbis I');
  console.log(`End of Ogg file ${n}`);
  ++n;
}
console.log(`End of stream`);
```
took a while (~50 seconds), but no exceptions.

> I think something is wrong exactly in real time streaming

Possible. Which also could be a small bug somewhere in the underlying libraries (e.g. my own [then-read-stream](https://github.com/Borewit/then-read-stream)), real-time streaming causes packages to be segmented differently.

The error is the same by the way, it maybe look different because I slightly changed that code.

It looks like the Ogg stream is getting corrupted somewhere.

**Comment by MaddyCrowle** [comment]
If you don't mind, I would like to write here solution of mentioned issue. Finally, I managed to solve it, and the problem was in corrupted ogg stream, yes, but not in IceCast itself, but in IceS. I discovered it by replacing IceS with Liquidsoap. Now it works!

**Comment by Borewit** [comment]
Great to hear you got it finally working!

Thanks for sharing your experience!
