### ISSUE TITLE
Uncaught error with id3v4

### ISSUE THREAD

**Issue by Jontyy** [Borewit/music-metadata#2]
Hi,

https://github.com/Borewit/music-metadata/blob/master/src/id4.ts#L159 

The above error is never caught, due to this library being async we cannot catch it when integrating.

**Comment by SirWindfield** [comment]
Any idea how to fix it? Not sure if it is that much of a problem. If the library is async, there is no real possibility of catching the error, maybe using a `Promise` would allow catching it.

**Comment by Jontyy** [comment]
You should do something like: 

https://github.com/Borewit/music-metadata/blob/master/src/id4.ts#L109

Or a quick fix would be adding this on line 84:

```javascript
try {
    const results = this.processMetaAtom(v, cb.atomName, cb.atomLength - 8);
} catch (err) {
    return done(err);
}
```

It is a problem for us as putting one of these m4a files into this will crash the whole service, as a temporary fix we've wrapped our integration with this library in a domain, but these are deprecated so its not ideal.

Async libraries should not throw errors: https://www.joyent.com/node-js/production/design/errors

Promises cannot catch errors of async libraries, you would have to resolve/reject depending on the callback.

**Comment by SirWindfield** [comment]
> Promises cannot catch errors of async libraries, you would have to resolve/reject depending on the callback. 
That's what I wanted to say :smile: But that would need some serious refactoring to make it work.

**Comment by Borewit** [comment]
Refactoring to promises will imply some serious refactoring. Promises can catch rejects. Exceptions can be caught and converted into rejects. 

Looks like a reasonable fix to me @Jontyy. 
I tried to fix it: 91beb02a1caa03a65be86d7a7c431953773b828b

**Comment by Jontyy** [comment]
Awesome, thanks for this, fixes the issue we were having :)

I would have submitted a PR with a test case but unfortunately I've no idea what sort of tags the file had, assuming iTunes?

I logged the `atomName` and `type` if this is of any use:

```
Â©na text
Â©AR text
aART text
Â©al text
stik undefined
```

**Comment by SirWindfield** [comment]
Looks like iTunes is currently not supported. I put it on the roadmap though.

**Comment by Borewit** [comment]
Can you provide the file @Jontyy ?

**Comment by Jontyy** [comment]
@Borewit sorry, unfortunately its a customer's file so I wont be able to share it.
