### ISSUE TITLE
Excessive memory use when parsing certain ID3 headers

### ISSUE THREAD

**Issue by bjorn-nesby** [Borewit/music-metadata#2002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

7.14

### JavaScript module eco system

CommonJS modules (CJS), music-medata ≤ version 7

### Current Behavior

I've come across files which contain large, and largely empty, ID3v2 headers.  
When such files are parsed, any application using music-metadata might appear to freeze or worse, crash when reaching the heap limit. 

To demonstrate, try to drop the provided file onto the [Audio Tag Analyzer](https://audio-tag-analyzer.netlify.app/): 
[large_id3_header.wav.zip](https://github.com/Borewit/music-metadata/files/14448127/large_id3_header.wav.zip)

On my machine, the browser tab will eventually become unresponsive.    

### Expected Behavior

It's of course reasonable to expect that such a file could take a considerable amount of time to parse (processing several MBs in tiny steps), but the side-effects are unexpected. 

It's particularly tough that it can lead to a crash, and I'm wondering if applying some kind of heuristics might make sense here (e.g. to simply skip a header if it's considered 'too large')?  

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by bjorn-nesby** [comment]
As a temporary fix, I've modified the ID3v2Parser.parseMetadata method to bail out when more than 100K errors have been generated. The metadata is still extracted from the test file I supplied, and the library is passing all mocha tests. 

If someone wants me to put up a PR, I'd happy to do so.

**Comment by Borewit** [comment]
I had look to your sample. In Node.js in debug mode, it takes 3.9 seconds to parse the file, no issues. A browser may be more sensitive. To have this kind of ID3 header does not make any sense. There is always reverse engineer some data to entertain the parser.

**Comment by bjorn-nesby** [comment]
Just to clarify, I didn't engineer these files, they appeared as part of a commercial sample pack*. And as things are, a node.js application might very well freeze or crash when the V8 engine isn't able to allocate more resources.

For example, here are some details from such a crash:
```` 

<--- Last few GCs --->

[3425:0x7fc070231000]   177340 ms: Scavenge 1995.2 (2064.7) -> 1992.8 (2065.9) MB, 3.6 / 0.0 ms  (average mu = 0.659, current mu = 0.404) allocation failure; 
[3425:0x7fc070231000]   177348 ms: Scavenge 1996.1 (2065.9) -> 1993.7 (2066.7) MB, 3.4 / 0.0 ms  (average mu = 0.659, current mu = 0.404) allocation failure; 
[3425:0x7fc070231000]   179108 ms: Scavenge 1997.0 (2066.7) -> 1994.5 (2074.9) MB, 1755.3 / 0.0 ms  (average mu = 0.659, current mu = 0.404) allocation failure; 


<--- JS stacktrace --->

[3425:0229/105646.552138:ERROR:v8_initializer.cc(714)] V8 javascript OOM (Reached heap limit).
[0229/105646.566016:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeedcf0000, 0x2000): (os/kern) invalid address (1)
[3417:0229/105646.852725:INFO:render_frame_host_impl.cc(11664)] RenderFrameHostImpl::MaybeGenerateCrashReport url = file:///index.html, status = 3, exit_code = 5
````

> There is always reverse engineer some data to entertain the parser.

Indeed. But isn't that to be expected when parsing random files in the wild? Some are bound to be broken in one or the other way (I guess you have plenty of experience here). And your library even recognizes that something isn't right with the file I provided, because it's logging a zillion errors while parsing it. 

So I guess my approach is just a different one: once huge amounts of errors start piling up, I believe it's good to have a way to bail out. 

[*] I silenced the audio to avoid copyright issues
