### ISSUE TITLE
Cannot read properties of undefined (reading 'docType')

### ISSUE THREAD

**Issue by thryfts** [Borewit/music-metadata#2017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

latest

### JavaScript module eco system

CommonJS modules (CJS), music-medata ≤ version 7

### Current Behavior

when trying to get metadata information from an audio buffer It works for a while and stops with error:  ```Cannot read properties of undefined (reading 'docType')```. The way i am getting the metadata is as follows: 

```
const mm = require('music-metadata');

const metadata = async (audioBuffer) => {
    try {
        // Parse metadata from the audio buffer
        const metadata = await mm.parseBuffer(audioBuffer, { mimeType: 'audio/webm' });

        // Extract relevant metadata properties
        const { format } = metadata;
        const { sampleRate, codec, numberOfChannels } = format;

        // Output the metadata
        console.log('Sample Rate:', sampleRate);
        console.log('Codec:', codec);
        console.log('Size:', parseFloat(audioBuffer.byteLength) / 1024, 'KB');
        console.log('Number of Channels:', numberOfChannels);

    } catch (error) {
        console.error('Error:', error.message);
    }
}
```

I get the audio buffer using javascript mediaRecorder library on client side and send the audio buffer for processing to backend. This is my client side code:

```
const constraints = { audio: { sampleRate: 16000, channelCount: 1 } };
        const stream = await navigator.mediaDevices.getUserMedia(constraints);
        mediaRecorder = new MediaRecorder(stream, { mimeType: 'audio/webm;codecs=opus' });

        // Start recording audio
        mediaRecorder.start(1000);

        // Function to handle data available
        const handleDataAvailable = (e) => {
            //this sends the buffer to the server 
            socket.emit(userId, e.data);
        };

        // Push audio chunks to buffer
        mediaRecorder.ondataavailable = handleDataAvailable;
```

### Expected Behavior

The first time i call the metadata function I get output: 

```
Sample Rate: 48000
Codec: OPUS
Size: 7.740234375 KB
Number of Channels: 1
```

Then all iterations after that return ```Error: Cannot read properties of undefined (reading 'docType')``` and ```Error: VINT value exceeding maximum size```

The expected behavior is to keep on getting metadata about the inputted buffer.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Looks like your audioBuffer contains invalid audio data after the initial call. Looks like an issue in your project.

**Comment by Borewit** [comment]
What you can try @thryfts, to remove explicit file type declaration: 

change this
```js
const metadata = await mm.parseBuffer(audioBuffer, { mimeType: 'audio/webm' });
```
into:
```js
const metadata = await mm.parseBuffer(audioBuffer);
 ```
 
 Alternatively, for debugging purposed, check the buffer with: [fyle-type, `filetypefrombufferbuffer()`](https://github.com/sindresorhus/file-type?tab=readme-ov-file#filetypefrombufferbuffer).
 
 I strongly suspect that you suffer from a synchronization issue, when pushing subsequential files to you backend. In other words, only you initial buffer is aligned with the audio file, the second and following buffer are not aligned.
