### ISSUE TITLE
FourCC error with aac files

### ISSUE THREAD

**Issue by noquierouser** [Borewit/music-metadata#204]
**Bug description**
An exception is raised by a couple of `.aac` files, one **untagged** and the other two **tagged** with mp3tag and VLC, related to `FourCC contains invalid characters`. All files play without issue in VLC.

FourCC error sets:

- `2e 7f fc 21` as invalid characters for untagged and VLC tagged files.
- `00 00 00 00` as invalid characters for mp3tag tagged file.

**Expected behavior**
No exception raised and metadata read and available.

**Audio file demonstrating the problem**
[TestFiles.zip](https://github.com/Borewit/music-metadata/files/3124702/TestFiles.zip)

**Comment by Borewit** [comment]
Thanks for reaching out @noquierouser.

The attached audio files [MPEG-2/AAC](https://mpeg.chiariglione.org/standards/mpeg-2/advanced-audio-coding).

The error is caused due to the fact these .aac files are currently interpreted as an MPEG-4. 
But apparently .aac files can either be MPEG-2 or MPEG-4:
> AAC has been standardized by ISO and IEC, as part of the MPEG-2 and MPEG-4 specifications.

_source: [wiki](https://en.wikipedia.org/wiki/Advanced_Audio_Coding)._

I guess I need to add MPEG-2/AAC support: #205

**Comment by noquierouser** [comment]
Interesting, I didn't know this was a thing. I always thought aac files were MPEG-4. Guess I was wrong.

Thanks for the quick response. :)

**Comment by Borewit** [comment]
> Interesting, I didn't know this was a thing. I always thought aac files were MPEG-4. Guess I was wrong.

I was not aware neither until today.

**Comment by Borewit** [comment]
It is extremely confusing. I intend to say that the atom based structure (as found in m4a, mp4) is the way an MPEG-4 audio container is structured. For MPEG-2 I expected the [Audio Layer I/II/III](https://www.mp3-tech.org/programmer/frame_header.html).
Well, in your files they use [ADTS](https://wiki.multimedia.cx/index.php?title=ADTS) which definitely not the atom structure, which looks like an extension of the [Audio Layer I/II/III](https://www.mp3-tech.org/programmer/frame_header.html).

This [MPEG Audio Layer I/II/III](https://www.mp3-tech.org/programmer/frame_header.html) audio container format is used by  MP3, still the most popular audio format around, but by far the most ugly container in my opinion.

In this ADTS header they re-assigned the MPEG 'version' (the so called MPEG _layer_ ) to be able point to MPEG-2, MPEG-4. 

Huh... MPEG-4 was the atom like structure, but this was the MPEG-2 like container, but the MPEG-2 like container is saying, which is now called ADTS, is saying it is MPEG-4... 😕

**Comment by noquierouser** [comment]
It sounds like there was an undocumented change of structure for MPEG-4 audio containers, or so I take from what you're telling. Or maybe an implementation off the standards that makes use of flags or something.

Maybe DASH related?

**Comment by Borewit** [comment]
So far it looks to be according to specs. Problem is there are so many standards around, and the MPEG/ISO documentation is not public accessible (at east not free of charge), which doesn't help.

But I think the [wiki page](https://en.wikipedia.org/wiki/Advanced_Audio_Coding) explains it well, AAC can be encoded in the following containers:

1. MPEG/3GPP container
  extensions: .m4a, .mp4, .3gp

1. Apple container
  extensions: .m4a, .m4b, .m4p, .m4r, .m4v
1. ADTS stream
  extensions: .aac

I believe the first 2 are similar. The third category, the ADTS, the one used in your samples, are basically a kind of retro fit on the MPEG frames as used in MP3's.

**Comment by Borewit** [comment]
Implemented in [v3.7.0](https://github.com/Borewit/music-metadata/releases/tag/v3.7.0)

**Comment by Borewit** [comment]
Related sindresorhus/file-type#208
