### ISSUE TITLE
Documenation: metadata.quality

### ISSUE THREAD

**Issue by eedefeed** [Borewit/music-metadata#2047]
### Has the question been asked before?

- [x] I have searched the existing issues

### Question

The purpose of `metadata.format`, `metadata.native` and `metadata.common` is mostly documented, but `metadata.quality` is not.

Searching through pull requests, it seems like it could be a list of errors the parser threw or something like that?

This issue is partly question, and part a request to update document.

(Thanks for your wonderful library)

**Comment by Borewit** [comment]
It's a kind of registration of odd things the parser came across. It can be used to indicate something is wrong with your audio file.
