### ISSUE TITLE
AAC parsed format is missing duration property

### ISSUE THREAD

**Issue by Vondry** [Borewit/music-metadata#207]
**Bug description**
Parsed aac file is missing duration property. Using `await parseFile(path, {duration: true});`

```
{ format:
   { tagTypes: [],
     lossless: false,
     dataformat: 'ADTS/MPEG-4',
     encoder: 'AAC',
     sampleRate: 44100,
     codecProfile: 'AAC LC',
     bitrate: 127821.59375,
     numberOfChannels: 2 },
  native: undefined,
  common:
   { track: { no: null, of: null }, disk: { no: null, of: null } } }
```

**Expected behavior**
I would expect to have duration property.

**Audio file demonstrating the problem**
(https://github.com/Borewit/music-metadata/files/3139850/NIK.TENDO.DECKY.-.Most.Wanted.x.YZOMANDIAS.OFF.VIZUAL.zip)

**Comment by Borewit** [comment]
@Vondry thanks for reporting this issue. Good to hear [the new AAC capability](https://github.com/Borewit/music-metadata/issues/205) is actually being used.

The duration of ADTS/AAC is a bit nasty to implement (even Foobar2000 did not calculate the duration of my sample files), so I skipped it deliberately, I was curious if someone would point it out.

If I implement it, the duration calculation will be expensive (will take a while to calculate), each and every ADTS frame has to be parsed. Therefor I will map the option to retrieve the duration to the `duration` flag.

**Comment by Vondry** [comment]
Hi, thanks for such a quick reply.

Let's assume small sized file, which has between 5-10Mb. I have no idea how much time it may take, but if it takes less than a second, it is OK in my case. Since I parse all files before the actual app starts.

Have a nice day. :)

**Comment by Borewit** [comment]
> but if it takes less than a second, it is OK in my case

I don't think so, probably a few seconds, maybe even more then 10 seconds...

Sorry, these MPEG/AFTS frames which require byte-hunting are terrible inefficient to parse in JavaScript. AAC is using very small frames which makes it even worse.

**Comment by Vondry** [comment]
This performance issue should be definitively highlighted in docs with some related topic, that is for sure. 

My app relies on the duration. So if no duration is present, i can not properly visualize progress of current track, so it makes `aac` more likely unusuable format. I would welcome duration property to be present anyway.

**Comment by Borewit** [comment]
Because this issue is open since a long time I will give an update.
To address this issue, to get the duration out of the ADTS file, I need to improve the MPEG/ADTS parser. I case of ADTS is still experience loosing sync somewhere half way the file.

So it's a lot of work, for file format which is not very common, with limited success (it will be slow) at most. Therefor it is not high on my priority list. Since there are not very much other issue, I may do fix it one day.
