### ISSUE TITLE
Monkey's Audio(APE) 不支持读取属性： bitrate

### ISSUE THREAD

**Issue by pointchange** [Borewit/music-metadata#2083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

"music-metadata": "^8.3.0",

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

使用node读取音频文件的信息，解析出来的信息 有类型为Monkey's Audio(APE) ，它不能读取属性 bitrate 。好像对APE的文件都有些限制，作者，标题基本信息没有正常，但同样的文件为何aimp应用能读出来属性bitrate属性。不太懂文件信息，请说明下。谢谢。
![1718444050373](https://github.com/Borewit/music-metadata/assets/67685400/8c841e7a-319e-4abd-b83f-99a447fd44b4)
![image](https://github.com/Borewit/music-metadata/assets/67685400/34a0c6eb-db61-4ee0-b7ac-8f69afc6f26f)

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Closing this one in favor of #2083
