### ISSUE TITLE
ape格式转成aac格式后，读取aac文件的duration属性读取不了。

### ISSUE THREAD

**Issue by pointchange** [Borewit/music-metadata#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

"music-metadata": "^8.3.0",

### JavaScript module eco system

None

### Current Behavior

有一个用ape转换成acc的需求，用ffmpeg转换格式后，用music-metadata读取文件信息，只有属性duration读取不了，其他信息和ape一样读取。music-metadata读取文件信息很快，用ffprobe就需要等待几秒，所以选择music-metadata，可music-metadata总是出乎意料。

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Issues should be written in English
