### ISSUE TITLE
APE format converted to ACC format，Cannot get attribute：duration

### ISSUE THREAD

**Issue by pointchange** [Borewit/music-metadata#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

"music-metadata": "^8.3.0",

### JavaScript module eco system

None

### Current Behavior

In a conversion audio project. I use “ffmpeg” APE format converted to ACC format, "music-metadata" cannot get attribute：“duration”. I don't know. Why is that. "music-metadata" is a problem dealing with APE format，Maybe the problem is there. I can not use "ffprobe" to conversion audio, it process slowly. On the contrary，I use "music-metadata" so fast.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Same issue as #1281
