### ISSUE TITLE
Enable Corepack and specify package manager version

### ISSUE THREAD

**Issue by minht11** [Borewit/music-metadata#2138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

This is not a public exposed feature request just an internal one.
I cloned the repo and installed yarn (because this repo uses it), but the issue was that my installed yarn was `4.3.1` and here it is probably  ^1 something. I am not sure which one to use and don't really have a way to know besides guessing.

To allow easier suggest contributors enable [corepack](https://yarnpkg.com/corepack) and specify which [package manager version](https://nodejs.org/api/packages.html#packagemanager) should be used inside package.json. This will not affect consumers of the library just the contributors.

---

My other suggestion would be to also switch to [pnpm](https://pnpm.io/) because in my opinion it seems bit better and more stable, but I digress.

**Comment by Borewit** [comment]
Hi @minht11 , thanks for pointing this out. Looks like I am a bit behind, I did an attempt to upgrade the yarn (#2051), and was not directly successful. Are you interested created a PR?

**Comment by minht11** [comment]
Sure. I am not that familiar with Yarn or Github Actions but I would be willing to try.
I saw in CI logs that the error is because of missing `chai` package.

Would you be interested in me migrating this repo from chai/mocha to native [node test runner](https://nodejs.org/api/test.html#test-runner)? Node 18/20 support it and API is almost identical so it should make yarn version migration easier (if you still want to use yarn wink pnpm).

**Comment by minht11** [comment]
Sure will open PR there, to _test_ things out there.

**Comment by Borewit** [comment]
Updated to Yarn Berry, using Corepack in #2051
