### ISSUE TITLE
parseFile() function doesn't exist

### ISSUE THREAD

**Issue by simonsanchezart** [Borewit/music-metadata#2144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

9.0.1

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

I'm using Tauri + React (ts).
I've installed the module, when I try to import the parseFile() function I get the error:
`Module '"music-metadata"' has no exported member 'parseFile'.ts(2305)`
There is also no `parseFile()` defined in `core.d.ts`

I'm importing it like this:
`import { parseFile } from "music-metadata";`
`"type": "module",` in `package.json`

### Expected Behavior

I could import `parseFile()` by doing `import { parseFile } from "music-metadata";` and then use `parseFile()`

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
As written in the README, [parseFile()](https://github.com/Borewit/music-metadata?tab=readme-ov-file#parsefile-function) is exclusively available for Node.js engines. So for sure this not available in React running in your browser. 
Which would be pointless as you do not have access to your file system in the browser.

For parsing a [File](https://developer.mozilla.org/en-US/docs/Web/API/File_API) in your browser, you can use the [parseBlob()](https://github.com/Borewit/music-metadata?tab=readme-ov-file#parseblob-function).

I have 0 experience with Tauri + React. If Tauri covers the backend, using some kind of Node.js engine, Tauri should be able to give you access to Node.js specific function. If it does not, you need to raise your issue there.

**Comment by joacoespinosa** [comment]
Hi @Borewit. I'm facing the exact same problem after updating from `7.14.0` to @latest

Mine is a Node.js app which was working with the mentioned version but breaks with `9.0.1`: `Module '"music-metadata"' has no exported member 'parseFile'`

Thoughts?

**Comment by Borewit** [comment]
> Hi @Borewit. I'm facing the exact same problem after updating from `7.14.0` to `@latest`
> 
> Mine is a Node.js app which was working with the mentioned version but breaks with `9.0.1`: `Module '"music-metadata"' has no exported member 'parseFile'`
> 
> Thoughts?

Hello @joacoespinosa, @latest is a moving target, I assume this is [v9.0.1](https://github.com/Borewit/music-metadata/releases/tag/v9.0.1)

I cannot reproduce your problem, I can only proof `parseFile()` is accessible in a Node.js engine:

<img width="812" alt="image" src="https://github.com/user-attachments/assets/2a48bb40-98c7-4eeb-9de1-4c780ae91934">


Reference: https://onecompiler.com/nodejs/42jznqj9u

**Comment by Borewit** [comment]
music-metadata version 8 & 9 are [Pure ESM packages](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), while version 7 is CommonJS.

To be able to use music-metadata version 8 or 9:
1. Run from an ESM based project (include `"type": "module"` in `package.json`)

To be able to import `parseFile()` :
1. Use Node.js
