### ISSUE TITLE
Special characters issue (Umlauts in particular)

### ISSUE THREAD

**Issue by uoziod** [Borewit/music-metadata#215]
**Bug description**
Extracted metadata contain wrong interpretation of umlauts. Thus, "Küso" turns to "KuL\bso"

**Expected behavior**
No specific transformation is applied.

**Audio file demonstrating the problem**
https://www.dropbox.com/s/pw9zoglw1fdicsp/umlaut-problem.flac.zip?dl=0

**Comment by Borewit** [comment]
Thanks for your feedback.
I tried to reproduce your issue, but it decodes just fine for me:
```TypeScript
describe("issue #215", () => {

  it('parse: umlaut-problem.flac', async () => {

    const filePath = path.join(issue_path, '#215', 'umlaut-problem.flac');

    const metadata = await mm.parseFile(filePath, {duration: false});
    const {format, common} = metadata;
    assert.strictEqual(format.dataformat, 'flac', 'format.dataformat');
    assert.deepEqual(format.tagTypes, ['vorbis'], 'format.tagTypes');
    assert.strictEqual(common.artist, 'Küso', 'common.artist'); // No problem here
  });

});
```
Maybe the escaping is done elsewhere?

**Comment by uoziod** [comment]
I'm thinking now if it might be somehow related to the fact that I use mm from ts-node.

**Comment by Borewit** [comment]
That should not matter, so do I while unit testing.

**Comment by Borewit** [comment]
I close this issue for now.
Please let me know if you experience any issues and feel free to write how you solved it.
