### ISSUE TITLE
readme error:  metadata.common.picture return that is array

### ISSUE THREAD

**Issue by pointchange** [Borewit/music-metadata#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### JavaScript module eco system

ECMAScript modules (ESM), music-medata ≥ version 8

### Current Behavior

  my data:  
       
[
    {
      format: 'image/jpeg',
      type: 'Media (e.g. label side of CD)',
      description: '',
      data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 48 00 48 00 00 ff db 00 43 00 02 01 01 01 01 01 02 01 01 01 02 02 02 02 02 04 03 02 02 02 02 05 04 04 03 ... 221375 more bytes>
    }
]

In your README.md, error: 
![微信图片_20240724172419](https://github.com/user-attachments/assets/477e1132-5043-4ed2-a362-e17f99a50a01)

In my project, I think it can be right :  `data:${picture[0].format};base64,${picture[0].data.toString('base64')}`

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
The examples are outdated. Since Buffer (`picture.data`) has been replaced with [`UInt8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) the `toString('base64')` no longer works.
