### ISSUE TITLE
`parseFile` not working with Bun runtime

### ISSUE THREAD

**Issue by DavNej** [Borewit/music-metadata#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

10.3.1

### Current Behavior

Using Bun as runtime, the console remains idle when `parseFile` is called.

Here is the following code. This code works well with `npm` and `tsx`.

Also, on line 1, I get the following error from typescript:
`Module '"music-metadata"' has no exported member 'parseFile'`

```typescript
import { parseFile } from 'music-metadata'
import { inspect } from 'util'

const filePath = '/path/to/file.mp3'

async function main() {
  try {
    const metadata = await parseFile(filePath)

    console.log(inspect(metadata, { showHidden: false, depth: null }))
  } catch (error) {
    console.error('Error parsing metadata:', error.message)
  }
}

await main()
```

### Expected Behavior

Should read properly the metadata of the given file

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by minht11** [comment]
Bun explicitly has a policy if it works in Node but not in Bun, it is a Bun bug, you should report it there.

**Comment by vdawg-git** [comment]
This works:
```Typescript
Bun.file(filePath)
    .arrayBuffer()
    .then((buffer) => new Uint8Array(buffer))
    .then((buffer) =>
	parseBuffer(buffer, { path: filePath }, { duration: true })
)
```
