### ISSUE TITLE
 Cannot read property 'parseBlob' of undefined

### ISSUE THREAD

**Issue by kimfucious** [Borewit/music-metadata#224]
I'm using [Dropzone.js](https://www.dropzonejs.com/) to upload files to an AWS S3 bucket.

This is possible with a PUT method using `acceptedFiles[0]`, which is the first file in the array that is output from a Dropzone drop event.  

Before I upload the file, I want to extract the meta data, so as to store it for later use.  I'd like to get the metadata *before* I upload the file to S3 and try to avoid re-fetching the file to get the metadata.

Using media-metadata-browser (I'm doing this on the client side), I'm trying to get the mp3 metadata, using:

```javascript
mm.parseBlob(acceptedFiles[0]).then(metadata => {
  console.log(metadata);
});
```
I know I'm probably doing something stupid, not fully understanding what I'm doing exactly, but the above code block throws the following error:

```console
Uncaught (in promise) TypeError: Cannot read property 'parseBlob' of undefined
```

What am I not getting here?

Any advice would be appreciated.

**Comment by kimfucious** [comment]
Hey, there.

Referring back to my "stupid" comment, I got this working by fixing the import statement in my js file.

**Incorrect**
```js
import mm from "music-metadata-browser";
```

**Correct**
```js
import * as mm from "music-metadata-browser";
```

**Comment by Borewit** [comment]
Good to hear it is working, please let me know if you experience any other issue.
