### ISSUE TITLE
Missing "numberOfSamples" on parsing audio file

### ISSUE THREAD

**Issue by julianpoemp** [Borewit/music-metadata#2273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

10.5.1

### Current Behavior

Audio sample (needs to be downloaded):
https://upload.poemp.net/index.php/s/Qc2qgKmcgUt55Iu/download

parseWebStream() with "audio/mpeg" returns audio information without "format.numberOfSamples" attribute.

```typescript
    try {
      // Assuming you have a ReadableStream of an audio file
      const response = await fetch('http://localhost:5321/media/zahlen.mp3');
      const webStream = response.body!;

      // Parse the metadata from the web stream
      console.log("METADATA:");
      const metadata = await parseWebStream(webStream, 'audio/mpeg');

      // Log the parsed metadata
      console.log(metadata);
    } catch (error) {
      console.error('Error parsing metadata:', error);
    }
```

This issue is related to parsing a part of the supported audio formats like mp3, m4a a.s.o. .

I had a look on the Parser codes and found out, that "numberOfSamples" is not set there.

### Expected Behavior

parseWebStream (and other parsing methods) should always return "format.numberOfSamples" attribute.

The numberOfSamples attribute is very important for calculating correct time positions in samples with the original aample rate. Knowing the maximum duration in samples is very important e.g. for annotation of audio files.

Please set "numberOfSamples" on every audio format.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
@julianpoemp I cannot guarantee that the `numberOfSamples` is available for every type of audio file, as music-metadata is not designed to parse the audio portion. But for the example provided, it could be done: #2282
