### ISSUE TITLE
The structure returned by the lyrics analysis is incorrect.

### ISSUE THREAD

**Issue by xushengfeng** [Borewit/music-metadata#2277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

10.5.1

### Current Behavior

`common.lyrics[0]` is `string`

I don't know if the lyrics format I'm using is correct :(

![image](https://github.com/user-attachments/assets/f2df7d49-5c22-4221-9f36-d9cd1de6930d)

![image](https://github.com/user-attachments/assets/da02a0f3-e747-43ef-a3d8-c0cc5f56ec83)

### Expected Behavior

Return the correct lyric format

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Seems that the lyrics mapping is, depending on the format type, not inconsistent with the type. Do you mind to send [me](https://github.com/Borewit) a sample @xushengfeng ?
