### ISSUE TITLE
How can I use music-metadata in electron-vite?

### ISSUE THREAD

**Issue by angelsf3** [Borewit/music-metadata#2290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### music-metadata version

10.6.0

### Current Behavior

Hi, I'm following the example for the node version for the parseFile function, but I'm getting this error: 'Error parsing metadata: musicMetadata.parseFile is not a function'.. 

I'm working with Electron+Vite using Node version: 22.9.0 in the Main process, so I use import { parseFile } from 'music-metadata'. 

When I go to the parseFile definition everything looks ok.

I've got the same error when I use parseStream.

### Expected Behavior

Get the file information.

### Attached audio sample?

- [X] I have provided sufficient information to reproduce the issue

**Comment by Borewit** [comment]
Good to hear it is working, may help others as well.

> I think that Electron + Vite works with ESM because I work with Typescript and I use import/export instead require/module.

Better to use the second option, the `import` using TypeScript:
```ts
// Importing music-metadata in a CommonJS project, written in TypeScript 
import { loadMusicMetadata } from 'music-metadata' ; 

(async () => {
  // Dynamically loads the ESM module in a CommonJS project
  const mm = await loadMusicMetadata();

  const metadata = await mm.parseFile('/path/to/your/file');
})();
```
 But that does not determine if you are using ESM or CommonJS. In a CommonJS project TypeScript will transpile your `import` to `require`.

But that the fact that `loadMusicMetadata` works, indicates that your project is CommonJS, or least that portion of the project.

**Comment by angelsf3** [comment]
Oh. I see, use TS is not mandatory to use ESM or CommonJS. Thanks a lot again and I hope this help other people with this issue too. Great library.
