### ISSUE TITLE
RangeError when parsing MPEG-4 file

### ISSUE THREAD

**Issue by b3u** [Borewit/music-metadata#231]
Error when parsing MPEG-4 file
```sh
RangeError [ERR_INVALID_OPT_VALUE]: The value "-8" is invalid for option "size"
    at Function.alloc (buffer.js:259)
    at FileTokenizer.readToken (AbstractTokenizer.js:10)
    at MP4Parser.js:130
    at Atom.readData (Atom.js:71)
    at Atom.readAtom (Atom.js:46)
    at async Atom.readAtoms (Atom.js:18)
```

I would attach, the file, but this file is purchased so I don't feel comfortable uploading it. I can send you metadata though, if that would help.

Note: When I open the file in kid3-qt, there is no metadata present

**Comment by Borewit** [comment]
I will need the file to investigate the issue. I can give you an e-mail address if you open a chat via Discord (check chat button) to send it to. Or leave you mail address somewhere.

I will not redistribute or publish your audio track, I will only use investigate the issue with the metadata on your behalf.

With your permission, if applicable, I may use the metadata into a unit tests. In that case I will cut out the audio content to prevent copyright infringement and save space.

You can remove data from your previous post btw.

**Comment by Borewit** [comment]
Feel free to re-open, if you provide sample data @b3u.
