### ISSUE TITLE
Key is not working properly in Typescript

### ISSUE THREAD

**Issue by ericnyc646** [Borewit/music-metadata#235]
**Bug description**
Using in an Angular 8 and Electron Project and when I try to refer to the key property, it tells me it does not exist in the interface.

**Expected behavior**
should allow me to access that property

**Audio file demonstrating the problem**

Fix for me was the following:
In the following file:  /lib/type.d.ts
In the ICommonTagsResult
Add:
    key?: string;

Tested and it works correctly.

thanks!

**Comment by Borewit** [comment]
Thanks for letting me know @ericnyc646, I will implement your suggested fix.

**Comment by Borewit** [comment]
Fixed in [v4.3.1](https://github.com/Borewit/music-metadata/releases/tag/v4.3.1)

**Comment by ericnyc646** [comment]
I have taken latest, confirmed the fix is working.

Thank you so much!!!
