### ISSUE TITLE
Error: TypeError: Cannot read property 'parseStream' of undefined

### ISSUE THREAD

**Issue by dnish** [Borewit/music-metadata#24]
Hey,
when upgrading to the latest version I get the following error message:

     Error: TypeError: Cannot read property 'parseStream' of undefined

Reverting to 0.6.3 solves the issue.

**Comment by Borewit** [comment]
@dnish: I would like to help you. II checked the distribution, it looks okay to me. 
Can you be more specific? Which version? Can you share some code demonstrating you issue?

Are you using [music-metadata module](https://www.npmjs.com/package/music-metadata) server side (Node.js) or client side (in the browser)?

Can you compare your code with the [example using `mm.parseStream()` on RunKit](https://runkit.com/borewit/parse-mp3-id3v2-4-tags-stream-with-music-metadata)?
