### ISSUE TITLE
Reading Lyrics header

### ISSUE THREAD

**Issue by jri** [Borewit/music-metadata#264]
**Feature Request**
At the moment music-metadata does not read a [Lyrics(3v2) header](http://id3.org/Lyrics3v2). As a consequence reading the APEv2 tags is apparently not possible if a file has both, a Lyrics header and APEv2 tags.

This is a follow up of https://github.com/Borewit/music-metadata/issues/257#issuecomment-531525694

(I want read the APEv2 tags, not actually the lyrics header.)

**Comment by Borewit** [comment]
Ability read APEv2 header in combination with Lyrics header: PR #271

**Comment by Borewit** [comment]
Ability to extract APEv2 header, which also has a [Lyrics3v2](http://id3.org/Lyrics3v2) header implemented in [v4.8.0](https://github.com/Borewit/music-metadata/releases/tag/v4.8.0).

**Comment by Borewit** [comment]
There is some code present for [Lyrics3v2](http://id3.org/Lyrics3v2), if better support is required, I need sample files.
