### ISSUE TITLE
ParseFile halts execution with no error

### ISSUE THREAD

**Issue by jorgev259** [Borewit/music-metadata#268]
**Bug description**
when using parseFile on Ubuntu 18.06 the function doesnt return anything and halts execution without throwing an error.

`>console.log(path.join(config.musicPath, pathN))
          let metadata = await mm.parseFile(path.join(config.musicPath, pathN), {duration:true})`

this code works on windows, but not on Ubuntu. The console.log works but after the execution doesnt do anything.

**Comment by Borewit** [comment]
music-metadata is continues tested on Linux & Windows, I am surprised you encounter different behavior.

What is the output of `console.log(path.join(config.musicPath, pathN))`?
Can you provide me the file `path.join(config.musicPath, pathN)` is pointing to @jorgev259?

What if you change to `{duration:false}`?

You can get more debug info if you set `DEBUG=*` in your environment.

**Comment by jorgev259** [comment]
Disregard, it wasnt a problem with the library. Unrelated issue

**Comment by jorgev259** [comment]
```
console.log('Loaded file.')
mm.parseFile(path.join(config.musicPath, pathN))
      .then(async metadata => {
            console.log('loaded metadata')     
          })
          .catch(err => {
            console.error(err)
          })
```
I retract my past statement, it still freezes. path.join returns "/media/dropbox/route/to/.mp3"

**Comment by jorgev259** [comment]
[01 Vampire Killer ~Akumajo Dracula (Family Computer Disk System)~.zip](https://github.com/Borewit/music-metadata/files/3650882/01.Vampire.Killer.Akumajo.Dracula.Family.Computer.Disk.System.zip)
one of the files used (its a bulk operation)

**Comment by Borewit** [comment]
> its a bulk operation

Are you sure you are not parsing all audio files in parallel?
That would cause a memory usage and a disk i/o collusion which may freeze your application.

See: https://github.com/Borewit/music-metadata#frequently-asked-questions.

**Comment by Borewit** [comment]
Please see my comments in jorgev259/socradio#1
