### ISSUE TITLE
Support rating tag

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#27]
Related issue: https://github.com/leetreveil/musicmetadata/issues/137

Parse rating tags and map it to a common tag.
In line with MusicBrainz Picard, normalize the common tag to a scale from 0 to 5.0:

```Python
            elif frameid == 'POPM':
                # Rating in ID3 ranges from 0 to 255, normalize this to the range 0 to 5
                if frame.email == config.setting['rating_user_email']:
                    rating = string_(int(round(frame.rating / 255.0 * (config.setting['rating_steps'] - 1))))
                    metadata.add('~rating', rating)
```
_source: https://github.com/metabrainz/picard/blob/master/picard/formats/id3.py_

**Comment by Borewit** [comment]
If I implement this, are you planning to use this @KeitIG?

**Comment by LudekStoklasa** [comment]
I second that, I've just found that POPM isn't read, e.g. for [this](https://www.dropbox.com/s/xywzupo5jyt2gcx/02-Yeahs-It%27s%20Blitz%21%202.mp3?dl=0) 3 star file the "3 stars" rating is shown in MediaMonkey, Windows Media Player, Foobar, but it cannot be retrieved by music-metadata, I found it while enhancing metadata reading in [this commit](https://github.com/mediamonkeyserver/mms/commit/b914aa6f5500b571a617ec6b8a04b1d014f1ba98) , for MP4 and Vorbis the rating is read fine.

**Comment by jirihajek** [comment]
Since mapping of the scales (0-5, 0-255) isn't fully standardized, I'd rather suggest to provide the 'raw' value from ID3v2 (i.e. 0-255 range). Alternatively, provide both, i.e. 'rating' and 'rating_raw'?

**Comment by Borewit** [comment]
Thanks for your feedback gents.
Let's enable rating support.

**Comment by Borewit** [comment]
Added in [v2.0.0](https://github.com/Borewit/music-metadata/releases/tag/v2.0.0)

**Comment by LudekStoklasa** [comment]
Thanks for quick adding!!  Just testing 2.0.0 and I can confirm that I am seeing both rating and native rating ( native['ID3v2.3']['POPM'] ).

Thanks again!

**Comment by Borewit** [comment]
Thanks for letting me know! 
No problem, it was a pleasure.
