### ISSUE TITLE
Guessed MIME-type not supported: image/jpeg

### ISSUE THREAD

**Issue by ericnyc646** [Borewit/music-metadata#281]
**Bug description**
When I try to parse a file that has a jpeg image, it fails with the message "Guessed MIME-type not supported: image/jpeg".  This is even before I look at the picture.

**Expected behavior**
Handle JPEG or a way around this bug.

**Audio file demonstrating the problem**
[1-05 Born This Way.zip](https://github.com/Borewit/music-metadata/files/3718741/1-05.Born.This.Way.zip)

**Comment by Borewit** [comment]
Thanks for reaching out @ericnyc646.

The following unit test using the provided file types pass just fine:
```ts
describe('281', () => {

  it('parse file the normal way', async () => {

    const filePath = path.join(issue_path, '#281', '1-05 Born This Way.mp3');

    const metadata = await mm.parseFile(filePath);
    const {format} = metadata;

    assert.strictEqual(format.container, 'MPEG');
    assert.approximately(format.duration, 267.57, 1/200, 'format.duration');
    assert.deepEqual(format.tagTypes, ['ID3v2.2']);

    console.log(JSON.stringify(format, null, 2))
  });

  it('Enforcing auto detect file type', async () => {

    const filePath = path.join(issue_path, '#281', '1-05 Born This Way.mp3');

    const buf = fs.readFileSync(filePath);

    // Because we parse from a buffer, music-metadata has initially no idea what the audio type is
    const metadata = await mm.parseBuffer(buf);
    const {format} = metadata;

    assert.strictEqual(format.container, 'MPEG');
    assert.approximately(format.duration, 267.57, 1/200, 'format.duration');
    assert.deepEqual(format.tagTypes, ['ID3v2.2']);

    console.log(JSON.stringify(format, null, 2))
  });
});
```
Also dragging and dropping the file on [audio-tag-analyzer.netlify.com](https://audio-tag-analyzer.netlify.com/).

Can you give me more detail @ericnyc646? Which parser method are you using? Are you running in Node?

**Comment by ericnyc646** [comment]
Issue was mine.  My sincerest apologies.

Working great on:  Electron + Angular 8.2

**Comment by Borewit** [comment]
No problem at all, please give me a ping if you released your app to the public.

**Comment by ericnyc646** [comment]
Will do.
