### ISSUE TITLE
Illegal ID3v2-tag-length throws 'Index out of range" exception

### ISSUE THREAD

**Issue by Newan** [Borewit/music-metadata#31]
On parsing my mp3 folder some files have incompatible tags:

`Parse ERROR: last file: Index out of range`

Part of: #26

**Comment by Borewit** [comment]
Should be fixed in [v0.7.17](https://github.com/Borewit/music-metadata/releases/tag/v0.7.17)

**Comment by Newan** [comment]
fixed

**Comment by Borewit** [comment]
Cool! You're welcome.
