### ISSUE TITLE
Incorrect metadata for mp3 file

### ISSUE THREAD

**Issue by davakh** [Borewit/music-metadata#347]
I've got incorrect data while using `parseBlob` function with `.mp3` extension audio file. 

Input audiofile: 
[issue_incorrect_mp2_metadata_recognition.zip](https://github.com/Borewit/music-metadata-browser/files/3938603/issue_incorrect_mp2_metadata_recognition.zip)

Steps to reproduce:
1. upload `mp3` file from `zip`
2. use function `parseBlob` or `parseFile` (from `music-metadata`) for file

Output:
```
codec: "MP2"
numberOfChannels: 2
sampleRate: 16000
```

Expected: (as f.e. `get-metadata.com` resolves it)
```
codec: "MP3"
numberOfChannels: 1
SampleRate: 8000
```

71 warnings while parsing file: 
- 64 warnings - `"Parse error: Cannot determine bit-rate"` 
- 5 warnings  - `"Parse error: Cannot read property 'toString' of null"`, 
- 2 warnings - `"Parse error: Cannot determine sampling-rate"`

Issue repeats in library `music-metadata` too. 
Hope, you may help clarify things for me or find a fix for this.

**Comment by Borewit** [comment]
Thank you for reaching out @davakh. 

I see what you mean:

![image](https://user-images.githubusercontent.com/23255260/70461764-aeabfb80-1ab9-11ea-806a-498959f75b17.png)

I will investigate.

**Comment by Borewit** [comment]
I will also include the MPEG version number in `metadata.format.codec`: #349

**Comment by Borewit** [comment]
Bug is occurring with MPEG files using MPEG version 2.5 decoding.

**Comment by Borewit** [comment]
Should be fixed in:
1. [music-metadata v5.1.0](https://github.com/Borewit/music-metadata/releases/tag/v5.1.0)
2. [music-metadata-browser v1.9.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v1.9.0)

**Comment by davakh** [comment]
How is that possible to react so fast on issues? Thank you for your job ❤️ , it fixed.
