### ISSUE TITLE
Cannot read property 'sampleRate' of undefined

### ISSUE THREAD

**Issue by ozelot379** [Borewit/music-metadata#386]
**Bug description**
On some iTunes purchased movies (m4v), I get `Cannot read property 'sampleRate' of undefined`

I tried to fix it in https://github.com/Borewit/music-metadata/pull/383

**Expected behavior**
I dont' know, whether it's possible to parse drm protected tracks, but I think at least the tags and the duration should work.

**Audio file demonstrating the problem**
Not possible due copyright

**Comment by Borewit** [comment]
Fixed in [v5.4.3](https://github.com/Borewit/music-metadata/releases/tag/v5.4.3), via #383
