### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 508. Received 1954034623

### ISSUE THREAD

**Issue by ozelot379** [Borewit/music-metadata#388]
**Bug description**
On some iTunes purchased movies (m4v), I get `The value of "offset" is out of range. It must be >= 0 and <= 508. Received 1954034623` or `Attempt to access memory outside buffer bounds`

I can patch/fix this by try-catch all `get` methods in https://github.com/Borewit/token-types/blob/master/lib/index.ts like
```js
get(buf: Buffer, off: number): number 
  try {
    return ...;
  } catch(ex) {
    return 0;
  }
}
```

But how to fix this really, I don't know

**Expected behavior**
I dont' know, whether it's possible to parse drm protected tracks, but I think at least the tags and the duration should work.

**Audio file demonstrating the problem**
Not possible due copyright

**Comment by ozelot379** [comment]
isn't necessary to fix this bug - I can skip these few files for my use case, if an exception is occured

**Comment by Borewit** [comment]
> isn't necessary to fix this bug

I think it is important, I would like to provide a component one can rely on. 

@ozelot379 can you please check if this error still occurs with version [v6.3.4](https://github.com/Borewit/music-metadata/releases/tag/v6.3.4)?

I have not been able to reproduce it, neither with the samples of @qcasey.

**Comment by ozelot379** [comment]
yes, this bug seems to fixed and not occur anymore
