### ISSUE TITLE
UnhandledPromiseRejectionWarning: AssertionError

### ISSUE THREAD

**Issue by thoni56** [Borewit/music-metadata#398]
**Bug description**
Getting `UnhandledPromiseRejectionWarning: AssertionError` when reading attached file. Also try/catch around the `parseFile()` call does not catch this so the application gets in a state of flux.

This is my code:

```
    try {
      console.log(file);
      mm.parseFile(file)
        .catch(e => {
          console.log("Could not read metadata from ", file);
        })
    } catch (e) {
      console.log("Could not read metadata from ", file);
    }
```

But I still get the RejectionWarning instead of my console logs.

**Expected behavior**
Meta data should be read, and in failure of doing that there should be some method or callback to catch this case.

**Audio file demonstrating the problem**

[problem1.mp3.zip](https://github.com/Borewit/music-metadata/files/4030157/problem1.mp3.zip)

**Comment by thoni56** [comment]
For my own use I can fix the files, but I can't expect users to have the level of knowledge, or interest...

**Comment by thoni56** [comment]
Here's the complete error message:

```
(node:7426) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: pictureType should be defined
    at Function.fixPictureMimeType (.../node_modules/music-metadata/lib/common/GenericTagMapper.js:28:16)
    at MetadataCollector.postMap (.../node_modules/music-metadata/lib/common/MetadataCollector.js:100:71)
    at MetadataCollector.toCommon (.../node_modules/music-metadata/lib/common/MetadataCollector.js:179:18)
    at MetadataCollector.addTag (.../node_modules/music-metadata/lib/common/MetadataCollector.js:64:14)
    at ID3v2Parser.addTag (.../node_modules/music-metadata/lib/id3v2/ID3v2Parser.js:161:23)
    at ID3v2Parser.parseId3Data (.../node_modules/music-metadata/lib/id3v2/ID3v2Parser.js:156:22)
(node:7426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Borewit** [comment]
You are getting an `UnhandledPromiseRejectionWarning` because you are not handling the promise.

A working example with the same file using `async`/`await`
```js
const mm = require('music-metadata');

(async () => {
  try {
    const {format} = await mm.parseFile('C:\\tmp\\problem1.mp3');
    console.log(`Looks like a valid: ${format.container} file.`);
  } catch (error) {
    console.log(`Oops, something went wrong parsing my file: ${error.message}`);
  }
})();
// => Oops, something went wrong parsing my file: pictureType should be defined
```

Or using `then`

```js
const mm = require('music-metadata');

mm.parseFile('C:\\tmp\\problem1.mp3').then(metadata => {
  console.log(`Looks like a valid: ${metadata.format.container} file.`);
}, error => {
  console.log(`Oops, something went wrong parsing my file: ${error.message}`);
});
```
Not directly related to your issue, only to your sample code, but be very careful with the `.catch`!!!!
Note that I took a valid `.mp3` this time:

```js
mm.parseFile('C:\\tmp\\no-problem.mp3').then(metadata => {
  console.log(`Looks like a valid: ${metadata.format.container} file.`);
  throw new Error('Using .catch, you will also catch me');
}).catch(error => {
  console.log(`This error may not be be parsing issue at all: ${error.message}`);
});
// => Looks like a valid: MPEG file.
// => Oops, something went wrong parsing my file: Using .catch, you will also catch me

**Comment by Borewit** [comment]
In your code fragment is in inside function, you probably need to do something like

```js 
return mm.parseFile(file).... // Note the return
```

**Comment by thoni56** [comment]
Thanks for the pointer about `.catch`, not fully into promises yet. And actually, in my app I had the simple `try ... await ... catch` pattern, so that problem was just a side effect of not following the normal flow.

So I'm okay with closing this now that you have #399.

**Comment by Borewit** [comment]
It is tricky @thoni56. I have been struggling with same issues myself. It takes a lot practice to master it.

The `try ... await ... catch` makes is a bit easier, but you have to be very aware that underlying mechanisms are promises.

I just realized I gave you the [wrong suggestion](https://github.com/Borewit/music-metadata/issues/398#issuecomment-571736368). If you use try catch, you should use await inside. Otherwise it will exit the catch scope before the promise is resolved or rejected.

**Comment by Borewit** [comment]
Tag was empty after all, no longer an error but a warning since version [v6.1.1](https://github.com/Borewit/music-metadata/releases/tag/v6.1.1)
