### ISSUE TITLE
Matroska segement infos and attachments

### ISSUE THREAD

**Issue by ozelot379** [Borewit/music-metadata#407]
**Feature Request**
Is it possible to map the matroska segement info (title and date) to tags?

And image attachments to picture tags?

You can set it with mkvtoolnix
![screenshot](https://user-images.githubusercontent.com/16632028/72183879-6309ac00-33ef-11ea-80a1-e988618f8f37.png)

**Comment by Borewit** [comment]
Maybe the segment information to chapters, what do you think?

https://github.com/Borewit/music-metadata/blob/3be523905e867d5a743ebcb795443266c8a26639/lib/type.ts#L394

Tracks are planned to be exposed via #357, PR:  #394.

**Comment by Borewit** [comment]
> The Segment Information section contains basic information relating to the whole file. This includes the title for the file, a unique ID so that the file can be identified around the world, and if it is part of a series of files, the ID of the next file.

Ref: https://www.matroska.org/technical/diagram/index.html

**Comment by Borewit** [comment]
Implemented in [v6.2.0](https://github.com/Borewit/music-metadata/releases/tag/v6.2.0)

**Comment by ozelot379** [comment]
thx
