### ISSUE TITLE
mp3 (ADTS) causes infinite loop if duration is requested

### ISSUE THREAD

**Issue by snx888** [Borewit/music-metadata#430]
**Bug description**
I'm parsing a mp3 file (ADTS/MPEG-2, AAC SSR) unsing the option {duration:true}.
The call of parseFile does not return, causing an infinite loop instead.

**Expected behavior**
The function/method parseFile should return successfully or throwing an error.

**Audio file demonstrating the problem**
[test.zip](https://github.com/Borewit/music-metadata/files/4142641/test.zip)

**First Findings**
File lib/mpeg/MpegParser.js 
Function parseAdts
The frameCount is growing infinite, withut the option duration:true everything works fine because we'll skip after the 3rd frame.

**Comment by Borewit** [comment]
Issue confirmed

**Comment by Borewit** [comment]
This MP3-file is prefixed with a corrupt frame, which identifies as an ADTS frame.
Similar patters as the [`Bob Acri - Sleep Away.mp3`](https://github.com/Borewit/music-metadata/blob/master/test/samples/mp3/Sleep%20Away.mp3) shipped with Windows 7.

A trick to make an MP3 file look like an AAC?

**Comment by Borewit** [comment]
Fixed in [v6.3.2](https://github.com/Borewit/music-metadata/releases/tag/v6.3.2)
