### ISSUE TITLE
Best way to parse live-stream?

### ISSUE THREAD

**Issue by KingOfCaves** [Borewit/music-metadata#437]
Is it possible to use this in a situation where you have a constant feed from a stream and just parse the metadata from it indefinitely? I tried searching each chunk ( using stream.on('data') ) and parsing based on whether or not each chunk had certain charachteristics, but that only worked half of the time and failed other times ( using mm.parseBuffer on a concatenated buffer array would sometimes give a "parsePage of undefined" error despite it firing from a metadata event ). When you use an observer with mm.parseStream to dump what it captures to console, it gets the metadata from the stream immediately and starts spamming it into console until the next metadata event fires. Is there a way to get this functionality where it captures the first time it's able to parse the metadata, and then update every time there an update thereafter?

**Comment by Borewit** [comment]
> Is it possible to use this in a situation where you have a constant feed from a stream and just parse the metadata from it indefinitely?

It is designed to parse streams, but it does expect in a single song. If can show me what you run into, we might get [music-metadata](https://github.com/Borewit/music-metadata) better suitable for this purpose.

The weak point maybe the concept of a new track within a stream.

> When you use an observer with mm.parseStream to dump what it captures to console, it gets the metadata from the stream immediately.

` observer` and `mm.parseStream` is the way to go indeed. ` Strictly speaking, it does not generate an event immediately, but it will as soon as new metadata is available.

> ...and starts spamming it into console until the next metadata event fires

You decide what you want to write to the console. But it tells you what metadata is read, in addition to that it gives you access to the metadata-model with all data collected so far, as well to the part which has changed. This function is used to progressively build up track information in combination with low bandwidth, or other cases where the track is partial available. For bits of information it may actually not fire an event, therefor the metadata-model is essential.

> Is there a way to get this functionality where it captures the first time it's able to parse the metadata, and then update every time there an update thereafter?

That is exactly what it does. To prevent you have to combine all tags, to a consolidated track metadata information object, it does this for you as well.

**Comment by KingOfCaves** [comment]
Thanks for the response! Using the observer to get the information after all the necessary tags are available is definitely the way to go. I think I have something that should work continuously over time. I was probably overthinking it before. What I did was make an async function that returns the parseStream promise and once the parseStream promise resolves it just calls the async function again, looping the process. I can't believe it was so simple. Thanks again!

**Comment by Borewit** [comment]
I forget about the fact that with a live-stream, the parser may return. It may return at the end of the file, somewhere in the beginning. it depends of the format, and some cases of the flags provided and content.

What format is the live stream? Is live stream publicly available? Did you publish your code somewhere?

Maybe we can improve the behavior reading live streams with a flag, e.g.:

```js
parseStream(stream, {keepReading: true, observer: update => {
    // process metadata
  }});
```

**Comment by Borewit** [comment]
Feel free to re-open.

**Comment by case** [comment]
@KingOfCaves any chance you could post some sample code in a gist, for how you got this working? Thanks!

**Comment by KingOfCaves** [comment]
> @KingOfCaves any chance you could post some sample code in a gist, for how you got this working? Thanks!

Sure thing! My code looks something like this. I have an object that stores the metadata that it gets from the icecast server which is then served and updated with socketio. Not sure if this is the best way to do it but it works really well for me.

The function does a few checks at the start to make sure that all of the data is fully captured or updated.

```
let currentMetadata = {};

http.get(URL, (src) => {
	src.on('end', () => console.log('stream ended...'));
	src.on('error', (error) => console.log('stream crashed...\n', error));

	const siftThrough = async () => {
		return await mm
			.parseStream(src, 'audio/ogg', {
				skipPostHeaders: true,
				skipCovers: true,
				observer: (update) => {
					const { artist, title, album } = update.metadata.common;
					const allTags = artist && title && album;
					const changed =
						currentMetadata.artist !== artist || currentMetadata.album !== album || currentMetadata.title !== title;

					if (allTags && changed) {
						// COVERFIND FUNCTION HERE
						console.log(coverFind);
						const cover = `/images/covers/${path.basename(coverFind)}`;
						console.log(cover);
						currentMetadata = {
							title,
							album,
							artist,
							cover,
						};
						io.emit('metadataUpdate', currentMetadata);
						console.log(currentMetadata);
					}
				},
			})
			.then(() => siftThrough())
			.catch((error) => console.log(error));
	};
	siftThrough();
});
```

**Comment by case** [comment]
@KingOfCaves thank you, much appreciated!

**Comment by Borewit** [comment]
Some suggestions:
1. Use while loop instead of recursion, you risk running out of memory after many recusrions
1. Use await with try catch pattern
1. Make sure you exit when there is stream error. Maybe you should figure out what kind of error was thrown as well.

```js
let currentMetadata = {};

http.get(URL, async src => {
  let keepParsing = true;

  src.on('end', () => {
    keepParsing = false;
    console.log('stream ended...');
  });

  src.on('error', error => {
    keepParsing = false;
    console.log('stream crashed...\n', error);
  });

  while (keepParsing) {
    try {
      await mm.parseStream(src, 'audio/ogg', {
        skipPostHeaders: true,
        skipCovers: true,
        observer: update => {
          const {artist, title, album} = update.metadata.common;
          const allTags = artist && title && album;
          const changed =
            currentMetadata.artist !== artist || currentMetadata.album !== album || currentMetadata.title !== title;

          if (allTags && changed) {
            // COVERFIND FUNCTION HERE
            console.log(coverFind);
            const cover = `/images/covers/${path.basename(coverFind)}`;
            console.log(cover);
            currentMetadata = {
              title,
              album,
              artist,
              cover,
            };
            io.emit('metadataUpdate', currentMetadata);
            console.log(currentMetadata);
          }
        }
      });
    } catch (error) {
      console.log(error);
    }
  }
});
```

**Comment by KingOfCaves** [comment]
@Borewit 
It seriously never occurred to me that I could pass an async fn to the get request. For some reason I thought it had to be synchronous. I never had problems with memory with the other solution ( at least not yet ), but I still had my worries as to whether there were better solutions for performance. 

Thanks for the tips!
