### ISSUE TITLE
I keep getting "TypeError: fs.stat is not a function"

### ISSUE THREAD

**Issue by MohammedZ666** [Borewit/music-metadata#460]
I am trying to parse metadata from a file.  

    async parseFiles(audioFiles) {
        for (const file of audioFiles) {
            //this line catches the above mentioned error
            const metadata = await mm.parseFile(file);
      }

      // this is the method calling the parseFiles...
      upload = async () => {
        var fileInput = document.getElementById("fileItem");
        var files = fileInput.files;
        this.parseFiles(files);
       }
       // the render function...
      render() {
        return (
            <div style={{ margin: 'auto', width: '60%' }}>

                <input id="fileItem" type="file" multiple />
                <button onClick={this.upload} >Upload</button>
                <LinearProgress variant="determinate" value={this.state.progress} color="secondary" />

            </div>
        );
      }

**Comment by Borewit** [comment]
Hi @MohammedZ666,

[music-metadata](https://github.com/Borewit/music-metadata) is designed for Node.js.
`mm.parseFile()` is expecting a file path as an argument. That doesn't fly in your browser.

In your web browser, you should use [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) instead.
Try [parseBlob()](https://github.com/Borewit/music-metadata-browser#parseblob-function). Note that the browser [File object](https://developer.mozilla.org/en-US/docs/Web/API/File) is derived from the [Blob object](https://developer.mozilla.org/en-US/docs/Web/API/Blob)

**Comment by MohammedZ666** [comment]
Ok, will do. Thank you very much.

**Comment by MalarkodiB** [comment]
Hi,

I am getting the same sort of error at the below case: > fs[fsStatType] is not a function


'use strict';
const {promisify} = require('util');
const fs = require('fs');

async function isType(fsStatType, statsMethodName, filePath) {
	if (typeof filePath !== 'string') {
		throw new TypeError(`Expected a string, got ${typeof filePath}`);
	}

	try {
		const stats = await promisify(fs[fsStatType])(filePath);
		return stats[statsMethodName]();
	} catch (error) {
		if (error.code === 'ENOENT') {
			return false;
		}

		throw error;
	}
}

function isTypeSync(fsStatType, statsMethodName, filePath) {
	if (typeof filePath !== 'string') {
		throw new TypeError(`Expected a string, got ${typeof filePath}`);
	}

	try {
		return fs[fsStatType](filePath)[statsMethodName]();
	} catch (error) {
		if (error.code === 'ENOENT') {
			return false;
		}

		throw error;
	}
}

exports.isFile = isType.bind(null, 'stat', 'isFile');
exports.isDirectory = isType.bind(null, 'stat', 'isDirectory');
exports.isSymlink = isType.bind(null, 'lstat', 'isSymbolicLink');
exports.isFileSync = isTypeSync.bind(null, 'statSync', 'isFile');
exports.isDirectorySync = isTypeSync.bind(null, 'statSync', 'isDirectory');
exports.isSymlinkSync = isTypeSync.bind(null, 'lstatSync', 'isSymbolicLink');

**Comment by Borewit** [comment]
In Node.js?
