### ISSUE TITLE
Support for opus and question about cover art

### ISSUE THREAD

**Issue by Extarys** [Borewit/music-metadata#47]
This is AWESOME, it's almost an all in one.

Would it be possible in the future to add support for opus file? :)

Also, can I read cover art from FLAC files? Some of my files have this - no idea how they did it.

Thanks 👍

**Comment by Borewit** [comment]
Good to hear you like it.

Reading cover art is supported from FLAC/APE headers is supported.

Let me investigate what it takes to implement Opus audio files.

**Comment by Extarys** [comment]
Ok thanks for confirming covert art support for FLAC files.

Take your time hehe I'm still in the early stage of my little project.

On a side note, how hard would it be to implement writing tags to file? 😸 Or do you know any good extension for that?

**Comment by Borewit** [comment]
Opus is doable, I need to extend the ogg parser to enable that.

There is an issue #10 regarding for writing. It would be fantastic to offer this, but it is is indeed a lot of work. I only know [mutagen](https://github.com/quodlibet/mutagen) which is written Python.

**Comment by Extarys** [comment]
Awesome I'll give mutagen a try.
Thanks for looking into opus !

**Comment by Borewit** [comment]
Follow up in pull request #49.

**Comment by Borewit** [comment]
Implemented in [v0.9.0](https://github.com/Borewit/music-metadata/releases/tag/v0.9.0)
