### ISSUE TITLE
No metadata found in files with metadata

### ISSUE THREAD

**Issue by elizavetd** [Borewit/music-metadata#48]
I have two files that have music tags, but they are not seen by this parser and object is returned with nulls in properties while thousands of other files do not have such problem. I can't figure out what is wrong with these two songs, maybe I'm missing something.

[Songs.zip](https://github.com/Borewit/music-metadata/files/1685745/Songs.zip)

**Comment by Borewit** [comment]
_Moly-02-Ho Anao.mp3_ has 2 different ID3 tag blocks:
1. ID3v2.3
2. ID3v2.4

which you can find in the returned result:

``` javascript
"native": {
        "ID3v2.3": [
            {
                "id": "PRIV",
                "value": {
                    "owner_identifier": "WM/MediaClassSecondaryID",
                    "data": {
                        "type": "Buffer",
                        "data": [...]
                    }
                }
            },
            {
                "id": "PRIV",
                "value": {
                    "owner_identifier": "WM/MediaClassPrimaryID",
                    "data": {
                        "type": "Buffer",
                        "data":[...]
                    }
                }
            },
            {
                "id": "TRCK",
                "value": "2"
            },
            {
                "id": "TALB",
                "value": "No One Will Know"
            },
            {
                "id": "TYER",
                "value": "1999"
            },
            {
                "id": "TPE2",
                "value": "Moly"
            },
            {
                "id": "TIT2",
                "value": "Ho Anao"
            },
            {
                "id": "TCON",
                "value": "Cover"
            },
            {
                "id": "TPE1",
                "value": "Moly"
            }
        ],
        "ID3v2.4": [
            {
                "id": "TENC",
                "value": "SUPER(C)"
            }
        ]`
```
However the ID3v2.4 block does not contain much information as you can see.
Why is the common mapping empty ? 
Because only one tag block is used to map to the common mappings. The rational behind this is to avoid inconsistent data. Which one used? The ID3v2.4 has priority over the older ID3v2.3 tag block. In other words, the assumption is made that the ID3v2.3 block is only there for backward compatibility.

 _UFO Yepha & Lis Sorensen-01-Storm.mp3_ the same story. It has an ID3v1.1 and an ID3v2.4 tag block. The empty ID3v2.4 overules the ID3v1.1 tags.

**Comment by elizavetd** [comment]
@Borewit 
Okay, got it, thank you for explaining this to me.
But is there any way to bypass this problem and get ID3 tag that is not empty? Unfortunately, avoiding inconsistent data is not a solution in my project.

**Comment by Borewit** [comment]
> But is there any way to bypass this problem and get ID3 tag that is not empty?

In fact the ID3v2.4 block is not empty, so skipping empty blocks is not going to solve this issue.
You do have access to all _native_ metadata blocks, so you have the possibility to combine the data. Good programmers are laze, so my best guess is you are


> Unfortunately, avoiding inconsistent data is not a solution in my project.

Lets assume we have the following ID3v1.1 meta-data block: 
`artist: "Leonard Cohan", title "Suzanne"` 
in combination with an ID3v2.4 meta-data block:
`'title: "I am a virgin"`.
 
Would it be reasoble to say in the common output that _Leonard Cohan_ sung _I am a virgin_?

**Comment by elizavetd** [comment]
Yeah, I've already figured it out but forgot to write it here, sorry
Thanks for your help =)

**Comment by Borewit** [comment]
You're welcome.

**Comment by Borewit** [comment]
And good luck with your project!
