### ISSUE TITLE
Await mm.parseFile(path) indefinite

### ISSUE THREAD

**Issue by svenseitan** [Borewit/music-metadata#486]
Hello. I make music software and I have a problem that is difficult to identify (for me at least).

I put in a table (pathsAudio) all the paths of the audio files present in a folder. This works.

Next, I want to convert each path in the array to an object that contains the metadata for the audio files.

Here is the simplified code:

```
async function extendAudioFiles (files) {
	const filesExt = []
	let i = files.length
	for (const f of files) {
		const m = await mm.parseFile(f)
		const mc = m.common
		const data = {
			path: f,
			title: mc.title
		}
		filesExt.push(data)
		console.log(i--)
	}
	return filesExt
}
...
extendAudioFiles(pathsAudio).then(res => {
	console.log(res)
})
```

Most of the time it works fine, but sometimes (about one in 10) "await mm.parseFile (f)" is waiting indefinitely. No error is displayed. And it's never on the same path. This only happened on my computer, via an Electron application. The pathsAudio array contains 5000 paths.

I do not know what to do. Thank you for helping me.

**Comment by Borewit** [comment]
Maybe it gets very slow due to a memory leak? The sum of 5000 metadata objects can grow quite large, with the album art embedded.

**Comment by svenseitan** [comment]
Thank you. Is there a way to improve my code to avoid these memory leaks? I need to browse all the user's music folder to create a music collection in a software, with album art.

**Comment by Borewit** [comment]
Prevent:
```js
filesExt.push(data);
```

Do something like:
```
processMetadata(data);
```

**Comment by svenseitan** [comment]
Thanks, but how do you get a data array as well? I find it hard to capture the interest.

**Comment by Borewit** [comment]
It all depends how you want to use it. If you need to load all 5000 entries in memory, it is going to cost some memory. You can prevent loading cover art, using the `skipCovers` flag. Without the cover art you should be fine. You can also filter the data you really need, e.g. `filesExt.push(data.common);`, but there are plenty of other alternatives.

Maybe use this to get a rough estimation of the object size (in serialized form, in memory it would be much less):
```JSON.stringify(filesExt).length```

**Comment by svenseitan** [comment]
The problem I mention in the first message sometimes occurs when i <200. I tried with the option skipCover: false, and I see that it does not change anything (the problem occurs at about the same frequency) . I have optimized my code for better performance, but that does not change much. I also filter the data I really need (see the full code below).

I use music-metadata for Musiko, a music collection player (https://snapcraft.io/musiko). Musiko retrieves all the music from a given folder (and its subfolders), and then organizes them by albums (with metadata). The software opens on well presented albums.

```
extendAudioFiles: async function(files) {
		let nb = files.length, i = 0
		for (i; i < nb; i++) {
			console.log(i)
			const f = files[i]
			const m = await mm.parseFile(f)
			const mc = m.common
			const data = {
				path: f,
				duration: m.format.duration,
				album: mc.album,
				title: mc.title,
				year: mc.year
			}
			if (mc.disk.no) data.disc = mc.disk.no
			if (mc.track.no) data.track = mc.track.no
			if (mc.picture) data.pictures = mc.picture
			if (mc.discsubtitle) data.discsubtitle = mc.discsubtitle
			if (mc.albumartist) {
				data.artwork = mc.albumartist
				data.artists = [mc.albumartist]
			}
			if (mc.artist) {
				data.artists = mc.artist.split(', ')
				if (!mc.albumartist) data.artwork = data.artists.join(', ')
			}
			files[i] = data
		}
		return files
	}
```

**Comment by Borewit** [comment]
> I use music-metadata for Musiko, a music collection player (https://snapcraft.io/musiko).

That looks like great player to me, nice work!

music-metadata is designed parsing large audio collections, I am surprised to hear it does not work stable for you. I don't see anything wrong with your code, and apparently memory is not the bottleneck neither. If it happens on different files, it does not seems to be related to the input. You also read one file at once, which is frequently an issue.

What if you read the entire folder structure in one Node.js script? Maybe repeat that for 40 times.

**Comment by svenseitan** [comment]
Thank you for Musiko :)
I have tried with one Node.js script and it's miraculous: 200 000 audio files (with album art embedded) without problems, and it's 2 times faster ! My code was client side.
Thank you very much. Music-metadata is very useful for me.
