### ISSUE TITLE
Typing on ICommonTagsResult.comment appears incorrect

### ISSUE THREAD

**Issue by MrNope** [Borewit/music-metadata#50]
The type of `ICommonTagsResult.comment` is declared as `string[]` in index.d.ts in the root of the package, but in practise it appears to actually return:
```
{
    description: string,
    language: string,
    text: string,
}[]
```

Observed when installing v0.9.2.
I had a very brief look through some of the source but I couldn't immediately trace through how the comment tag data was being populated (due to my lack of familiarity with the project).
I can provide further detail if needed.

**Comment by Borewit** [comment]
I will look into it @MrNope, appreciate your feedback.

**Comment by Borewit** [comment]
Should be fixed in [v0.9.3](https://github.com/Borewit/music-metadata/releases/tag/v0.9.3).
A confirmation would be great @MrNope.

**Comment by MrNope** [comment]
Doesn't appear resolved, unfortunately. I've traced the incorrect type declaration to here in the source:
https://github.com/Borewit/music-metadata/blob/6b0b0cf7a2cb06a09f29d42af20791ce4f928979/src/index.ts#L37

Thank you so much for your quick response!

**Comment by Borewit** [comment]
That Type definition is correct. The comments, if any are found, is an array of strings.

The type you found:
 ```JavaScript
{
    description: string,
    language: string,
    text: string,
}[]
````
is a native ID3v2 comment type. 

The way it should work is that, only the _text_ is ending up in metadata.common.comment

**Comment by MrNope** [comment]
Sorry, my bad - it appears to be working in that case. I just checked and I'm now getting `string[]` returned.

Thanks.

**Comment by Borewit** [comment]
No problem at all, good luck with your project.
