### ISSUE TITLE
Don't support gb2312

### ISSUE THREAD

**Issue by Discreater** [Borewit/music-metadata#511]
**Bug description**
Here is my script
```typescript
import * as mm from 'music-metadata';

const file = 'F:\\Music\\李玉刚、谢安琪 - 兰花指.mp3'
mm.parseFile(file)
  .then(metadata => {
    console.log(`file: ${file}`)
    console.log(`title: ${metadata.common.title}`)
    console.log(`artist: ${metadata.common.artist}`)
  })
  .catch(err => {
    console.error(err.message);
  });
```
Here is the output
```
file: F:\Music\李玉刚、谢安琪 - 兰花指.mp3
title: 09.À¼»¨Ö¸
artist: Ð»°²ç÷/ÀîÓñ¸Õ
```

**Expected behavior**
In windows10 file explorer, it can be parsed correctly. Such as
![image](https://user-images.githubusercontent.com/41231596/81504748-9d437580-931d-11ea-881d-649b605a6c7a.png)

```
title: 09.兰花指
artist: 李玉刚/谢安琪
```

**Audio file demonstrating the problem**
[audio.zip](https://github.com/Borewit/music-metadata/files/4606078/audio.zip)

**Comment by Borewit** [comment]
MP3tags is consistent with [music-metadata](https://github.com/Borewit/music-metadata)

![image](https://user-images.githubusercontent.com/23255260/81505194-e24fb380-92ed-11ea-93dc-ef65af87b1c7.png).

Same in foobar 2000:

![image](https://user-images.githubusercontent.com/23255260/81505223-0ca17100-92ee-11ea-96ee-23af81bdefd9.png)

Same on my Windows 10:
![image](https://user-images.githubusercontent.com/23255260/81505281-59854780-92ee-11ea-8211-fc10b9570889.png)

If you edit the file with a good tag editor like:

- [MusicBrainz Picard](https://picard.musicbrainz.org)
- [foobar2000](https://www.foobar2000.org)
- [mp3tag](https://www.mp3tag.de)

you will see [music-metadata](https://github.com/Borewit/music-metadata) will decode these tags just fine.

**Comment by Borewit** [comment]
After updating the tags:

![image](https://user-images.githubusercontent.com/23255260/81505426-52126e00-92ef-11ea-82a3-56152e9d19d7.png)
