### ISSUE TITLE
Is there a way to get the mp3 frame size and offset?

### ISSUE THREAD

**Issue by lionel-lints** [Borewit/music-metadata#523]
Hi there, I am trying to use mm to parse some mp3s I would like to merge, however I am having trouble understanding if there is public access to the mpeg frame size and offsets?

If so I would really appreciate any insight you might have about how to retrieve this information. If this information is currently private only, is it possible to update this so we can get access to this data?

Thanks so much for any thoughts!

**Comment by Borewit** [comment]
In the debug information you find offsets of each frame.

You can log frame offset to the console by setting an environment variable `DEBUG=*`.

Via the API there is no offset information provided.

Can you elaborate a bit what you are planning to do with that information?
Note that the parser may not parse each frame.

**Comment by lionel-lints** [comment]
Thanks for the quick response! We want to cut 2 selections from an mp3 and merge them without a full re-encode (like with ffmpeg or similar utility), but we need to ensure that we are cutting on the frame so that the audio merges correctly. Would it be reasonable to add it as an optional part of the response data? It seems like a useful piece of data for identifying frame locations when cutting the audio...

Also if you of a way to infer this data from the currently exported audio options, that could work as well, and would be much appreciated!

**Comment by Borewit** [comment]
I cut MP3's myself using the DEBUG information, but that is a very manual process. 

Is this a one time thing, or are you planning to publish the cutting utility?

**Comment by lionel-lints** [comment]
Trying to implement this in an app we are going to publish. Yeah if this was a one time deal I am sure I could sort it out, but it'd be great to get it going so we could use mm programatically. Is there some reason this metadata isn't already exposed?

**Comment by Borewit** [comment]
> Trying to implement this in an app we are going to publish.

Nice.

> Is there some reason this metadata isn't already exposed?

1. There is no interest in this information I guess, I think you are the exception
2. It's format dependent information, and not obvious to collect because it is not necessary available since this is not an audio parser, but a metadata parser. But it some cases it is required to process some or even all audio frames, or at least jump from one frame to the next one.

I am very busy lately. I need to address some bugs first before I spend time on new functionality. Feel free to come up with a PR.

**Comment by lionel-lints** [comment]
Thanks for the thoughts! I will take a look and see if I can put together a PR, do you have any suggestions for what I should look at? I was going to investigate the MPEG parser and see if I could change some of the private keys, I am not sure I understand how the application is structured. Any thoughts you might have about how I should approach this would be helpful!

**Comment by Borewit** [comment]
Yes the [MpegParser](https://github.com/Borewit/music-metadata/blob/master/lib/mpeg/MpegParser.ts) is probably the place to collect the frame information. It has access to the options provided. 

The offset of an MPEG frame (and the frame count is there): 
https://github.com/Borewit/music-metadata/blob/14f59c937b40d4eb42f38c2ba8533ba4530e5f2c/lib/mpeg/MpegParser.ts#L373

You probably want to keep the offsets of the headers as well (there maybe multiple!)

[common/MetadataCollector](https://github.com/Borewit/music-metadata/blob/master/lib/common/MetadataCollector.ts) is used to store and collect metadata from the parsers. 

API is divided in:
-  common metadata: format independent metadata. The user doesn't care what the audio format is, the same API is used independent of the underlying format.
- format: audio format information, technical details, but also **format independent**
- native: access to original header tags, grouped per header format

There maybe little challenge how to fit this into the API. Maybe chapter interface could give a little inspiration:
https://github.com/Borewit/music-metadata/blob/14f59c937b40d4eb42f38c2ba8533ba4530e5f2c/lib/type.ts#L452   

Note the observer call back in [option](https://github.com/Borewit/music-metadata#options) for notification while parsing, especially if you make it go through the entire audio file to collect frame offsets, this may a relevant option.

If I could use your application to cut my audio tracks, that would be great. With an MP3, I would like to be able keep prefixing headers, 10 audio frames, and the ID3v1 header (possibly APE) which may appear on the end.
