### ISSUE TITLE
"fs" module imported, but not set as dependency or peerDependency

### ISSUE THREAD

**Issue by Definitely-Not-Vlad** [Borewit/music-metadata#549]
**Bug description**
Packager cannot find `fs` in node_modules.

**Expected behavior**
`fs` is listed under `dependencies` or at least under `peerDependencies` in this module's `package.json`.

Further info:
In [RandomFileReader](https://github.com/Borewit/music-metadata/blob/master/lib/common/RandomFileReader.ts#L2) the file imports `fs`, meanwhile, the `package.json` of the overall module does not contain this as any kind of dependency. I'd suggest adding it.

**Comment by Borewit** [comment]
[fs](https://nodejs.org/api/fs.html) is standard module in node.js, no need to declare that dependency.

If you are trying to run this code in the browser, please ensure [music-metadata-browse](https://github.com/Borewit/music-metadata-browser/) instead. That is **not** depending on [fs](https://nodejs.org/api/fs.html).
