### ISSUE TITLE
wma: embedded picture data is accessible via the common metadata interface

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#57]
I haven't studied the file in details and so I'm not sure how serious the error is, but similarly to #56, I suppose that it should be possible to at least read the rest of the tag?

[sample_problem.zip](https://github.com/Borewit/music-metadata/files/1767576/sample_problem.zip)

**Comment by Borewit** [comment]
Sorry @jirihajek, I was not able to reproduce your issue.

**Comment by jirihajek** [comment]
Sorry, my fault, the file actually is parsed correctly. The only problem there is that the resulting picture contains empty 'data' field. I guess that this might be a bug?

**Comment by Borewit** [comment]
ASF parser could be written better, however. bug should be fixed in [v0.9.7](https://github.com/Borewit/music-metadata/releases/tag/v0.9.7).
