### ISSUE TITLE
Slow duration parsing in some cases

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#58]
Duration parsing for some mp3s can take even several seconds on a fast machine. My guess is that it might be caused by a frequent Promise usage in MpegParser._sync(). Have you already considered another approach? Thanks!

**Comment by Borewit** [comment]
I think your analysis is pretty accurate. It does happen with some MP3, to my best understanding those which are encoded poorly (with frame sync problems).

I tried to switch to different promise modules, didn't help.
I tried to avoid memory consumption in sync loop, trying the best practices of dealing with promises.
Related issues: #34, #26, #45.

I spend a lot of time actually on this. The mitigation is now to limit the number of iterations, to avoid the a crashing down to the ground.

But maybe I looked in the wrong direction. If you have a good alternative, I am open to adapt it.

**Comment by jirihajek** [comment]
I'm afraid that any Promise-based implementation will be quite slow, since Promise handling probably has to result in a significant overhead (when used in an often repeated code). I think that the only way to process the whole file fast is to read it (whole or some bigger chunks) and process mpeg frames in a loop (like some while{}). In order to keep the code responsible, some chunks (like 100kB or so) would probably be preferred. Makes sense?

**Comment by Borewit** [comment]
It does make sense.
