### ISSUE TITLE
Receiving error: 'The "path" argument must be of type string or an instance of Buffer or URL' when using in a typescript project

### ISSUE THREAD

**Issue by 3MUl0R** [Borewit/music-metadata#595]
I've been trying to use music-metadata in my typescript project for a few nights now.  Using mm to read files on my local disk was a breeze, however I have been struggling to read from a url.  I found some [sample code ](https://runkit.com/borewit/parse-mp3-id3v2-4-tags-stream-with-music-metadata) posted by @Borewit that I based this off of:

```(javascript)
import * as https from 'https'
import * as mm from 'music-metadata'

const audioUrl = "https://dl.dropboxusercontent.com/sh/4oeq6mdfj59m5su/AADqRhhAegfGQpvXZt6HnRi_a/Backgrounds_Bird_ST028880.ogg"

function getMetaFromUrl(url:string) {
	https.get(url, (res) => {
		const mimeType = res.headers['content-type'];
		console.log('Parsing the ' + mimeType + '...');
		mm.parseStream(res, mimeType, { skipCovers: true }).then(metaData => {
			console.log("metadata: ", metaData)
		})
	})
}

getMetaFromUrl(audioUrl)
```

Borewit's sample code runs perfectly.  Unfortunately I have been through many revisions of my typescript version and I always end up with the same error:
```(javascript)
unhandledRejection TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received function getPath
    at Object.stat (fs.js:988:10)
    at c:\localdev\mreAudioKit\node_modules\strtok3\lib\FsPromise.js:12:12
    at new Promise (<anonymous>)
    at Object.stat (c:\localdev\mreAudioKit\node_modules\strtok3\lib\FsPromise.js:11:12)
    at Object.fromStream (c:\localdev\mreAudioKit\node_modules\strtok3\lib\index.js:21:31)
    at Object.parseStream (c:\localdev\mreAudioKit\node_modules\music-metadata\lib\index.js:21:37)
    at ClientRequest.<anonymous> (c:\localdev\mreAudioKit\built\server.js:163:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Though my testing I can see that the res from the https.get in my code appears to be identical to what is returned by Borewit's sample code.  So I cannot figure out why it is being rejected by mm.parseStream().  

Thanks in advance for any help!

**Comment by Borewit** [comment]
An example in the [README](https://github.com/Borewit/tokenizer-http/blob/master/README.md) may be helpful.

There are multiple ways to ready from an URL. The sample you found may very out dated. The [https](https://nodejs.org/api/https.html) is not the most user friendly inventions of Node. Better to use a third party https client. 

One way of doing it, using [node-fetch](https://www.npmjs.com/package/node-fetch):
```js
const fetch = require('node-fetch');
const musicMetadata = require('music-metadata');

const url = 'https://test-audio.netlify.app/' + encodeURI('Various Artists - 2008 - netBloc Vol 13 - Color in a World of Monochrome [AAC-40]') + '/' + encodeURI('1.01. Sweet Man Like Me.m4a');

console.log(`Fetching audio from: ${url}`);

(async () => {
  const response = await fetch(url); // Read HTTP headers
  const contentType = response.headers.get('content-type'); // Extract the content-type
  const metadata = await musicMetadata.parseStream(response.body, {mimeType: contentType}); // Parse and read the remainder of the HTTP body
  console.log(metadata.common);
})();
```

Or using [@tokenizer/http](https://github.com/Borewit/tokenizer-http) using [RFC-7233 range request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) transfer:
```js
const mm = require('music-metadata'); // Use module 'music-metadata' in Node.js
const {makeTokenizer} = require('@tokenizer/http');

const audioTrackUrl = 'https://test-audio.netlify.com/Various%20Artists%20-%202009%20-%20netBloc%20Vol%2024_%20tiuqottigeloot%20%5BMP3-V2%5D/01%20-%20Diablo%20Swing%20Orchestra%20-%20Heroines.mp3';

(async () => {
  const httpTokenizer = await makeTokenizer(audioTrackUrl);
  const metadata = await mm.parseFromTokenizer(httpTokenizer);
  console.log('metadata:', metadata);
})();
```

**Comment by Borewit** [comment]
I have updated the [runkit example](https://runkit.com/borewit/parse-mp3-id3v2-4-tags-stream-with-music-metadata/7.0.1).

**Comment by 3MUl0R** [comment]
Thank you!  I was able to successfully implement the node-fetch example.  

I did also try the @tokenizer/http version.  It worked with your test link, however I was not able to get it to work with my link.

Thanks again for the help and all your work music-metadata and other projects!

**Comment by Borewit** [comment]
Thank you so much for the sponsorship @3MUl0R, I just noticed. I though, huh, I have no sponsors. Really very much appreciated!
