### ISSUE TITLE
can't get duration of ogg opus file

### ISSUE THREAD

**Issue by victorafael-com** [Borewit/music-metadata#608]
**Bug description**
I'm getting two different ogg-opus audio files from a provider. but i'm able to get the duration only from one of them.

I'm trying to get the duration using the readme.md snippet:

    mm.parseBuffer(file, {mimeType: "audio/ogg", size: file.length}, {duration: true}).then( metadata => {
        console.log(util.inspect(metadata, {showHidden: false, depth: null}));
    });

**Expected behavior**
I expected to get the duration from both files

**Audio file demonstrating the problem**
I'm attaching two audio files:
36533e60f6133c3d9817a478cc35c525.oga (sample rate: 48000) <- returns the proper duration: 5.28
d04dc145466fdc56525259b8414824df.oga (sample rate: 16000)<- don't return the duration even with duration: true

[test.zip](https://github.com/Borewit/music-metadata/files/5182822/test.zip)

**Comment by Borewit** [comment]
An Ogg file is divided in pages. The last page, should be marked as "last page". This is not the case in the second file, which causes the duration calculation to be bypassed.

I will implement a workaround.

**Comment by Borewit** [comment]
Implemented in [v7.1.0](https://github.com/Borewit/music-metadata/releases/tag/v7.1.0)

**Comment by victorafael-com** [comment]
It seems there's a miscalculation on my file.

It's returning 16.92s but the file is only 5.64

I'm assuming the file size is being calculated considering the sample rate as 48k when my file is 16k because:

16.92 * 16k / 48k = 5,64 (the correct duration).
