### ISSUE TITLE
Wrong ASF Compatibility Object GUID

### ISSUE THREAD

**Issue by jsummers** [Borewit/music-metadata#61]
src/asf/GUID.ts lists the Compatibility Object GUID as 75B22630-668E-11CF-A6D9-00AA0062CE6C. But that is the Header Object GUID. The ASF specification says the Compatibility Object GUID is 26F18B5D-4584-47EC-9F5F-0E651F0452C9.

**Comment by Borewit** [comment]
Thanks for reporting this Jason! 
Apperently [it was a flaw in the spec at one point](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/82d71fc8-a23d-42f8-87fc-10bb712f7ece/http-streaming-wmsp-using-mediafoundation?forum=mediafoundationdevelopment#c34ae0ab-7a22-4960-969b-d122ce39afb8).

**Comment by Borewit** [comment]
Fixed in [v0.9.7](https://github.com/Borewit/music-metadata/releases/tag/v0.9.7).
