### ISSUE TITLE
Wrong duration calculation in some Ogg/Opus audio files

### ISSUE THREAD

**Issue by victorafael-com** [Borewit/music-metadata#610]
**Bug description**
It seems there's a miscalculation on my file (d04dc145466fdc56525259b8414824df.oga).

It's returning 16.92s but the file is only 5.64

I'm assuming the file size is being calculated considering the sample rate as 48k when my file is 16k because:

16.92 * 16k / 48k = 5,64 (the correct duration).

**Expected behavior**
The duration result to be 5.64~

**Audio file demonstrating the problem**
(The same files as [Issue 608](https://github.com/Borewit/music-metadata/issues/608))
[test.zip](https://github.com/Borewit/music-metadata/files/5185376/test.zip)

**Comment by Borewit** [comment]
> I'm assuming the file size is being calculated considering the sample rate as 48k when my file is 16k because:
> 
> 16.92 * 16k / 48k = 5,64 (the correct duration).

Not exactly, it is the other way around, this is how it calculates the duration:

number of samples = 270720 samples
bit-rate = 16000 bits / second
duration = 270720 / 16000 = 16.92 seconds

So the bit-rate should be 48 kbit/sec to get to a duration of 5,64 seconds

I think I found I why. The "absolute granular position" for Opus is not relative to it's own bit-rate, it is always using 48kHz instead. Ref: https://tools.ietf.org/html/rfc7845#page-6

**Comment by Borewit** [comment]
Fixed in [v7.1.1](https://github.com/Borewit/music-metadata/releases/tag/v7.1.1)
