### ISSUE TITLE
Picture format decoding broken in ID3v2.2 header

### ISSUE THREAD

**Issue by bradisbell** [Borewit/music-metadata#614]
[05 I Believe You.zip](https://github.com/Borewit/music-metadata/files/5205698/05.I.Believe.You.zip)

**Bug description**

For the attached file, I call `.parseBlob()`.  In the resulting `metadata.common.picture[0].format`, I get some Chinese character.  I assume this is just corrupt data.

**Expected behavior**

There is album art in this file that I can see with VLC.  It would be great if this library could provide it with a type.  If not, I think it should throw an error or not provide the picture.

Let me know if you need more samples... I have a handful of these with the same issue.  Thanks!

**Comment by Borewit** [comment]
I think the decoding of the format field is done incorrect. It is decoded is a uni-code field, but probably should be read as `ISO-8859-1`:

> **If nothing else is said a string is represented as ISO-8859-1
   [ISO-8859-1] characters in the range $20 - $FF.** All unicode strings
   [UNICODE] use 16-bit unicode 2.0 (ISO/IEC 10646-1:1993, UCS-2). All
   numeric strings are always encoded as ISO-8859-1. Terminated strings
   are terminated with $00 if encoded with ISO-8859-1 and $00 00 if
   encoded as unicode. If nothing else is said newline character is
   forbidden. In ISO-8859-1 a new line is represented, when allowed, with
   $0A only. Frames that allow different types of text encoding have a
   text encoding description byte directly after the frame size. If
   ISO-8859-1 is used this byte should be $00, if unicode is used it
   should be $01.

Ref: https://id3.org/id3v2-00

**Comment by Borewit** [comment]
Fixed in [v7.1.2](https://github.com/Borewit/music-metadata/releases/tag/v7.1.2)

**Comment by bradisbell** [comment]
Awesome!  Thank you!!

**Comment by bradisbell** [comment]
Just wanted to confirm, this is working great for me now.  Deployed the patch today.  Thanks again!

**Comment by Borewit** [comment]
> Just wanted to confirm, this is working great for me now. Deployed the patch today. Thanks again!

That is good to hear @bradisbell, thank you for your feedback!
