### ISSUE TITLE
Uploading cover image on Firebase

### ISSUE THREAD

**Issue by demic-dev** [Borewit/music-metadata#625]
**Bug description**
Extracting metadata from an mp3 uploaded file. All metadatas get extracted well, but if you try to send the image (as blob) to Firebase (API url) it won't load all the file. Then, the terminal, will output this (throw an exception, handled with catch):

![Immagine 2020-09-16 221939](https://user-images.githubusercontent.com/59309595/93388255-b9769680-f86a-11ea-9832-1ae02d3115bb.png)

**Expected behavior**
Fully loaded image

**Comment by Borewit** [comment]
This is an issue in the code uploading the image, not to [music-metadata](https://github.com/Borewit/music-metadata).
To prevent this error, make sure all your HTTP headers are send before content is transmitted.
Probably somewhere in `uploadSongs.js`

**Comment by demic-dev** [comment]
Thanks!
