### ISSUE TITLE
Parser doesn't resolve/reject the promise

### ISSUE THREAD

**Issue by danbulant** [Borewit/music-metadata#633]
I've been working on a simple electron based music player and wanted to use this package to get the meta about music.

From debugging, I see that parseFile, parseBuffer and parseStream never returns. I've already looked at possible solutions, like in #486 but this is something else - there's no memory leak and it doesn't even return the first one (regardless if it's valid or invalid). I'm using this from the renderer process, but with node integration on, and id3 parser worked just fine (but that doesn't have support for as many formats).

I also saw that no resources get used, so it doesn't look like infinite loop or memory leak.

**Comment by Borewit** [comment]
> I've been working on a simple electron based music player and wanted to use this package to get the meta about music.

That is good beginning @danbulant. This is the very best tool for the job.

In Electron I strongly advice you to execute [music-metadata](https://github.com/Borewit/music-metadata ) from [main process](https://www.electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes).
I case you really want to execute from the [renderer process](https://www.electronjs.org/docs/tutorial/application-architecture#main-and-renderer-processes) (the browser) you should use [music-metadata-browser](https://github.com/Borewit/music-metadata-browser).

**Comment by danbulant** [comment]
Oh thanks. Could you maybe add some check with error message? Just silently failing and not returning isn't a good practice in my opinion.

**Comment by Borewit** [comment]
> Oh thanks. Could you maybe add some check with error message? Just silently failing and not returning isn't a good practice in my opinion.

I don't think this module is silently failing anywhere and how on earth do you think I should reproduce the issues you run possible into?

The documentation says, don't put cats in the microwave, but I do offer a special cat dryer if you are interested. Then it does not really make a lot sense squeezing the cat in the microwave and see what the result is, does it?

Yet if you do figure out a simple error message to detect there is a cat in the microwave, please send a PR.
