### ISSUE TITLE
Unable to parse aiff files. Error message: FourCC contains invalid characters: 28 63 29 20.

### ISSUE THREAD

**Issue by raikusy** [Borewit/music-metadata#643]
**Bug description**
Unable get metadata for `.aiff` files. It throws an exception.

> Error: FourCC contains invalid characters: 28 63 29 20
> at Object.get (/usr/app/node_modules/music-metadata/lib/common/FourCC.js:14:19)
> at Object.get (/usr/app/node_modules/music-metadata/lib/iff/index.js:12:43)
> at RangeRequestTokenizer.readToken (/usr/app/node_modules/strtok3/lib/AbstractTokenizer.js:28:22)
> at runMicrotasks (<anonymous>)
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async AIFFParser.parse (/usr/app/node_modules/music-metadata/lib/aiff/AiffParser.js:42:37)
> at async Function._parse (/usr/app/node_modules/music-metadata/lib/ParserFactory.js:158:9)
> at async /usr/app/dist/src/fileupload/fileupload.service.js:64:50

Tried using [https://audio-tag-analyzer.netlify.app/](https://audio-tag-analyzer.netlify.app/) too. Same result.

![Screenshot 2020-10-19 at 4 27 15 AM](https://user-images.githubusercontent.com/4938039/96387381-66726500-11c3-11eb-9181-f134045b48d6.png)

**Expected behavior**
It should parse the metadata.

**Audio file demonstrating the problem**
[File link](https://rr-s3.ovechr.com/local/audio/aiff/05c5e92e-2c8a-4954-85c0-fe0ca1385254_09_-_No_Sanctuary_Here.aiff)

**Comment by Borewit** [comment]
The para-thesis of the Tag `(C) ` the exception in the [FourCC](https://en.wikipedia.org/wiki/FourCC).

**Comment by Borewit** [comment]
Fixed in [v7.4.1](https://github.com/Borewit/music-metadata/releases/tag/v7.4.1).

**Comment by raikusy** [comment]
Amazing! Thanks a lot for responding quick 💜
