### ISSUE TITLE
Default values?

### ISSUE THREAD

**Issue by KeitIG** [Borewit/music-metadata#65]
Hello,

thank you for the great library! 🙌

One of my problem with this library though is when some metadata are undefined (let's say `genre`), I would expect the returned object to have an empty array for the the `genre` key (currently there is nothing).

So I have to manually check all fields, and if they do not exist, provide default values. Could you provide default values (empty arrays, empty strings ect...)? (at least for the most popular fields)

(also, it could be great in the doc to document the reason of the fork :) )

**Comment by KeitIG** [comment]
Or alternatively, would there be a way to have the standards id3 tags in an object like leetreveil/musicmetadata?

https://github.com/leetreveil/musicmetadata#api

**Comment by Borewit** [comment]
Hi Pierre, thanks for your feedback.

I think those are valid points.
I am working on an update with some API changes, I suggest to include

1.  Better API documentation
2. Initialize empty array for the 'common' fields

I think from a technical point of view, the current returned metadata object is actually much more consistent, it is also defined as a TypeScript interface.

I could write down why I forked indeed.

**Comment by Borewit** [comment]
So for all of the following common properties you would expect them to be present with an empty array of no values are found? 

````
  artist?: string,
  artists?: string[],
  comment?: string[],
  genre?: string[];
  composer?: string[];
  lyrics?: string[],
  composersort?: string[],
  lyricist?: string[],
  writer?: string[],
  conductor?: string[],
  remixer?: string[],
  arranger?: string[],
  engineer?: string[],
  producer?: string[],
  djmixer?: string[],
  mixer?: string[],
  grouping?: string[],
  subtitle?: string[],
  discsubtitle?: string[],
  releasetype?: string[],
  musicbrainz_artistid?: string[],
  musicbrainz_albumartistid?: string[],
  'performer:instrument'?: string[],
  notes: string[],
````

**Comment by Borewit** [comment]
Regarding the API documentation, do you think this is more helpful: https://github.com/Borewit/music-metadata/tree/api-documentation?

**Comment by Borewit** [comment]
On the wiki there is also some documentation: https://github.com/Borewit/music-metadata/wiki/Tag-Mapping

**Comment by KeitIG** [comment]
Sorry for the lack of reply ^^ I’ll have a look this afternoon :)
