### ISSUE TITLE
Native comments returned in Common tags

### ISSUE THREAD

**Issue by MrNope** [Borewit/music-metadata#66]
I've just observed ID3v2.2 comments `{ description, language, text }` being returned in the common tags, which is declared as `string[]`.

After updating a problem file to ID3v2.3, I think I have narrowed down that the problem seems to be in handling ID3v2.2 files specifically.

Thanks in advance!

**Comment by Borewit** [comment]
Related issue: #50.

**Comment by Borewit** [comment]
Do you have a sample file @MrNope for me with comment in ID3v2.2 with comment (with no description because in the change above I mapped those to sub-tags)?

**Comment by MrNope** [comment]
[sample-ID3v2.2.zip](https://github.com/Borewit/music-metadata/files/1818738/sample-ID3v2.2.zip)
Here's a sample ID3v2.2 file with a comment that caused an issue for me - free download from https://rushjet1.bandcamp.com/album/forgotten-music

**Comment by Borewit** [comment]
Thanks for your test data, it now became a unit test.
Fixed in [v0.9.10](https://github.com/Borewit/music-metadata/releases/tag/v0.9.10)
