### ISSUE TITLE
Failed to parse FourCC contains invalid characters

### ISSUE THREAD

**Issue by ion-dev** [Borewit/music-metadata#664]
I have a .wav file that fails to parse with error "FourCC contains invalid characters" - see screenshot below.

Here's the track:
https://we.tl/t-E9mKiQ61B0

You can test it using your online example here:
https://audio-tag-analyzer.netlify.app/

The file plays fine in iTunes and many other audio software but fails to parse using MM.

It looks like something to do with junk at the start of the hex data. The solution would be to ignore the junk and start from "fmt", as seen here:

![screenshot](https://user-images.githubusercontent.com/31892822/98017208-d81ef580-1df6-11eb-83ba-c49049bfd2f2.png)

https://forum.pjrc.com/threads/50537-preparing-audio-with-wav2sketch-getting-error-message-in-terminal?p=172955&viewfull=1#post172955

![Audio Tag Analyzer](https://user-images.githubusercontent.com/31892822/98017584-5da2a580-1df7-11eb-859e-5aa966938ac2.png)

**Comment by Borewit** [comment]
Sorry for my late reply, I can no longer download the sample you provided.
Can you please check if #588 ([music-metadata v7.5.3](https://github.com/Borewit/music-metadata/releases/tag/v7.5.3)) solved this issue?

**Comment by ion-dev** [comment]
Hi @Borewit thanks but unfortunately the latest version still does not fix the issue.

Here's the test track again:
https://we.tl/t-UumMmPcKwW

As explained, it looks like something to do with junk at the start of the hex data so one solution would be to ignore any junk data before "fmt", as seen in this image:

![image](https://user-images.githubusercontent.com/31892822/103551708-a8e23e80-4ea2-11eb-8535-29dd98ad83e8.png)
