### ISSUE TITLE
MP3 ID3v2.3 TCON frame - Multiple values not correctly parsed

### ISSUE THREAD

**Issue by tmilker** [Borewit/music-metadata#668]
**Bug description**
TCON parsing doesn't properly handle multiple values, ID3v1 genre references or the new Remix/Cover values IDv2.3.0 adds.

When the TCON frame is set to (52)(RX), it is parsed into an array with a single element of "(52/RX"

It follows the same "/" separator rule that other frames dictate but there's no mention of this behavior for TCON, it's just supposed to be a numeric string or the format above.  See https://id3.org/id3v2.3.0#line-282

**Expected behavior**
It should be parsed into an array with two elements "Electronic" and "Remix" assuming inclusion and use of the ID3v1+Winamp extension tables.

**Audio file demonstrating the problem**
Easily repeatable using foobar2000 to set the Genre value of a test MP3 file to "(52)(RX)" (no quotes)

**Comment by Borewit** [comment]
Confirmed to be a bug, sample file to reproduce the issue:

> Easily repeatable using foobar2000 to set the Genre value of a test MP3 file to "(52)(RX)" (no quotes)

[tcon-issue.zip](https://github.com/Borewit/music-metadata/files/5522797/tcon-issue.zip)

**Comment by Borewit** [comment]
I need a bit more time for this isssue @tmilker. Note that the value you have set is not mapped to the numeric value, because it is escaped as `((52)(RX)`. But there there is definitely room for improvement handling the genre.

**Comment by tmilker** [comment]
Here's your example file corrected with taglib-sharp.  Unfortunately, it doesn't understand the RX designation, so this is one "(52)(53)".  foobar2000 only shows the first genre and loses the rest.  foobar2000 didn't work for writing because it appears to only escape a "(" if it's the first character and not follow the rest of the spec.

[tcon-issue-corrected.zip](https://github.com/Borewit/music-metadata/files/5585067/tcon-issue-corrected.zip)

**Comment by Borewit** [comment]
Would you agree this is the desired behavior @tmilker?:

|ID3v2 `TCON`|expected `common.genre`|
|------------|-----------------------|
|`(52)(RX)`  |`['Electronic', 'Rx']` |
|`((52)(RX)` |`['(52)(RX)']`         |

**Comment by tmilker** [comment]
ID3v2 `TCON`| expected `common.genre`
-|-
`(52)(RX)`|`['Electronic', 'Remix']`
`((52)(RX)`|`['((52)', 'Remix']`

is what I would expect for those two examples.  (RX) and (CR) are defined in the spec as Remix and Cover so if you're expanding (52) to Electronic, those should be expanded too.

**Comment by Borewit** [comment]
> is what I would expect for those two examples. (RX) and (CR) are defined in the spec as Remix and Cover so if you're expanding (52) to Electronic, those should be expanded too.

Agree. 

|ID3v2 `TCON`|expected `common.genre`|
|------------|-----------------------|
|`(52)(RX)`  |`['Electronic', 'Remix]` |
|`(52)(CR)`  |`['Electronic', 'Cover]` |
|`((52)(RX)` |`['(52)(Remix)']`         |
|`(52)(?)`  |`['Electronic'`] |

**Comment by tmilker** [comment]
I don't believe the spec intends for RX/CR to be expanded within numeric strings, only refinements within parentheses.  I agree with everything else.

ID3v2 `TCON`|expected `common.genre`|comment
-|-|-
`((52)(RX)`|`['(52)', 'Remix']`|first is escaped, second is Remix refinement
`((52)((RX)`|`['(52)(RX)']`|just a single string with two escaped opening parentheses
