### ISSUE TITLE
Object `picture.data` will be `undefined` sometime.

### ISSUE THREAD

**Issue by yutent** [Borewit/music-metadata#673]
FilePath: ` /lib/common/MetadataCollector.ts`

```js
 /**
   * Fix some common issues with picture object
   * @param pictureType
   */
  private async postFixPicture(picture: IPicture): Promise<IPicture> {
    if (picture.data.length > 0) {
      if (!picture.format) {
        const fileType = await FileType.fromBuffer(picture.data);
        if (fileType) {
          picture.format = fileType.mime;
        } else {
          return null;
        }
      }
```

Object `picture.data` will be `undefined` sometime.

**Comment by Borewit** [comment]
Can you provide me with an example @yutent?

**Comment by yutent** [comment]
[xiangyiweiming.flac.zip](https://github.com/Borewit/music-metadata/files/5573750/xiangyiweiming.flac.zip)

![image](https://user-images.githubusercontent.com/11972650/99805284-3da10f00-2b77-11eb-9aa0-c67d5ac79130.png)

**Comment by Borewit** [comment]
The FLAC has in addition to the [Vorbis comment](https://en.wikipedia.org/wiki/Vorbis_comment) header also an APE header, which is non standard. The APEv2 header is corrupt, it has a tagged named as `Cover Art (front)` with type `text-utf8` (normally this is binary).

But I can improve the handling of the error a bit.

**Comment by yutent** [comment]
> The FLAC has in addition to the [Vorbis comment](https://en.wikipedia.org/wiki/Vorbis_comment) header also an APE header, which is non standard. The APEv2 header is corrupt, it has a tagged named as `Cover Art (front)` with type `text-utf8` (normally this is binary).
> 
> But I can improve the handling of the error a bit.

Many thanks!
