### ISSUE TITLE
Failed to integrate music-metadata in my project

### ISSUE THREAD

**Issue by rtank27** [Borewit/music-metadata#679]
When I am trying to integrated music-metadata module in my ionic project, I am facing the below error. The below error occurred when I tried running the project.
I was trying to extract music file metadata ( By using parseFile function ).
![Error](https://user-images.githubusercontent.com/74907044/99956339-dfa93d00-2dab-11eb-9d32-26c59adeb6be.PNG)

**Comment by Borewit** [comment]
[music-metadata](https://github.com/Borewit/music-metadat) is a Node.js module. I am note sure how to wire that in Ionic. It seems Ionic has a [file API](https://ionicframework.com/docs/native/file), not sure if you can make that shim the Node.js file API with that. Another option is to implement you own [tokenizer](https://github.com/Borewit/strtok3) library, reading from the [Ionic file API](https://ionicframework.com/docs/native/file)
