### ISSUE TITLE
End-Of-File error of some WMAs

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#68]
Parsing of some WMAs returns error:

Error: End-Of-File
    at c:\mms\mms\node_modules\strtok3\lib\FileTokenizer.js:45:23

Sample file attached.

[sample.zip](https://github.com/Borewit/music-metadata/files/1828674/sample.zip)

**Comment by Borewit** [comment]
Should music-metadata be able to parse truncated or corrupted files?
Therefor related to: 

- webtorrent/webtorrent-desktop#1340
- https://github.com/Borewit/music-metadata/pull/64#issuecomment-372018101
- #60: Return metadata quality information

**Comment by Borewit** [comment]
@jirihajek: Your feedback is highly appreciated.

Fixed in: [v0.9.11](https://github.com/Borewit/music-metadata/releases/tag/v0.9.11)

**Comment by jirihajek** [comment]
Thanks for the fix! I can confirm that it works well now.

> Should music-metadata be able to parse truncated or corrupted files?

In my experience tags are corrupted in some way quite often, which stems from buggy software, but also some lose interpretations of standards, or incomplete files. So, most tag reading libraries accept various forms of corruption, or let's say tags that don't follow specs -- otherwise they look like being buggy compared to other tag readers.

It certainly shouldn't go too far, e.g. to risk crashes of the tag reading library, but whatever can be parsed within some limits of the specs, should, imho, be tried to parsed.

**Comment by Borewit** [comment]
I agree with that.

My comment was also intended as a personal placeholder to follow with some longer term improvement.

One of the references goes back to the use case of the web-torrent application, which is using this parser to parse incomplete files.
