### ISSUE TITLE
ID3v1 strings aren't treated as null-terminated

### ISSUE THREAD

**Issue by jirihajek** [Borewit/music-metadata#69]
Even though ID3v1 strings should be filled with zeros to the length of 30 bytes, some tags happen to contain strings that are zero-terminated and then filled with junk (up to the correct 30 bytes). The junk after the first null would better be ignored. Sample attached.

[id3v1NotNull.zip](https://github.com/Borewit/music-metadata/files/1828715/id3v1NotNull.zip)

**Comment by Borewit** [comment]
That was an ugly one indeed.

Fixed in: [v0.9.11](https://github.com/Borewit/music-metadata/releases/tag/v0.9.11)
