### ISSUE TITLE
Setting tags

### ISSUE THREAD

**Issue by Tyrn** [Borewit/music-metadata#694]
Hi,

Sorry if this is an inappropriate question. As far as I can see, `music-metadata` is just for the reading.

What can I do if I want to edit tags? Research shows that there's nothing remotely approaching `music-metadata` with a function of editing.

**Comment by Borewit** [comment]
It's a very good question @Tyrn, which has been raised before: #10.

[music-metadata](https://github.com/Borewit/music-metadata) is indeed only for reading. I am not aware of an NPM module offering similar functionality for writing metadata tags. Python has [Mutagen](https://github.com/quodlibet/mutagen) which is used by [MusicBrainz Picard](https://picard.musicbrainz.org/).

**Comment by Borewit** [comment]
I close the issue as I am not planning to implement writing capability.
