### ISSUE TITLE
OGG tag parsing error: 'setup header type' not implemented

### ISSUE THREAD

**Issue by LudekStoklasa** [Borewit/music-metadata#70]
Hi, using music-metadata parser I see 'setup header type' not implemented error when parsing tag of this  [file](https://www.dropbox.com/s/yds3nn6e8yij1qg/03%20Biosphere%20-%20Warmed%20by%20the%20Drift.ogg?dl=0)
Other applications like VLC, Foobar2000 or MediaMonkey can read this tag.

**Comment by Borewit** [comment]
If they can read, we can read.

Fixed in issue: [v0.9.12](https://github.com/Borewit/music-metadata/releases/tag/v0.9.12)

**Comment by LudekStoklasa** [comment]
Hi, thanks for the quick fix! It is great to see that this package is so well maintained ;-)
