### ISSUE TITLE
Missing chunk size data for some ffmpeg-made WAVE PCM files results in an incorrect duration

### ISSUE THREAD

**Issue by dpeukert** [Borewit/music-metadata#707]
**Bug description**
When ffmpeg is used to crop a WAVE PCM file using streams, it is unable to write the chunk size, as it is not yet known at that point, and writes `ff ff ff ff` instead (see fluent-ffmpeg/node-fluent-ffmpeg#864). music-metadata interprets that as `4294967295` and uses that to calculate an incorrect duration.

**Expected behavior**
According to https://www.npmjs.com/package/wav#writeroptions, "most WAVE decoders will know [that] means to just read until EOF", which sounds like a plausible solution.

**Audio file demonstrating the problem**
[ffmpeg-missing-chunksize.zip](https://github.com/Borewit/music-metadata/files/5745459/ffmpeg-missing-chunksize.zip)

**Comment by Borewit** [comment]
Should be fixed by #712
