### ISSUE TITLE
music-metadata stuck loading when electron window is refreshed

### ISSUE THREAD

**Issue by MartinBarker** [Borewit/music-metadata#718]
**Bug description**
Hello. I am using the npm package music-metadata v7.5.2 with an electron app. It works fine the first time, but if I refresh the window( ctrl + shift + r) and then try to use my function, it will forever be stuck at the `getTrackNum() mm =  {parseStream: ƒ, parseFile: ƒ, ...... long object... } ` line
```
function getTrackNum(src) {
    console.log("getTrackNum() src = ", src)
    return new Promise(function (resolve) {

        console.log('getTrackNum() init requirerments called')
        try {
            console.log('getTrackNum() mm = ', mm)
            mm.parseFile(src).then(metadata => {
                    console.log('getTrackNum() metadata = ', metadata)
                    resolve(metadata.common.track.no)
                })
                .catch(err => {
                    console.error('getTrackNum() err = ', err.message);
                    resolve(null)
                });

        } catch (err) {
            console.log('getTrackNum() err caught = ', err)
        }

        //console.log('getTrackNum() end')
        //resolve(null)

    });
}
```

**Comment by MartinBarker** [comment]
I've been having this issue for the past 3 months: https://stackoverflow.com/questions/64003204/electron-music-metadata-not-working-after-refresh-ctrlshiftr

**Comment by Borewit** [comment]
I hear your frustration @MartinBarker. 

I am not sure if I can help you, as it does not sound like an issue with music-metadata.

Which Electron process is calling music-metadata? The _renderer process_ or the _main process_?

Note that the `.catch` may also catches calls which occurred in the callback! 

I suggest to do something like this instead:
```js
function getTrackNum(src) {
  console.log("getTrackNum() src = ", src)

  console.log('getTrackNum() init requirerments called')
  console.log('getTrackNum() mm = ', mm)
  return mm.parseFile(src).then(metadata => {
    console.log('We got all metadata', metadata)
  }, err => {
    console.error('For some weird reason we could not get the metadata', err.message);
  });
}
```

Be aware that streams can only be read once.
Are you sure you need to read (parse) from a stream? Where is you audio track coming from or located?

Can you provide an application  instructions demonstrating the issue?

**Comment by Borewit** [comment]
Even though I think I figured out [which project](MartinBarker/audio-archiver) you have the issue in, I am not able to reproduce the issue you experience.

Reloading the Electron app with <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>r</kbd> does not effect the retrieval of metadata.

**Comment by MartinBarker** [comment]
Hello sorry I should have included more steps to reproduct, the correct repo to use is `https://github.com/MartinBarker/digify`, clone the repo, checkout into the branch`build-win`, run `npm i` to install everything, then run `electron .` in the root directory to start the project (make sure your using command prompt if on windows, I havent been able to get electron to run in ubuntu linux subsystem)

Once digfiy is open and running, if you click 'create new upload' at the top of the window, can drag audio files / image files into a box. once an audio file is dragged into the box it will call `getTrackNum(src)` (which I tried to change like you mentioned but it did not make a difference).

again, it works fine the first time, but then if you `ctrl + shift + r ` to refresh the electron window (which is just a chromium window) the function now breaks.

Here is the audio+image file I am using to test:


[files.zip](https://github.com/Borewit/music-metadata/files/5762087/files.zip)

**Comment by Borewit** [comment]
I created the same improvements in: https://github.com/MartinBarker/digify/pull/2.

You recommend you code a bit cleaner @MartinBarker:
* Use consistent code style
* Prevent unnecessary code
* Don't check in code solely used for debugging a specific issue
* Rename a repository instead of creating a new one
* Archive (set readonly) repo's which are deprecated

I still cannot reproduce the issue.
