### ISSUE TITLE
Source map comments in npm

### ISSUE THREAD

**Issue by probablykasper** [Borewit/music-metadata#727]
### Bug description
In the `music-metadata` package, there are source map comments at the bottom of the files which point to `.map` files that do not exist:
```js
//# sourceMappingURL=core.js.map
```

I have `music-metadata` required in an Electron preload script, and because of this I'm getting I'm getting over 50 of these warnings in DevTools:
```
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/Users/kasper/dev/git/ferrum/node_modules/music-metadata/lib/dsdiff/DsdiffToken.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

### Expected behavior
No source map comments.

**Comment by Borewit** [comment]
Related to Borewit/strtok3#365

**Comment by probablykasper** [comment]
@Borewit `tsc` has a `--sourceMap` flag. Maybe you could use that for development, and then omit it for production?
