### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by princeahmed** [Borewit/music-metadata#735]
![image](https://user-images.githubusercontent.com/36558734/104986528-60e41f80-5a3d-11eb-9bf5-94a97bb8ee81.png)

**Comment by Borewit** [comment]
Same issue: #549, see https://github.com/Borewit/music-metadata/issues/549#issuecomment-673573891

For a Electron, have a look to changes I made here: https://github.com/MartinBarker/digify/pull/2/files
