### ISSUE TITLE
npm install music-metadata is error

### ISSUE THREAD

**Issue by diosamuel** [Borewit/music-metadata#738]
Hello, im get this error when install music-metadata by npm

![errormusic](https://user-images.githubusercontent.com/42204593/105679578-3f91a080-5f21-11eb-94f7-30fa8fea45ba.jpg)

npm ERR! Unexpected end of JSON input while parsing near '...R7QwvNK63vKbJ+jKKap3x'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CENTOS\AppData\Roaming\npm-cache\_logs\2021-01-25T08_23_11_279Z-debug.log

how that can be happen? :(

**Comment by Borewit** [comment]
I don't think this has anything to do with [music-metadata](https://github.com/Borewit/music-metadata).

Maybe same issue as npm/npm#19072 ?

You might want to try:
 ```bash
npm cache clean --force
```

**Comment by diosamuel** [comment]
It works, thank you so much :smile:
