### ISSUE TITLE
Not reading the number of channels correctly

### ISSUE THREAD

**Issue by natesct** [Borewit/music-metadata#739]
**Bug description**
Displaying Number of Channel as 1 (mono) but the audio is Stereo. I checked with more than one file.

**Expected behavior**
Display Channels as 2

**Audio file demonstrating the problem**

[ff-16b-2c-44100hz.zip](https://github.com/Borewit/music-metadata/files/5865345/ff-16b-2c-44100hz.zip)

**Comment by Borewit** [comment]
I cannot reproduce the issue, the following test passed:

```js
describe('#739', () => {

  it('Parse: ff-16b-2c-44100hz.mp3', async () => {

    const filePath = path.join(issue_path, '#739', 'ff-16b-2c-44100hz.mp3');

    const {format} = await mm.parseFile(filePath);

    assert.strictEqual(format.container, 'MPEG', 'format.container');
    assert.strictEqual(format.codec, 'MPEG 1 Layer 3', 'format.codec');
    assert.strictEqual(format.numberOfChannels, 2, 'format.numberOfChannels');
  });

});
```

**Comment by natesct** [comment]
``return metadata.parseFile(audioFile).then(metadata => {

			// Do great things with the metadata
			isMono = metadata.format.numberOfChannels = 1 ? true : false;
			isCBR = metadata.format.codecProfile = 'CBR' ? true : false;

			if (isMono && isCBR)
			{
				console.log(audioFile);
			}

**Comment by Borewit** [comment]
This is an assignment:
```js
metadata.format.numberOfChannels = 1;
```
it will asign the value1 to `metadata.format.numberOfChannels`:

Should be:
```js
const isMono = metadata.format.numberOfChannels === 1;
```
&
```js
const isCBR = metadata.format.codecProfile === 'CBR';
```

**Comment by natesct** [comment]
Apologies and thanks for getting back to me

**Comment by Borewit** [comment]
No problem @natesct.
