### ISSUE TITLE
Some M4A files do not return anything

### ISSUE THREAD

**Issue by KeitIG** [Borewit/music-metadata#74]
Hello! :)

one of the user of a side project gave me this file, and parsing it via `music-metadata` does not return anything. In Itunes, metadata are correctly extracted.

[4.New.Track.2.Live.zip](https://github.com/Borewit/music-metadata/files/1907960/4.New.Track.2.Live.zip)

![screen shot 2018-04-13 at 17 23 04](https://user-images.githubusercontent.com/1311607/38743646-eb5d64c6-3f3f-11e8-90e3-d37148090cd2.png)

Could it be related to #13?

**Comment by Borewit** [comment]
In the sample file the MP4 metadata atoms are behind the 'mdat' atom causing them to be ignored. I will update the parser to parse the entire file.

**Comment by KeitIG** [comment]
Is this encoding not respecting the spec then? (genuine question, I have no knowledge of id3)

**Comment by Borewit** [comment]
I have no reason to believe it is a spec violation, but I did not really check.
Fixed in issue [v0.9.14](https://github.com/Borewit/music-metadata/releases/tag/v0.9.14).

It looks like the new unit test failed running on Node version 4.

**Comment by KeitIG** [comment]
🙌
