### ISSUE TITLE
WAVE parsing lost most meta data

### ISSUE THREAD

**Issue by WholeMilk** [Borewit/music-metadata#740]
**Bug description**
When parsing WAVE file, most format meta data are lost except for `container` which still correctly identifies as "WAVE".
`Ignore chunk: RIFF/` warnings are present.

**Expected behavior**
Expects format meta data `codec`, `bitrate`, `sampleRate`, `numberOfChannels` etc.

**Audio file demonstrating the problem**
- Wave file used for testing exhibits this issue: https://github.com/Borewit/music-metadata/blob/master/test/samples/wav/ffmpeg-missing-chunksize.wav
- Drag and drop this file to https://audio-tag-analyzer.netlify.app/ (v7.6.3 at the time of writing) demonstrates the issue along with warning message.

**Notes**
- This issue seems to be related to changes in v7.5.3, v7.5.2 does not exhibit this issue.

**Comment by Borewit** [comment]
Should be solved in #741.
