### ISSUE TITLE
Incorrect metadata for mp4 container when first stream is video

### ISSUE THREAD

**Issue by RamonN334** [Borewit/music-metadata#744]
**Bug description**
When first stream is video in mp4 container, lib treats its as audio stream and return incorrect metadata. For example, duration is setting incorrect.

**Expected behavior**
Return correct metadata for mp4 container that contains video stream as first stream

**Comment by Borewit** [comment]
Can you provide a sample file @RamonN334 (zip it first)?

**Comment by RamonN334** [comment]
Yes, of course
[example.zip](https://github.com/Borewit/music-metadata/files/5923293/example.zip)

**Comment by Borewit** [comment]
Fixed in [v7.6.7](https://github.com/Borewit/music-metadata/releases/tag/v7.6.7).
