### ISSUE TITLE
node.js crashes on parsing a m4a file

### ISSUE THREAD

**Issue by nalmir** [Borewit/music-metadata#749]
Hi,
node.js crashes on parsing the following m4a audio file:
https://d3ctxlq1ktw2nl.cloudfront.net/staging/2020-7-17/0a728424-d981-35bc-ee83-07b0f9e87092.m4a

node.js versions tested 12(AWS linux), 14 (windows 10)
music-metadata versions tested 6.4.0, 7.6.7 (the most recent)

**Comment by Borewit** [comment]
Caused by lack of support of MP4 files with a zero-length box (atom). Zero indicates the remaining length.

**Comment by nalmir** [comment]
Can (will) you fix it?.. At least so it doesn't crash the entire app with the following error:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Thank you

**Comment by Borewit** [comment]
@nalmir. I will fix it.

Related to PR #476, which handle 0 length box for `mdat` box specifically.

**Comment by Borewit** [comment]
Fixed in [v7.6.8](https://github.com/Borewit/music-metadata/releases/tag/v7.6.8).
