### ISSUE TITLE
Wav file raising FourCC invalid characters error

### ISSUE THREAD

**Issue by tomallen400** [Borewit/music-metadata#75]
Hi

Am trying to pull audio metadata from a wav file, which has been working fine until now.  A user uploaded a file into the system, and this particular file is raising an error.  The file is playable, so I would assume there aren't any structural issues with the file.

File is here - https://app.box.com/s/djwmrjksxub4lqx30sp99srobsoh0k2e

In reproducing this error, my code is pretty simple - 

```
var file = "Test.wav";
musicMetadata.parseFile(file).then(function(metadata) {
	console.log(metadata);
}).catch(function(err) {
	console.log(err);
});
```
The returned error is - 
```
Error: FourCC contains invalid characters
    at Object.get (/readFileMetadata/node_modules/music-metadata/lib/common/FourCC.js:14:23)
    at Object.get (/readFileMetadata/node_modules/music-metadata/lib/riff/RiffChunk.js:13:43)
    at /readFileMetadata/node_modules/strtok3/lib/AbstractTokenizer.js:15:26

```
Am running 0.9.14 in Node 8.9.1

I see there was a similar problem with OGG files at #62 could this be related?

**Comment by Borewit** [comment]
Thanks for your feedback. 
This RIFF/WAVE file has but more complex structure as I tested against so far.

Issue fixed in: [v0.9.15](https://github.com/Borewit/music-metadata/releases/tag/v0.9.15)
