### ISSUE TITLE
Examples of files not being correctly parsed

### ISSUE THREAD

**Issue by KeitIG** [Borewit/music-metadata#77]
Hello, me again! 👋

Here are a few files whose id3 do not get found :) the tags are correctly found with other players (and `musicmetadata` too if I'm not mistaken) https://drive.google.com/file/d/1v-Oiv2GbCtbFs9yrmmfW7hbBYpMpyecf/view?usp=sharing

Sorry again :p

**Comment by Borewit** [comment]
No problem, I will investigate it Saturday or Sunday.

**Comment by Borewit** [comment]
_01 Uprising.m4a_: Muse vanished, I will investigate that one further, looks like a bug.

**Comment by Borewit** [comment]
Fixed in: [v0.10.2](https://github.com/Borewit/music-metadata/releases/tag/v0.10.2)

**Comment by Borewit** [comment]
I suppose you could not find a similar picture with Carla Bruni? 
Thanks Pierre!

M4A files are (normally) not using ID3 tag headers to store metadata, they are using a M4A atom/box structure.  Most of the atoms are documented in the [QuickTime File Format Specification](https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html), although the structure found audio files does not always seem to line up, or is using Atoms defined for specifically for movies it seems like. Probable still room for improvement.

**Comment by Borewit** [comment]
So the inconsistency is that the meta-data is partly nested in a (Metadata Item List Atom)[https://developer.apple.com/library/content/documentation/QuickTime/QTFF/Metadata/Metadata.html#//apple_ref/doc/uid/TP40000939-CH1-SW24]:

```
  music-metadata:parser:MP4 Ignore: name=moov/trak/mdia/minf/stbl/stco, len=2272 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta, len=3096 on offset=50181 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta, len=2875 on offset=50189 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta/hdlr, len=34 on offset=50201 +0ms
  music-metadata:parser:MP4 Ignore: name=moov/udta/meta/hdlr, len=34 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta/ilst, len=1320 on offset=50235 +0ms
  music-metadata:parser:MP4 metadata-item: name=©nam, len=35 +0ms
  music-metadata:parser:MP4 metadata-item: name=©alb, len=39 +1ms
  music-metadata:parser:MP4 metadata-item: name=trkn, len=32 +0ms
  music-metadata:parser:MP4 metadata-item: name=cpil, len=25 +0ms
  music-metadata:parser:MP4 metadata-item: name=pgap, len=25 +1ms
  music-metadata:parser:MP4 metadata-item: name=tmpo, len=26 +0ms
  music-metadata:parser:MP4 metadata-item: name=©too, len=56 +0ms
  music-metadata:parser:MP4 metadata-item: name=----, len=188 +0ms
  music-metadata:parser:MP4 metadata-item: name=----, len=119 +1ms
  music-metadata:parser:MP4 metadata-item: name=----, len=162 +0ms
  music-metadata:parser:MP4 metadata-item: name=©day, len=28 +1ms
  music-metadata:parser:MP4 metadata-item: name=cnID, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=rtng, len=25 +0ms
  music-metadata:parser:MP4 metadata-item: name=atID, len=28 +1ms
  music-metadata:parser:MP4 metadata-item: name=cmID, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=plID, len=32 +0ms
  music-metadata:parser:MP4 metadata-item: name=geID, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=sfID, len=28 +1ms
  music-metadata:parser:MP4 metadata-item: name=tvsn, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=tves, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=stik, len=25 +0ms
  music-metadata:parser:MP4 metadata-item: name=purd, len=43 +1ms
  music-metadata:parser:MP4 metadata-item: name=rndu, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=rpdu, len=28 +0ms
  music-metadata:parser:MP4 metadata-item: name=©wrt, len=78 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta/gnre, len=26 on offset=51433 +1ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta/©ART, len=33 on offset=51459 +0ms
  music-metadata:parser:MP4 parse atom name=moov/udta/meta/aART, len=33 on offset=51492 +0ms
```
If you set the following environment variable: `DEBUG=*`, you can can that output.

Looks like all of the files you provided are now working, if not let me know.

**Comment by KeitIG** [comment]
Everything is working perfectly, I could release a patch to my app this afternoon, thank you again!
