### ISSUE TITLE
Question: import Buffer from buffer module instead of relying on global Buffer?

### ISSUE THREAD

**Issue by n1ru4l** [Borewit/music-metadata#776]
**Feature Request**

When I switched from Webpack to Vite while depending on music-metadata-browser (which depends on this library) I noticed that I suddenly had to polyfill `Buffer` (https://github.com/feross/buffer) globally by assigning it to `window.Buffer`.

esmodule based bundlers are getting more and more popular and having a global polyfill are considered a bit dirty some (including me).

Since in Node.js the Buffer can also be imported via `import { Buffer } from "buffer"`, it might maybe make sense to import the `Buffer` from there? Then `music-metadata-browser` might also add the npm module `buffer` as a peer dependency?

With that, the global polyfill could be avoided. The only drawback that I see right now is that the code here is getting a bit bigger (more import statements) and in addition when loading this library in a Node.js context and the npm package buffer is loaded instead of the native Node.js buffer 🤔

**Comment by n1ru4l** [comment]
Another question, would be whether the implementation could rather be based on `Uint8Array`, which is part of the ECMASpec and thus available in all environments?

**Comment by Borewit** [comment]
> it might maybe make sense to import the Buffer from there?

No, I disagree with that. This module is written for Node.js. Buffer is part of Node.js API. 

Although I tried to keep https://github.com/Borewit/music-metadata/blob/master/lib/core.ts (which is the shared code between music-metadata-browser and music-metadata) as neutral as possible, with having browser compatibility in mind. It has beeen designed in such a way, that there is for example no dependency to [`fs`](https://nodejs.org/api/fs.html).

> Then music-metadata-browser might also add the npm module buffer as a peer dependency

[buffer](https://www.npmjs.com/package/buffer) is a dependency of [music-metadata-browser](https://github.com/Borewit/music-metadata-browser): https://github.com/Borewit/music-metadata-browser/blob/911491aab856d90ddad90b0dc43d2123abc234a8/package.json#L112

> Another question, would be whether the implementation could rather be based on Uint8Array instead of Buffer, which is part of the ECMASpec and thus available in all environments?

As I replied here: https://github.com/Borewit/music-metadata-browser/issues/417#issuecomment-798400244, I think that is good suggestion, and I have been working on that. One of the issues is that the [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) is limited to utf-8 encoding and decoding in the Node.js implementation.

Related to:
- https://github.com/sindresorhus/file-type/issues/437
- https://github.com/Borewit/token-types/issues/245

**Comment by Borewit** [comment]
After some familiarization with ES modules, I better see your point @n1ru4l.
Please note that I am working towards shaping this as an ES module, and depending on Buffer as part of that seems to be a logical step. It may make [music-metadata-browser](https://github.com/Borewit/music-metadata-browser) obsolete.
Related: #885.
