### ISSUE TITLE
Support for AMR & AMR_WB detection

### ISSUE THREAD

**Issue by redvivi** [Borewit/music-metadata#782]
**Feature Request**
I guess all is in the title :-)

Very useful to use with Google Cloud Platform: https://cloud.google.com/speech-to-text/docs/encoding 

Thanks !

**Comment by Borewit** [comment]
Reference documentation:
- [Foobar Adaptive Multi-Rate audio decoder](https://github.com/unjello/foo_input_amr)

**Comment by Borewit** [comment]
Resolved with https://github.com/Borewit/music-metadata/pull/798
