### ISSUE TITLE
Duration: NaN for m4a Audiobook

### ISSUE THREAD

**Issue by bensaufley** [Borewit/music-metadata#797]
First: thanks so much for this utility. It's great, and it's just what I need for a project I'm working on.

**Bug description**
When running `parseFile(filename, { duration: true })` I'm getting `NaN` for one specific audiobook in `.m4a` format. I've run the script against three others with no problems.

**Expected behavior**
I expect to get a float value for `duration` when I pass `duration: true` to `parseFile`.

**Audio file demonstrating the problem**
I can't upload the audiobook because it's 1.23GB and copyright-protected (or, I should say, there's no DRM but it's copywritten and I'd rather not upload it for that reason), but here's the metadata using ffmpeg and ffmetadata:

[Vagabonds.txt](https://github.com/Borewit/music-metadata/files/6339080/Vagabonds.txt)

And here's a screenshot of the "Info" MacOS shows. You can see Duration here:

![image](https://user-images.githubusercontent.com/331287/115303281-6f6fcf00-a131-11eb-9109-eebabba738c5.png)

As far as I can tell, the file is not corrupted. I am able to play it, and going to the end has the "This has been…" stuff that you hear at the end of books, so it doesn't look like it's cut off early (sometimes a sign of corruption).

**Comment by bensaufley** [comment]
Here's `exiftool`'s output, which also shows duration
[Vagabonds.exif.txt](https://github.com/Borewit/music-metadata/files/6339129/Vagabonds.exif.txt)

**Comment by Borewit** [comment]
Thanks for reporting the issue @bensaufley. Unfortunately it is absolutely undo-able to investigation without the sample. Samples which are passed to me for metadata analysis are used for that purpose only. You could say I do that on behalf of the owner, just like you bring your car to the garage. If turn I turn the original sample into a unit test sample, I take out the content to prevent copyright violations. If that is an issue for you, I don't. If you want you can mail me a private link: <git username>@xs4all.nl.

**Comment by Borewit** [comment]
Could very well be solved by PR #1472.
