### ISSUE TITLE
[tag] isrc improvements

### ISSUE THREAD

**Issue by sayem314** [Borewit/music-metadata#802]
**Feature Request**

Sometimes ISRC is not embedded in `TSRC` but in `TXXX:ISRC`, can we support that?

**Comment by sayem314** [comment]
@Borewit this patch worked for me.

```patch
diff --git a/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js b/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js
index 3be35a6..9f819c2 100644
--- a/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js
+++ b/node_modules/music-metadata/lib/id3v2/ID3v24TagMapper.js
@@ -66,6 +66,7 @@ const id3v24TagMap = {
     TENC: 'encodedby',
     TSSE: 'encodersettings',
     'TXXX:BARCODE': 'barcode',
+    'TXXX:ISRC': 'isrc',
     TSRC: 'isrc',
     'TXXX:ASIN': 'asin',
     'TXXX:originalyear': 'originalyear',
```

**Comment by Borewit** [comment]
Do you feel convenient to create a PR? Clone the repo, create a new branch, apply the patch, commit the change, push the change, go to the original repo and turn your branch into a PR.

**Comment by sayem314** [comment]
Why do I have to create new branch? Why can’t I just commit to master and make PR?

**Comment by Borewit** [comment]
The convention is to create a new branch, so that the master can follow (pull) the changes of the upstream (original) repository. That way you can anticipate on incoming changes. You want to prevent having branches with the same name with different history between the original and the clone.
