### ISSUE TITLE
Capture Audio metadata from URL

### ISSUE THREAD

**Issue by ryangalvaogp** [Borewit/music-metadata#809]
**Feature Request**

It would be less costly for developers who store their audios on online services like Amazon S3 and analyze the audio by the file URL.

Seria menos custoso para os desenvolvedores que armazenam seus audios em serviços online como Amazon S3 e analizar o audio pelo URL do arquivo.

**Comment by Borewit** [comment]
For reading efficient from S3, check: [Reading audio metadata from Amazon S3](https://github.com/Borewit/tokenizer-s3#reading-audio-metadata-from-amazon-s3).

An example how to read from HTTPS: https://github.com/Borewit/music-metadata/blob/master/example/javascript/stream.js

As there are dozens of options how to read from a URL, that is not functionality which directly belongs [music-metadata](https://github.com/Borewit/music-metadata).

I can recommand [got](https://github.com/sindresorhus/got):

```js
const got = require('got');
const util = require('util');
const mm = require('music-metadata'); // music-metadata

const audioUrl = 'https://github.com/Borewit/music-metadata/raw/master/test/samples/MusicBrainz%20-%20Beth%20Hart%20-%20Sinner\'s%20Prayer%20%5Bid3v2.3%5D.V2.mp3';

(async () => {
  try {
    // Stream MP3 sample file from GitHub via HTTP
    const stream = await got.stream(audioUrl);
    const metadata = await mm.parseStream(stream);
    console.log(util.inspect(metadata, { showHidden: false, depth: null }));
  } catch(error) {
    // Oops, something went wrong
    console.error(error.message);
  }
})();
```

**Comment by ryangalvaogp** [comment]
Deu tudo certo! Muito obrigado!

**Comment by ryangalvaogp** [comment]
Deu tudo certo Muito Obrigado!
