### ISSUE TITLE
Wav file duration is wrong for some files

### ISSUE THREAD

**Issue by kisanme** [Borewit/music-metadata#819]
**Bug description**
I generated a wav file using AWS Polly pcm format. The wave file duration is wrong when ran through this library

**Audio file demonstrating the problem**
https://drive.google.com/file/d/1pL3zk97KACmBokqGROZM1bXDAlAxW9Fr/view?usp=sharing

**Comment by Borewit** [comment]
Caused by an odd high WAV chunk length.
