### ISSUE TITLE
Initialization issue on React Native (Android simulator)

### ISSUE THREAD

**Issue by jon-noviggo** [Borewit/music-metadata#826]
### Bug description
I am working on a React Native project using music-metadata and encountered a crash while initializing the library on startup while working inside an Android simulator.  Below is a screenshot of the crash inside the simulator.

![Screenshot_1622215609](https://user-images.githubusercontent.com/59061674/120007467-efe2e480-bfa7-11eb-9f49-ef9d81c311b7.png)

### Expected behavior
The library should initialize without issue within React Native.

### Potential resolution
After looking through the source code, I encountered what I believe to be an illegal character within OggParser.ts which, when removed, resolves the load-up issue.

https://github.com/Borewit/music-metadata/blob/1da017278bb0d564a13e5f8b40e25651123522aa/lib/ogg/OggParser.ts#L110

You can see a better look at this character in the screenshot below, as it is not visually apparent in Github's Web UI.

![Illegal Character](https://user-images.githubusercontent.com/59061674/120006051-7f879380-bfa6-11eb-9452-0e17c413d827.PNG)

**Comment by Borewit** [comment]
The special character as is in the string is a bit ugly, but it what is should.  I escaped the characters in #826.

Can you please provide a sample of the audio file causing issues?

**Comment by jon-noviggo** [comment]
@Borewit Thank you for the quick response!  

The crash occurred on the start-up of the application, and I could not load the application until I removed the special character.  Once removed, I was able to use the library without a problem and scan files from the local device using mm.parseBuffer().   I would be glad to test the escape character change on my Android simulator when ready, I checked out the commit mentioned but it failed to compile as OggParser.ts was missing.

![image](https://user-images.githubusercontent.com/59061674/120079280-23de0880-c081-11eb-8f17-7a9d0b540f3a.png)

**Comment by Borewit** [comment]
The changes I made will not fix your issue. I need to investigate the issue. Removing the special characters will not fix anything, they are there for a reason. Removing them will cause certain files no longer to be recognised and ignored.

**Comment by Borewit** [comment]
Without a sample I cannot investigate this issue any further. Feel free to reopen if additional information is available.

**Comment by jon-noviggo** [comment]
@Borewit, your updates have fixed the issue.  Thank you!
