### ISSUE TITLE
Missing metadata from WAV file

### ISSUE THREAD

**Issue by ffxsam** [Borewit/music-metadata#83]
I exported a WAV file from Adobe Audition with RIFF tags. Unfortunately, the tags are not shown in the metadata:

```js
{ format:
   { dataformat: 'WAVE',
     bitsPerSample: 24,
     sampleRate: 48000,
     numberOfChannels: 2,
     bitrate: 576000,
     numberOfSamples: 29762,
     duration: 0.6200416666666667,
     tagTypes: [ 'exif' ] },
  native: undefined,
  common: {} }
```

WAV file attached.
[test.wav.zip](https://github.com/Borewit/music-metadata/files/1949183/test.wav.zip)

**Comment by Borewit** [comment]
RIFF/EXIF mapping to common was missing, related issue: #28.

**Comment by Borewit** [comment]
Should be better in: [v0.11.1](https://github.com/Borewit/music-metadata/releases/tag/v0.11.1)

If you have an example with more detailed metadata set in the RIFF, I am very much interested in it.

**Comment by ffxsam** [comment]
@Borewit Sure thing! Here you go.

[riff.wav.zip](https://github.com/Borewit/music-metadata/files/1952483/riff.wav.zip)

![image](https://user-images.githubusercontent.com/12532733/39324686-bb15fe2a-4955-11e8-9e50-66848d98aa39.png)
