### ISSUE TITLE
Support "common" (and not only "native") for .webm files

### ISSUE THREAD

**Issue by martpie** [Borewit/music-metadata#835]
**Feature Request**

Hello 👋 

Thank you again for this great library!

Debugging https://github.com/martpie/museeks/pull/590, I realized that maybe a better fix would be to fix it at the package level, rather than the application level, do you think it would be do-able?

Sample files: https://drive.google.com/drive/folders/1m_VdewpLCW5SyKF3QT4n1FtS-D6Dd4iC

**Comment by Borewit** [comment]
If something needs to fixed or augmented, this is the right place and welcome back @martpie.

So I basically see 2 tags which possibly could be mapped to common:

| Webm Tag | common |
 |---|----|
 | `50:ARTIST` | `albumartist` |
 | `50:GENRE`| `genre` |

I could not find any information what this `50:` prefix means or where it comes from. 

Foobar2000 seems to understand these tags so I followed their example. So I follow their example. That is why I propose to map `50:ARTIST`  to `albumartis` and not to `artist`

**Comment by Borewit** [comment]
2277c9058fc4744af49412259568bde2eca210bf would make the following test pass:

```ts
describe('#835', () => {

  it('should parse "Dance Money.webm"', async () => {

    const filePath = path.join(issue_path, '#835', 'Dance Money.webm');

    const {format, common, native} = await mm.parseFile(filePath, {duration: true});
    assert.strictEqual(format.container, 'EBML/webm', 'format.container');
    assert.strictEqual(format.codec, 'OPUS', 'format.codec');

    assert.deepStrictEqual(common.genre, ['hip hop'], 'common.genre');
  });

  it('should parse "Let Me Down Slowly.webm"', async () => {

    const filePath = path.join(issue_path, '#835', 'Let Me Down Slowly.webm');

    const {format, common, native} = await mm.parseFile(filePath, {duration: true});
    assert.strictEqual(format.container, 'EBML/webm', 'format.container');
    assert.strictEqual(format.codec, 'OPUS', 'format.codec');

    assert.strictEqual(common.title, 'Let Me Down Slowly', 'common.title');
    assert.strictEqual(common.albumartist, 'Alec Benjamin', 'common.albumartist');
  });

  it('should parse "tagged.webm"', async () => {

    const filePath = path.join(issue_path, '#835', 'tagged.webm');

    const {format, common, native} = await mm.parseFile(filePath, {duration: true});
    assert.strictEqual(format.container, 'EBML/webm', 'format.container');
    assert.strictEqual(format.codec, 'OPUS', 'format.codec');

    assert.isUndefined(common.title, 'common.title');
    assert.strictEqual(common.albumartist, 'son go ku', 'common.title');
  });

});
```

**Comment by Borewit** [comment]
Is this sufficient, did I miss anything @martpie?

**Comment by martpie** [comment]
I think it looks very good like that! @HaiDang666 what do you think?

**Comment by HaiDang666** [comment]
look good, btw ffmpeg was used to edit that metadata.

**Comment by Borewit** [comment]
The `50:` is caused by a bug in this Matroksa parser, there is no default value type in these tags (type, is album, track etc...). It should fall back to album as the default, but it turns the type ID instead of the string value.
