### ISSUE TITLE
Inconsistent mp4 identification

### ISSUE THREAD

**Issue by PapiOphidian** [Borewit/music-metadata#838]
I'll preface this with; I route all files which I intend to identify via http through this function. I limit the amount of chunks to pass through this module as it tends to go until the end of stream even if unnecessary. 20 chunks is more than enough in all tested cases excluding mp4 files. I have tested without a limit and I still experience this issue.

I have tested only one other video/* type which is an mkv file and it resolved every single time.
All files tested are being fetched from the same CDN.

**Bug description**
When passing any mp4 video through this lib for identification (I have tested roughly 10), whether it actually identifies is hit or miss. Most of the times, it only throws an End-Of-Stream Error. I don't believe I'm encountering race conditions as the code flow from readable initialize to passing to this lib is not asynchronous and works 100% of the time for other supported file types. I have even passed the same video file into it multiple times and sometimes it identifies and most times it doesn't.

**Expected behavior**
The mp4 is identified 100%, if not, most of the time just like other files

**Audio file demonstrating the problem**
This issue has only been tested on HTTP file streaming. Attached is a link to one of my tested mp4s and also the file directly uploaded through github.
https://cdn.discordapp.com/attachments/497161350934560778/861841920057016330/fumo_fear.mp4

https://user-images.githubusercontent.com/25259648/124549074-7ed2f000-dde3-11eb-8674-b1894b39cc60.mp4

**Comment by Borewit** [comment]
Hi @PapiOphidian.

The MP4 parser reads all boxes (atoms, chunks). If it reads from a stream, the entire stream will be read.  If you read from big files, you may want to try [@tokenizer/http](https://github.com/Borewit/tokenizer-http) which selectively retrieves the required ranges. It is not necessary more efficient.

What is important, that you pass the content length to music-metadata. 

Something like this:
```js
const metadata = await mm.parseStream(stream, {size: parseInt(response['content-length'])})
```
[Full example](https://github.com/Borewit/music-metadata-example-got/blob/5f1e9b229076c97d479512c626eae89d7647a050/http-got.js#L12)

This is just an initial response, I will investigate further.

**Comment by PapiOphidian** [comment]
Hey. Thanks for the swift response. I have attempted passing the entire stream before instead of just limiting to just 20 chunks, but that hasn't worked with my current implementation. This is my current implementation.

```typescript
function getHTTPAsSource(resource: string) {
	type ExtraData = { title?: string; author?: string; stream: boolean; probe: string }
	return centra(resource, "get").header(Constants.baseHTTPRequestHeaders).compress().stream().send().then(res => {
		const message: import("http").IncomingMessage = res as any;

		if (!Constants.OKStatusCodes.includes(message.statusCode as number)) {
			message.destroy();
			throw new Error("Non OK status code");
		}

		const mimeMatch = message.headers["content-type"]?.match(mimeRegex);
		if (message.headers["content-type"] && !mimeMatch) {
			message.destroy();
			throw new Error("Unknown file format.");
		}

		const chunked = !!(message.headers["transfer-encoding"] && message.headers["transfer-encoding"].includes("chunked"));
		// chunked is up here because I previously used it to limit how many frames were piped if it was chunked or not.
		const readwrite = new LimitedReadWriteStream(20);
		return metadata.parseStream(message.pipe(readwrite), { mimeType: message.headers["content-type"], size: message.headers["content-length"] ? Number(message.headers["content-length"]) : undefined }).then(parsed => {
			message.destroy();
			if (!message.headers["content-type"] && !parsed.format.container) throw new Error("Unknown file format.");

			const extra: ExtraData = {
				stream: chunked,
				probe: mimeMatch ? mimeMatch[2] : parsed.format.container!.toLowerCase()
			};
			if (message.headers["icy-description"]) extra.title = message.headers["icy-description"] as string;
			if (message.headers["icy-name"]) extra.author = message.headers["icy-name"] as string;
			return { parsed, extra };
		});
	});
}
```

I will try out your suggestion of @tokenizer/http though

**Comment by Borewit** [comment]
I try to reproduce your issue @PapiOphidian. but I don't directly see any problem:

```js
const got = require('got');
const util = require('util');
const mm = require('music-metadata'); // music-metadata

const audioUrlMp4 = 'https://cdn.discordapp.com/attachments/497161350934560778/861841920057016330/fumo_fear.mp4';

(async () => {
  try {
    // Stream MP3 sample file from GitHub via HTTP
    const stream = await got.stream(audioUrlMp4).on('response', async response => {
      const metadata = await mm.parseStream(stream, {size: parseInt(response.headers['content-length'])})
      stream.destroy();
      console.log(util.inspect(metadata, { showHidden: false, depth: null }));
    });
  } catch(error) {
    // Oops, something went wrong
    console.error(error.message);
  }
})();
```
Outputs:
```
{
  format: {
    tagTypes: [],
    trackInfo: [
      {
        codecName: '<avc1>',
        type: 2,
        audio: { samplingFrequency: 640.064, bitDepth: 0, channels: 0 }
      },
      {
        codecName: 'MPEG-4/AAC',
        type: 2,
        audio: { samplingFrequency: 44100, bitDepth: 16, channels: 2 }
      }
    ],
    container: 'isom/iso2/avc1/mp41',
    creationTime: 1904-01-01T00:00:00.000Z,
    modificationTime: 1904-01-01T00:00:00.000Z,
    codec: 'MPEG-4/AAC',
    duration: 31.299433106575965,
    sampleRate: 44100,
    bitsPerSample: 16,
    numberOfChannels: 2,
    lossless: false,
    bitrate: 845597.9349491597
  },
  native: {},
  quality: { warnings: [] },
  common: {
    track: { no: null, of: null },
    disk: { no: null, of: null },
    movementIndex: {}
  }
}
```
I also tried without passing the content-length, and I have the same result.

**Comment by PapiOphidian** [comment]
Perhaps it might be the http lib I was using. I tried the tokenizer you recommended and I was able to extract the meta data with no issues, granted the server provided all of the headers the tokenizer required, which I fallback to the lib I was using if it didn't. Either way, things are working on my end now and I'll keep all of this in mind for future reference. Thank you for your help
