### ISSUE TITLE
mm.parseBuffer throws error this.buf.copy is not a function

### ISSUE THREAD

**Issue by polisen** [Borewit/music-metadata#850]
**Bug description**
mm.parseBuffer throws error this.buf.copy is not a function

**Expected behavior**
correct execution

Any insight would be greatly appreciated.
The files underlying format, encoding, etc has been confirmed to be mp3.

        console.log('file :>> ', file);
          (async () => {
            try {
              const buffer = await file.arrayBuffer()
              console.log(buffer)
              const metadata = await mm.parseBuffer(file, 'audio/mpeg');
              console.log(metadata);
            } catch (error) {
              console.error(error.message);
            }
          })();

![Screenshot 2021-07-16 at 14 37 15](https://user-images.githubusercontent.com/29376308/125948745-8332300b-96b0-4d01-8f5a-a4f2c27f4cef.png)

**Comment by polisen** [comment]
node v.16
macos catalina

**Comment by polisen** [comment]
okey nvm I'm a fucking idiot - anyone has the same problem please refer to music-metadata-browser instead

**Comment by Borewit** [comment]
It is an interesting error actually. If I understood well you tried to use directly [music-metadata](ttps://github.com/Borewit/music-metadata) in your front-end application. 

Apparently you manage to get a kind of working. I suspect [Buffer](https://nodejs.org/api/buffer.html) got poly-filled with [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array). The `copy()` does not exist in [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).

I am actually lately working toward a more multi purpose architecture, so replaced [Buffer](https://nodejs.org/api/buffer.html) with [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) where possible. (Ref: Borewit/token-types#246)

But indeed [music-metadata-browse](https://github.com/Borewit/music-metadata-browser) is the designed for the right adaptations to use [music-metadata](ttps://github.com/Borewit/music-metadata) in a front-end application.
