### ISSUE TITLE
update to 7.11.0 and get typescript error for token-types

### ISSUE THREAD

**Issue by akdj** [Borewit/music-metadata#866]
Hi, 

I was using the v7.8.0 of music-metadata for my TypeScript project, and now I updated it to the v7.11.0, and I get this compile error 
```
node_modules/token-types/lib/index.d.ts:123:44 - error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).

export declare class BufferType implements IGetToken<Uint8Array, Buffer> {

node_modules/token-types/lib/index.d.ts:131:44 - error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).
 export declare class StringType implements IGetToken<string, Buffer> {
```

Did you know how to fix it?

**Comment by jpolo** [comment]
It seems the reason of this bug could be related to  the pinned dependency "file-types": "16.5.2" which depends on "token-types" v3 instead of v4 ?

**Comment by Borewit** [comment]
You need to install `@tokenizer/token` as development dependency: https://github.com/Borewit/tokenizer-token#installation

Reason you did not experience this issue before, because `@tokenizer/token` was declared as normal dependency in one of the other dependencies.

**Comment by akdj** [comment]
Hi, @Borewit  thank you ! That's fixed the issue!

**Comment by Borewit** [comment]
I think I convert `@tokenizer/token` back to a normal dependency.
