### ISSUE TITLE
When I build using TypeScript token-types produce an error

### ISSUE THREAD

**Issue by danias** [Borewit/music-metadata#870]
**Bug description**

`import * as mm from 'music-metadata';`
or 
`import * as mm from 'music-metadata/lib/core';`

When building the project after the import statement is in my code the following errors take place:

node_modules/token-types/lib/index.d.ts:123:44 - error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).

123 export declare class BufferType implements IGetToken<Uint8Array, Buffer> {
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/token-types/lib/index.d.ts:131:44 - error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).

131 export declare class StringType implements IGetToken<string, Buffer> {
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

**Expected behavior**
No error should be thrown

**Comment by Borewit** [comment]
Should be resolved after you update to [v7.11.1](https://github.com/Borewit/music-metadata/releases/tag/v7.11.1)
