### ISSUE TITLE
`picture.format` may not be set correctly

### ISSUE THREAD

**Issue by autopulous** [Borewit/music-metadata#893]
`postFixPicture()` logic has a hole where the `picture.format` will not get set correctly (overwritten by drop through logic path)

`MetadataCollector.ts`

Current Logic:

```js
  /**
   * Fix some common issues with picture object
   * @param pictureType
   */
  private async postFixPicture(picture: IPicture): Promise<IPicture> {
    if (picture.data && picture.data.length > 0) {
      if (!picture.format) {
        const fileType = await FileType.fromBuffer(picture.data);
        if (fileType) {
          picture.format = fileType.mime;
        } else {
          return null;
        }
      }
      picture.format = picture.format.toLocaleLowerCase();
      switch (picture.format) {
        case 'image/jpg':
          picture.format = 'image/jpeg';  // ToDo: register warning
      }
      return picture;
    }
    this.addWarning(`Empty picture tag found`);
    return null;
  }
```

Proposed logic:

```js
/**
   * Fix some common issues with picture object
   * @param pictureType
   */
  private async postFixPicture(picture: IPicture): Promise < IPicture > {
    if (picture.data && picture.data.length) {
      if (picture.format) {
        picture.format = picture.format.toLocaleLowerCase();
      } else {
        const fileType = await FileType.fromBuffer(picture.data);
        if (!fileType) {
          return null;
        }
        picture.format = fileType.mime;
      }
      switch (picture.format) {
      case 'image/jpg':
        picture.format = 'image/jpeg'; // ToDo: register warning
      }
      return picture;
    }
    this.addWarning(`Empty picture tag found`);
    return null;
  }
```

**Comment by Borewit** [comment]
Good catch @autopulous. Can you create a PR? Do you have a sample which makes it fail, so we can add a unit test?

**Comment by autopulous** [comment]
Glad to do a pull request - I actually wanted to do so yesterday, but I guess I need permission to push a branch - (I've never contributed to someone else's project that I wasn't already invited)

I do not have a test case, I only noticed the issue when looking through the code for a very simple function that I need to create.

**Comment by Borewit** [comment]
By cloning the repository, and create a branch on the cloned repo (don't use master branch for that, you may need that to get incoming changes). If you go back to the original repo (mine) you will see you can create a PR from the branch on your clone.

**Comment by autopulous** [comment]
I have cloned to my system, created a branch, and made the changes... when I try to push my branch to your repository I get the following: 

````
git.exe push --progress "origin" fix-picture-format-assignment
remote: Permission to Borewit/music-metadata.git denied to autopulous.
fatal: unable to access 'https://github.com/Borewit/music-metadata.git/': The requested URL returned error: 403
````

I see no way to create a pull request because there's no way for me to push my branch to the repository.

**Comment by Borewit** [comment]
@autopulous, you have skipped on required step, that is to fork on Github. I should have explained that better.  

![image](https://user-images.githubusercontent.com/23255260/131248897-34394dcc-6feb-403d-b4d8-dd19a221e629.png)

Which will create https://github.com/autopulous/music-metadata.

And that one you normally clone local. Instead you have now cloning mine. That is actually a way I start very often, until the point I decide create a PR. So let's follow that approach.

```
git remote set-url origin https://github.com/autopulous/music-metadata.git
```

Now you can push the branch. And yes it will be created on your fork (now called _origin_), not on my repo (_upstream_).

Optionally you can set remote _upstream_: 
```
git remote add upstream https://github.com/Borewit/music-metadata.git
```

This is how it looks like:
![image](https://user-images.githubusercontent.com/23255260/131249108-7e17f8cc-ea3f-4a55-8715-6b0cc8d5ea60.png)

If you pushed the branch, you can go to the upstream repo https://github.com/Borewit/music-metadata and you will see the branch displayed, and offered the option to create a PR.

**Comment by autopulous** [comment]
Thanks for the explanation.

**Comment by Borewit** [comment]
No need to clear an issue, closing is sufficient. It could serve as a lesson learned or maybe the code could be written more intuitive or better clarified by a comment. If we would do everything perfect the first time, we would not have so many commits😉.
