### ISSUE TITLE
Duration is not correct parsing non-PCM wave files

### ISSUE THREAD

**Issue by yuuk** [Borewit/music-metadata#92]
duration is not correct with wav file，and i have set the duration option to true

**Comment by Borewit** [comment]
I rechecked the duration of the wave files used for the unit tests, they seem to have the right outcome.
Can you please provide a sample @yuuk?

The duration flag should not impact parsing wave files.

**Comment by yuuk** [comment]
Thanks for the reply, and  here is the screenshot. 

<img width="875" alt="screenshot" src="https://user-images.githubusercontent.com/9426456/40285962-ba9f5eb8-5cd4-11e8-9fe9-aeda560bcb93.png">

The file's duration is 3'31'', but it resolved with 0.20884353741496597

**Comment by Borewit** [comment]
Thanks for providing the sample @yuuk. This wave file is using a Microsoft 4-bit ADPCM audio encoding. The duration currently assumes the data is raw PCM. The duration is indeed incorrect with such a file, I will look into it.

**Comment by Borewit** [comment]
Thank you for your feedback.
The issue should be fixed in [v1.1.0](https://github.com/Borewit/music-metadata/releases/tag/v1.1.0).
