### ISSUE TITLE
How to obtain track gain 

### ISSUE THREAD

**Issue by cyberwombat** [Borewit/music-metadata#940]
I need to measure the headroom of a track. I see there is a `tracGain` field but after parsing some mp3 and wav I don't see any gain info returned. Is there something I have to enable to obtain this?

**Comment by Borewit** [comment]
Hi @cyberwombat. If the track gain is present in the metadata, you be able to read it. In case it is not defined, it will not be calculated. The module does not decode audio streams.

**Comment by cyberwombat** [comment]
Ah I see. Thank you.
