### ISSUE TITLE
Add size of file to metadata

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [Borewit/music-metadata#963]
Hello, I've been building an app and it would be quite useful if the `parseFile()` returned the file size. I saw in the `parseFile` source code that apparently it already gets the file size, so I imagine it would be just a matter of returning it in the metadata, right?

In the meantime I'm having to put `const { size } = await stat(path);` on my code, making the function slower cause it's called several times in a row.

**Comment by Borewit** [comment]
I am not going to implement it. To many corner cases, as the file size is frequently unknown. Best is to determine the file size outside music-metadata.
