### ISSUE TITLE
Duration of an MP3 file

### ISSUE THREAD

**Issue by ronildo** [Borewit/music-metadata#965]
Hi guys, I'm trying to retrieve the duration of an MP3 file, this used to work fine, but now I'm not able to see the duration of the audio.

Below is the print screen of the console log.
<img width="725" alt="Screen Shot 2021-12-22 at 10 19 01 AM" src="https://user-images.githubusercontent.com/622159/147114813-66bb698b-bef6-45ce-92aa-ff5f53c1ce4f.png">

Any idea what I might be doing wrong?

**Comment by ronildo** [comment]
Found it... my guess it changed the contract to get some values from a buffer as my code was working before.

now we have to pass duration true
const metadata = await mm.parseBuffer(buffer, file.mime, { duration: true });

**Comment by Borewit** [comment]
If the duration is defined in the MP3 header (in the Xing header) or some other way it is predictable without parsing the entire file it should work without the _duration flag_ set.
Only when it really requires to parse the entire file, the _duration-flag_ should make the difference.
If the behavior is any different, please raise an issue and include a sample file.
