### ISSUE TITLE
MP3 file with both v1 and v2.2 tag misses metadata

### ISSUE THREAD

**Issue by thoni56** [Borewit/music-metadata#975]
**Bug description**
When an MP3 file that has tags ID3 v1 and ID3 v2.2 meta data from v2.2 is not transferred to "common".

Running `music-metadata` v7.11.4.

**Expected behavior**
The file has the v2.2 meta data "TBP" which is not transferred to `common.bpm` as expected. The data it is saved in `native[ID3v2.2][TBP]`.

So even if the double ID3 tags might be confusing, `music-metadata` seems to consider the file having ID3 v2.2 format since that metadata is in `native` but there is no ID3 v1 entry.

**Audio file demonstrating the problem**
[01 Betty Lou.zip](https://github.com/Borewit/music-metadata/files/7849866/01.Betty.Lou.zip)

**Comment by Borewit** [comment]
Hello @thoni56 

The MP3 file is indeed a headers ID3v2 and  ID3v1 header, but also an APEv2 header.

Based on their priority, one tag header get precedence over the other and is mapped to `.common`.

These are the priorities:
https://github.com/Borewit/music-metadata/blob/feb15be8bd8da14ab10cca4c1068be2408fa7b1e/lib/common/MetadataCollector.ts#L17

First one, get priority over the others. They are not combined, only one is picked. Trust me, the metadata may inconsistent, and I will get tons of question about weird combinations if I would combine them.

The idea is that a more modern tag header tags precedence over the older one.
So if  an ID3v2.2 tag header is present, that one will be leading for common, and the ID3v1 header is ignored. Which is sensible thing as the later version can capture much more detailed metadata is the older header. 
Yet this algorithm is far away from perfect. An APEv2 header in MP3 file is arbitrary as it kind of non-standard. A smarter priority mapping may give APEv2 a lower priority for this reason.

The tag `ID3v22.TBP` is currently [indeed not mapped to common](https://github.com/Borewit/music-metadata/blob/feb15be8bd8da14ab10cca4c1068be2408fa7b1e/lib/id3v2/ID3v22TagMapper.ts). 

I have no problem adding mapping from `ID3v22.TBP` to `common.bpm`. Would be great if you can tell me where is coming from. I think this tag is non standard, and probably even violating the **informal** iD3v2.2 standard as it not using the custom tag system. I have no problem taking a pragmatic approach (that''s why you can access APEv2), as long it does not harm formal standards.

I hope this clarifies things a bit.

**Comment by thoni56** [comment]
Thank you, @Borewit! Pretty much what I expected. I did not know the priority order, nor that we can actually find which tag/attribute is actually mapped. Nice to know!

Unfortunately I have a lot of files ripped with different software, so I can't tell you where this comes from. What I can say is that iTunes finds and sets the TBP attribute, which is why I started investigating why my software did not pick it up. Indicated also  [here](https://exiftool.org/TagNames/ID3.html#v2_2) (which probably is a heuristic list and not an official standard).

Since the APE tag only contains gain information, I'm guessing that might also come from iTunes (auto-adjust level), but that is just a guess. But then it would seem strange that iTunes would only add this to some files.

Anyway, thanks again, I will probably try to remap the tags to a more standard configuration. It is only the files from one album.

**Comment by Borewit** [comment]
Version [7.11.5](https://www.npmjs.com/package/music-metadata/v/7.11.5) maps the ID3v2.2 `TBP`.

**Comment by thoni56** [comment]
Thanks!

**Comment by Borewit** [comment]
I can strongly recommend [MusicBrainz Picard](https://picard.musicbrainz.org/) for tagging your audio tracks.
