### ISSUE TITLE
Cover Art not being attached to generated m4b?

### ISSUE THREAD

**Issue by bensaufley** [Borewit/music-metadata#976]
**Bug description**

Have recently updated to the latest version of this repo (excellent stuff, thanks!) and it _looks_ like my cover art, despite existing separately next to the generated `.m4b` (so the script knows it's there), is not being embedded in the `.m4b` itself. Here's the command I'm running:

```sh
~/Projects/AAXtoMP3/AAXtoMP3 -e:m4b -A <activation code> -s -t  ~/Downloads/audiobooks --complete_dir ~/Downloads/audiobooks/converted --use-audible-cli-data --audible-cli-library-file ../library.tsv  -l 3 ./<book>.aaxc
```

The `--audible` flags are a recent addition, trying to see if that helped. I also ran without either of them and the same issue is there. AirDropping the file to [BookPlayer](https://github.com/TortugaPower/BookPlayer) results in no cover image being shown. Using [`music-metadata`](https://github.com/Borewit/music-metadata) produces no `metadata.common.picture` metadata. It seems very much like it's not there, even though it's also clear that the script is aware of the image and can either pull it from the `.aax` or use the one provided by `audible-cli`.

**Expected behavior**

Cover image which is visible in aax and aaxc, downloaded via the UI or via the audible-cli, is embedded in the generated `.m4b` and visible in BookPlayer, MacOS Finder, and/or `music-metadata`.

**Audio file demonstrating the problem**

I can share a file that reproduces this privately if an email address is provided.

**Comment by Borewit** [comment]
Expecting different behavior from AAXtoMP3 cannot be filed as a bug in music-metadata.

How can help you?

**Comment by bensaufley** [comment]
Hah! So sorry, should've gone to bed earlier. Meant to file this at AAXtoMP3. Weird.

**Comment by Borewit** [comment]
No worries
